### ISSUE TITLE
gui

### ISSUE THREAD

**Issue by jacho981** [Tyrrrz/YoutubeDownloader#1]
hi,
love this, but i tried to implement it in a wpf proyect and can't get it to work. not very experienced in programing. it doesnt throw any exception or error, but it just freezes when i click on the button that is supposed to run everthing. i suppose the problem is running this line in the button's click event: MainAsync(args).GetAwaiter ().GetResult(); ? isnt this supposed to run in a different thread so it doesnt block the UI? i dont get it, since when i run the cloned project runs fine. but when implementing it in a gui based solution it just freezes. In java there was something called swingworker or something like that where you did this kind of things. For what i've read, in C# there is BackgroundWorker, but i read that it's being substituted by this async/await thing, which is what you use in your code right? so it shoudnt block the gui... damn, if you could help i'd be grateful. i know this Issues spot is not for asking question, but i've been trying like for 6 hours now and i'm kind of desperate. thx and sorry for asking!

**Comment by Tyrrrz** [comment]
Hi.
You are right, this question is neither relevant to the project, nor is it really possible to give a simple answer.
You should read more about async/await pattern and look at some examples. Your GUI application should have async methods awaiting other async methods in a chain which eventually leads to fire-and-forget event handlers.
