### ISSUE TITLE
Sorting videos

### ISSUE THREAD

**Issue by floatas** [Tyrrrz/YoutubeDownloader#10]
It would be nice to be able to sort videos.
By: Title, Date, Length, progress

Also 0.00% is a bit ambiguous. Maybe it can be changed to "Pending..." if it's not currently being downloaded.

**Comment by Tyrrrz** [comment]
>Also 0.00% is a bit ambiguous. Maybe it can be changed to "Pending..." if it's not currently being downloaded.

Fixed
