### ISSUE TITLE
Stuck at 15.0%

### ISSUE THREAD

**Issue by Teezton** [Tyrrrz/YoutubeDownloader#101]
Any video I try to download I'm getting stuck at 15.0%.
![Image 001](https://user-images.githubusercontent.com/5905860/79768286-7ac3cb00-8322-11ea-99e9-db480bd131c8.png)

**Comment by Tyrrrz** [comment]
Does it get stuck perpetually or get unstuck after a few minutes?

**Comment by Teezton** [comment]
> Does it get stuck perpetually or get unstuck after a few minutes?

You were right, after 15 minutes it was finished. 
Sometimes just a little patience is needed ahaha, thanks!

**Comment by Tyrrrz** [comment]
I have also noticed this happen sometimes, not sure why.

**Comment by Tyrrrz** [comment]
The fix for this will be in next release.
