### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by Top1Valla** [Tyrrrz/YoutubeDownloader#102]
It will be more beautiful!

**Comment by polynoman** [comment]
Hey, I might be able to do this. Can you add the "Hacktoberfest" label and assign it to me?

**Comment by andrewkolos** [comment]
@polynoman Heya! I noticed this issue while browsing around Tyrrrz's repos. Just wanted to let you know that I've been working on a dark theme for their discord exporter app that has a very similar UI set up to this one. [PR in-progress here](https://github.com/Tyrrrz/DiscordChatExporter/pull/388). Perhaps you may find this useful by seeing my (initial) approach and some problems I ran into, especially if you happen to be like me and have no prior experience with WPF. I'll let ya know when we've finished over there if you are looking for some inspiration. If you decide to go ahead without me, I'd also love to see how you approach implementing this feature!

**Comment by Tyrrrz** [comment]
@andrewkolos you're free to PR this one too. Take a look at my commits in DCE after your PR to see how I adjusted the changes.

**Comment by andrewkolos** [comment]
I haven't used this app before, but I'll try to take a crack at it this week.

**Comment by polynoman** [comment]
Hey, nice thing that you did it @andrewkolos !
