### ISSUE TITLE
Cannot download private lists

### ISSUE THREAD

**Issue by mdesipris** [Tyrrrz/YoutubeDownloader#108]
Cannot download private lists, only public and the raised error is misleading (http 400)

**Comment by Tyrrrz** [comment]
Can't do much here because YouTube doesn't identify errors based on whether the request was invalid or the playlist is private or doesn't exist.

**Comment by mdesipris** [comment]
What's the error detail you're getting?

**Comment by Tyrrrz** [comment]
On YouTube's side it's always 400 / "Invalid parameters".

**Comment by mdesipris** [comment]
Is authentication on your plans?

**Comment by Tyrrrz** [comment]
No, it's not.

**Comment by mdesipris** [comment]
Noted with thanks. It's an excellent project!

**Comment by Tyrrrz** [comment]
Thanks!
