### ISSUE TITLE
Message about downloading .NET Core seems to point to wrong/outdated page

### ISSUE THREAD

**Issue by fearworksmedia** [Tyrrrz/YoutubeDownloader#110]
Not sure if it was just me but the dialog box that prompts to download .NET Core linked me to a page in my browser that then redirects to:

https://dotnet.microsoft.com/download/dotnet-core/?utm_source=getdotnetcore&utm_medium=referral

I downloaded the first thing that looked like what I needed, but it appears it isn't the "desktop" version that you have linked to in another issue thread:

https://dotnet.microsoft.com/download/dotnet-core/current/runtime

So I had to uninstall the first one I downloaded to install the correct version. Maybe the link to download .NET Core just needs updating?

**Comment by Tyrrrz** [comment]
Yeah, the link it opens is just not user friendly at all. Unfortunately, I can't control that dialog box because it's on Microsoft's side. As far as I know, they're already working on making it better for the next release (.NET 5.0) but that will be a while.

**Comment by glen4cindy** [comment]
Leave it to Microsoft.......

Just like that message that comes up when you are installing Windows 10 "Leave everything to us..."

How comforting. LOL

**Comment by Tyrrrz** [comment]
Unfortunately nothing I can do here :/
Leaving it open so as to avoid duplicates in the future
