### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by dongmin2002345** [Tyrrrz/YoutubeDownloader#111]
Is it possible to add proxy functionality? My network needs a proxy to come out

**Comment by Tyrrrz** [comment]
It should pick up default proxy automatically (as configured in your internet settings).

**Comment by dongmin2002345** [comment]
I tried to set the proxy using IE, IE can access the Internet normally, but the program can not be downloaded, prompting "The connection attempt failed because the connected party did not reply correctly after a period of time or the connected host did not respond", similar to "4K Video Downloader" can Set the agent's IP and port, user name and password on the software, can be downloaded normally

**Comment by Tyrrrz** [comment]
Can you try setting these environment variables?

![image](https://user-images.githubusercontent.com/1935960/84116766-1aefc380-aa39-11ea-9039-e9801623b8af.png)

**Comment by pendave** [comment]
Alright, IE proxy settings is nice.
