### ISSUE TITLE
Error when I try to download a video

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#112]
I always get this error:
![image](https://user-images.githubusercontent.com/39240736/84429194-0b829d00-ac28-11ea-9709-e363a877139f.png)

I dont understand this error, because I only requested two Videos in the last hour from my IP. Why I get this error?

**Comment by derech1e** [comment]
Sry, it was an error on my side.

**Comment by Tyrrrz** [comment]
YouTube has rate control to counter unofficial clients (such as this one) trying to download videos. I'm not sure what's the limit but if it comes up, you just need to wait some time and you can download again.

**Comment by derech1e** [comment]
> YouTube has rate control to counter unofficial clients (such as this one) trying to download videos. I'm not sure what's the limit but if it comes up, you just need to wait some time and you can download again.

I had a switch between my Computer and the Internet. So he hasn't any IPv6 Adress...
