### ISSUE TITLE
Unable to download; keep getting "rate limiting" error

### ISSUE THREAD

**Issue by dev-working** [Tyrrrz/YoutubeDownloader#113]
Haven't been able to download anything. Keep getting this error.
![image](https://user-images.githubusercontent.com/66910012/84594671-f83b2180-ae21-11ea-994c-197a964644bc.png)

I was trying to download from a YouTube playlist.

**Comment by Tyrrrz** [comment]
YouTube has rate control to counter unofficial clients (such as this one) trying to download videos. I'm not sure what's the limit but if it comes up, you just need to wait some time and you can download again.
