### ISSUE TITLE
Download videos that are newer than a specific upload date

### ISSUE THREAD

**Issue by dev-working** [Tyrrrz/YoutubeDownloader#114]
I am interested in downloading from a YouTube Playlist. The owner of this playlist adds new videos to the same playlist from time to time. 

At this time, it is not possible to put in the YouTube playlist URL in the search box and only download new videos since "a specific date".

Would be nice to have this feature.

**Comment by Tyrrrz** [comment]
If you use the "skip existing downloads" option, it will skip videos you have already downloaded. Otherwise, this feature will probably not be implemented, sorry.
