### ISSUE TITLE
Lots of random crashing on large playlists

### ISSUE THREAD

**Issue by dev-working** [Tyrrrz/YoutubeDownloader#115]
Not sure what is causing the problem but there is a lot of random crashing while downloading a big playlist with 300+ videos.

I don't even see an error message. Only notice that youtubedownloader is no longer running and the downloads were aborted.

**Comment by Tyrrrz** [comment]
It would help if you can give me an example playlist where it happens

**Comment by krishnakoumar27** [comment]
Playlist link: https://www.youtube.com/user/theslowmoguys/videos?view=0&sort=dd&shelf_id=1. This playlist has 220+ videos. The Application crashes as mentioned by @dev-working. 

My Settings:
Everything is in Default settings excepts "Maximum concurrent downloads" which I set to 10.

**Comment by Tyrrrz** [comment]
Does it crash at some specific point? I tried to download the playlist and it seems to work so far, but I don't want to wait until it finishes the entire playlist to see if there's an error.

Also, reducing concurrent downloads might actually help.

**Comment by krishnakoumar27** [comment]
-  I tried to download the same playlist again two times with concurrent downloads set to 10. It crashes again. The crash occurrence seems random. For the first try, it crashes after 15 mins and for the second time, it crashes around 22 mins. 

- It works fine when the concurrent download set to 2 and  I was able to download the entire playlist.

- But, it would be great if the application remains stable with the concurrent downloads set to 10. Multiple Concurrent downloads (like setting to 10) help in reducing overall download time.

**Comment by Tyrrrz** [comment]
I think the issue here is that 10 FFmpeg processes might be too much to handle it once.

**Comment by Tyrrrz** [comment]
Did lowering concurrency help?

**Comment by krishnakoumar27** [comment]
Yes lowering the concurrent download <=3 doesn't crashes the application. I tried setting up with 6 and it crashes.

**Comment by Tyrrrz** [comment]
Interesting. Thanks for letting me know.
