### ISSUE TITLE
Failed to perform an HTTP request to YouTube due to fatal failure

### ISSUE THREAD

**Issue by MikeTheToolman** [Tyrrrz/YoutubeDownloader#116]
Using version 1.7.8.0 and attempting to download this video
https://www.youtube.com/watch?v=ULLtTSxFYBs&list=PL3TLgjzPzmUnaddOp60cGS6YEna6CwGEp&index=2&t=0s
I get the error in the subject.

Thanks,
Mike
![error](https://user-images.githubusercontent.com/64294322/85044520-571ad680-b153-11ea-8c1a-81c39658797c.png)

**Comment by Tyrrrz** [comment]
It appears that that playlist does not exist.

**Comment by MikeTheToolman** [comment]
Tyrrrz,

Thanks for replying. If you click the link I provided the video will play. Trying YoutubeDownloader again this morning the problem is the same. There is something amiss. Does it work for you?

Thanks again,
Mike

**Comment by Tyrrrz** [comment]
When I open the link you provided, I can only see the video, not the playlist.
Trying to open the [playlist itself](https://www.youtube.com/playlist/?list=PL3TLgjzPzmUnaddOp60cGS6YEna6CwGEp) says it doesn't exist:
![image](https://user-images.githubusercontent.com/1935960/85726862-2dd3ea80-b6ff-11ea-8d8f-747b33e9bd0f.png)

**Comment by MikeTheToolman** [comment]
Alexey,

 

You’re on it this morning. Thanks.

 

I’m still working to figure this out as I value the use of YoutubeDownloader. I’ve discovered the key to my difficulty. I have this video saved in YouTube in its own folder which YouTube identifies as a “playlist”. When I click on the folder it opens a “playlist” of one video. If I dig the same video out of my YouTube history it has a different link than the one in the folder. Now I understand.

 

The playlist opens with no problem on my computer probably having to do with my Google login being different from yours.

 

Thanks for your patience,

Mike

**Comment by Tyrrrz** [comment]
It's possible that the playlist is private and that your account has access to it but it's not available publicly.
To download only the video, remove the `&list=PL...` part from the URL.
