### ISSUE TITLE
*Trivial* Issue  " Error occured" after close application

### ISSUE THREAD

**Issue by GaboCapo** [Tyrrrz/YoutubeDownloader#117]
Hi, 
i get an trvial Error when i close the application.
I added a Screenshot from that.
Thank you very much for the project at all. 👍 
![YT Downlaoder ISSUE ](https://user-images.githubusercontent.com/39612138/85055055-468f4e00-b19d-11ea-9900-957ea6159f33.png)

Only reproduction information:

I placed the extracted data into the `Program` Folder from my Windows.
Maybe there is/was a Folder on the PC with a old Version.

You can close the Issue, because the Tool works fine, also with that "Error occured" Message 💯

**Comment by Tyrrrz** [comment]
The app needs write access to its directory to save settings. You can run it as admin to fix this issue.

**Comment by GaboCapo** [comment]
Thanks :)
If someone else has this error and wants to switch off the warning: If you always want to start the program as admin, right-click on the program link and select "Properties". In the "Compatibility" tab, activate the "Run program as administrator" option and then save the changes with "Ok".
