### ISSUE TITLE
Unable to download unlisted recording of live stream

### ISSUE THREAD

**Issue by moriakaice** [Tyrrrz/YoutubeDownloader#119]
When trying to download the following video: [https://www.youtube.com/watch?v=jOOOwLCVq0I](https://www.youtube.com/watch?v=jOOOwLCVq0I), I'm receiving an error:
![01 07 2020_07 34 48_REC](https://user-images.githubusercontent.com/202810/86206985-e4a3f080-bb6d-11ea-9abd-9d853221a6ff.png)

**Comment by abyssox** [comment]
The Video is simply not available anylonger.
When i try to watch the video i get "This video has been removed from the uploader".

**Comment by moriakaice** [comment]
Yeah, unfortunately, I can't do anything about it.

**Comment by Tyrrrz** [comment]
Same thing.
![image](https://user-images.githubusercontent.com/1935960/86531930-40ec7480-bece-11ea-9780-824ec9e429b8.png)

It's not unlisted, looks like it's deleted.

**Comment by moriakaice** [comment]
Sure. It is *now* deleted, at the time of posting the report, it was unlisted.

**Comment by moriakaice** [comment]
I do wonder if this has anything to do with (unlisted) recording of live stream on YT.

Nevertheless, since it's now removed, I'll close the issue.

**Comment by Tyrrrz** [comment]
I don't think it's because it was unlisted, probably related to https://github.com/Tyrrrz/YoutubeExplode/issues/407, in which case it either fixes itself after some time or you can try some other download option.
