### ISSUE TITLE
Pause/Stop/Start all downloads

### ISSUE THREAD

**Issue by floatas** [Tyrrrz/YoutubeDownloader#12]
I was trying to download ~200 videos and convert them to mp3, well it would have taken some time. App crached with some socket exceptions.
Maybe it would be possible to add some logic to resume after crash. 
Some idea how it could work:
1. Start downloading videos.
2. When any video is downloaded serialize to file all videos, with tag completed/not completed. (after every video is downloaded)
3. Close/crash app.
4. Start app. Application checks if serialized file exists and if it exists continue. (ignore partial download and start from new).
5. All videos are done, remove file.

**Comment by Tyrrrz** [comment]
I don't want the app persisting any downloads. If there's a problem that causes an exception, I'd rather fix that than introduce a workaround.

**Comment by floatas** [comment]
Then looking from other perspective, long running tasks (large amount of videos and conversion), it would be nice to have pause and continue.
