### ISSUE TITLE
Constant re-encoding

### ISSUE THREAD

**Issue by Hunanbean** [Tyrrrz/YoutubeDownloader#121]
over the last two days a new issue has come up. When i download any video, instead of what it normally does, which is almost a passthrough copy to local, it is now using 100% cpu and re-encoding everything. it is doing this even with videos i had previously downloaded that went 'direct' to hdd without obvious re-encode. due to the limited number of user settings, i do not think this is caused by something i inadvertently changed.

Thank you very much for this project.

**Comment by pedzed** [comment]
I can confirm. I was using v1.7.8 just a while ago and it worked fine. Now with v1.7.9 it uses 100% CPU.

**Edit:** Downgrading works. But it auto updates after exiting to v1.7.9.

**Comment by Tyrrrz** [comment]
Can you give me a video that you were trying to download and tell me which format you were using?
I looked through the code and it's no clear what could've broken this.

**Comment by user123147** [comment]
from what I can gather it happens with video game video, only at 1080p often at 60fps, and maybe recent video
what's weird is that ffmpeg start using 100% of CPU everytime when youtubedownloader reach 15% of the download.
tested on these random game vid :
https://youtu.be/vJWZo0yk_Ok
https://youtu.be/ihDfvhv7g9w

**Comment by 2manyusernamestaken** [comment]
> Can you give me a video that you were trying to download and tell me which format you were using?

I was using a playlist: https://www.youtube.com/playlist?list=PLQ15Iu5Vbki9wWkIoqOvuU940d32C2LyA

Format: mp4

Thanks for looking into it!

**Comment by Tyrrrz** [comment]
> what's weird is that ffmpeg start using 100% of CPU everytime when youtubedownloader reach 15% of the download.

That's not weird, if the streams require transcoding then the total progress is split into 15%+85% (download+transcoding) as it takes the most time. FFmpeg will always use 100% CPU because majority of its work is CPU-bound, so it's not surprising either.

I have found a regression, the mp4 download options were matching with webm audio streams, which lead to transcoding. Will fix.
