### ISSUE TITLE
RequestLimitExceededException: Failed to perform an HTTP request to YouTube because of rate limiting

### ISSUE THREAD

**Issue by Otto1111** [Tyrrrz/YoutubeDownloader#123]
![problem](https://user-images.githubusercontent.com/68665306/88226693-c2812800-cc6c-11ea-852c-03d97ff9dc0e.png)

What can i do?

https://www.youtube.com/watch?v=HtzUkuENtF4

**Comment by Tyrrrz** [comment]
Wait some time (~ 1hour probably) and try again.

**Comment by Otto1111** [comment]
Sorry, has no effect

**Comment by Tyrrrz** [comment]
Can't do anything more than that.

**Comment by Otto1111** [comment]
OK! New IP. It works!
Whats the request limit for you tube?

**Comment by Tyrrrz** [comment]
No clue. It's hidden.
