### ISSUE TITLE
Download mp3 320kbps

### ISSUE THREAD

**Issue by balasratran** [Tyrrrz/YoutubeDownloader#13]
Let me ask how can I download mp3 files 320kbps. Please guide me. 
Thank you very much.

**Comment by Tyrrrz** [comment]
Hi @balasratran,
Copy-paste a video URL and select "mp3" in the format combobox.

**Comment by balasratran** [comment]
Hi @Tyrrrz 
I have tried and can only download mp3 files 124 kbps. Is there any way to download mp3 files with 320 kbps quality?

**Comment by Tyrrrz** [comment]
YoutubeDownloader extracts the highest bitrate audio that YouTube provides. Not all videos provide audio bitrate higher than ~130kb/s.

**Comment by balasratran** [comment]
I understand. Thank you very much.

**Comment by Tyrrrz** [comment]
You are welcome :)

**Comment by mrnams** [comment]
@Tyrrrz  I tried downloading mp3 of one of video and it downloaded with bitrate 124kbps,  from same video I downloaded using browser extension and extension could download audio with bitrate 320kbps.
I tried debugging but could not understand values whether they are in bits/bytes...
