### ISSUE TITLE
"The given key was not present in the dictionary"

### ISSUE THREAD

**Issue by SIMULATAN** [Tyrrrz/YoutubeDownloader#130]
As the title says, that error pops up when trying to download a video.

By the way, I love the Program, great work!
v1.7.12

**Comment by Tyrrrz** [comment]
Does this still happen on latest version?

**Comment by SIMULATAN** [comment]
First, sorry for the late response!

I tried it yesterday without thinking about it, and it worked just as fine as always!
But strangly, I didn't notice any updating, but as far as I know the Downloader updates itself without admin privileges.
Thank you!

**Comment by Tyrrrz** [comment]
Yeah it overwrites itself automatically on next launch. But you can tell if it updated if the version is higher than 1.7.12 ;)
Anyway, it could also be that YouTube "fixed" itself.
