### ISSUE TITLE
Error "Expected end of string, but instead reached end of data"

### ISSUE THREAD

**Issue by Kazandu** [Tyrrrz/YoutubeDownloader#131]
Searching for a Video just throws the error "Expected end of string, but instead reached end of data. LuneNumber: 0 | BytePositionInLine: 56717."

**Comment by Tyrrrz** [comment]
Is this on latest version? Do you get it consistently?

**Comment by Kazandu** [comment]
I'm on Version 1.7.13, happens only on some videos, others work fine. Is there a way to run the tool with logging?

**Comment by Tyrrrz** [comment]
No there isn't. Can you give me search queries/videos where it fails?

**Comment by Kazandu** [comment]
https: // www.youtube.com/ watch?v=5y3xh8gs24c For example makes it throw the error

**Comment by Tyrrrz** [comment]
Looks like the issue is more involved and caused by the fact that some age-restricted videos cannot be downloaded.

**Comment by Tyrrrz** [comment]
I fixed this particular issue in the upstream library, but the video you linked still cannot be downloaded due to an issue tracked here: https://github.com/Tyrrrz/YoutubeExplode/issues/441. Will release an update once/if it's resolved.
