### ISSUE TITLE
Connection attempt Failed error

### ISSUE THREAD

**Issue by shaneb214** [Tyrrrz/YoutubeDownloader#134]
Hi there. Youtube Explode has been working fine for me but recently I've been getting this error. For YoutubeDownloader it says "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond".

I get the same error using youtube explode in my own visual studio project. Was just wondering if you could help, thanks very much 👍

**Comment by Tyrrrz** [comment]
Hi there. Unfortunately, it sounds like the server just straight up timed out. Could be an issue on YouTube's side, could be your connection or routing to them. Nothing we can do on our end but retry and hope it works.
