### ISSUE TITLE
End of data error when trying to download a certain video

### ISSUE THREAD

**Issue by L4v4** [Tyrrrz/YoutubeDownloader#135]
Version: 1.7.13
### Steps to reproduce:
1. Type the following URL into the search bar:<br>
`https://www.youtube.com/watch?v=5y3xh8gs24c` or `https://youtu.be/5y3xh8gs24c`

2. Hit enter or press the arrow to start the search

### Expected Behavior:<br>
The confirmation window opens, asking for the format.

### Actual Behavior:<br>
The following error window appears:
```
Error
Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 62040.
```

### Additional Notes:
* No other video I tried showed this error - they continued with the expected behavior.
* Searching for the title finds the video. However, pressing "Download" instantly shows the status as "Failed".

### Picture of the error:
![image](https://user-images.githubusercontent.com/64252476/94358421-32fb5980-00a1-11eb-98b9-3b28201e6dfd.png)

**Comment by REDPANDAUwU** [comment]
lol i tried downloading the same video too, im pretty sure it has something to do with the japanese characters

**Comment by L4v4** [comment]
A friend of mine was also able to reproduce this error.

However, I don't think that the Japanese characters are the problem - other videos worked fine for me (this was the first occurence in ~500 videos - a lot of them with different types of characters).

**Comment by REDPANDAUwU** [comment]
i just checked and every video on calli's ( https://www.youtube.com/channel/UCL_qhgtOy0dy1Agp8vkySQg ) channel doesnt work with the downloader wtf

**Comment by L4v4** [comment]
They do for me (example: https://www.youtube.com/watch?v=vz7JIBvAFqM) - exept for the one I tried initially.
![image](https://user-images.githubusercontent.com/64252476/94465254-e8243380-01bf-11eb-91c6-1b2aec461533.png)
