### ISSUE TITLE
Only shows audio types on some videos

### ISSUE THREAD

**Issue by chenxuuu** [Tyrrrz/YoutubeDownloader#138]
when downloading some videos, it only show audio files to me
such as this url: https://www.youtube.com/watch?v=yBl--anPq1k
maybe this caused by proxy, I'm not sure

![图片](https://user-images.githubusercontent.com/10357394/95360598-29be8800-08fe-11eb-9c49-9d7d8943ae62.png)

**Comment by chenxuuu** [comment]
same as https://github.com/ytdl-org/youtube-dl/issues/26330 ?

**Comment by Tyrrrz** [comment]
Some videos sometimes don't provide complete media streams. This issue typically resolves itself after a while. My guess is that to fix it YoutubeExplode needs to have https://github.com/Tyrrrz/YoutubeExplode/issues/159 implemented.
