### ISSUE TITLE
Errors occur when downloading multiple videos

### ISSUE THREAD

**Issue by 1gcat** [Tyrrrz/YoutubeDownloader#14]
>YoutubeDownloader: 1.3.1
>OS: Windows 7 X64
>URL: https://www.youtube.com/playlist?list=PLZyAyG4_KmYnvTqe5__NG3bXMrdjYV4Ci

![捕获](https://user-images.githubusercontent.com/43435652/55155245-d6f50380-5191-11e9-81ff-28f343102b1a.JPG)

**Comment by Tyrrrz** [comment]
Looks like something to do with SSL, I can't read the Chinese text.

**Comment by 1gcat** [comment]
> Looks like something to do with SSL, I can't read the Chinese text.

Sorry,I forgot to translate it into English,it means `Could not create SSL/TLS secure channel`

**Comment by Tyrrrz** [comment]
Maybe your local CA list is out of date. Have you tried Windows update?
