### ISSUE TITLE
Exclude format list not working

### ISSUE THREAD

**Issue by abyssox** [Tyrrrz/YoutubeDownloader#142]
Hi,

it seem like the exclude format list function is not working.

I set e.g. ogg to exclude:
![grafik](https://user-images.githubusercontent.com/4539953/96333007-b1776580-1067-11eb-898f-dd28cbcd0fa4.png)

but in the download dialog it still shows ogg as a download option:
![grafik](https://user-images.githubusercontent.com/4539953/96333032-d8ce3280-1067-11eb-84fb-ccf1ad57b83b.png)

regards
abyssox

**Comment by Tyrrrz** [comment]
@beawolf could you take a look?

**Comment by mustafacagataytulun** [comment]
@Tyrrrz I will look into it, and send a PR for a fix as soon as possible.
