### ISSUE TITLE
Channel batching doesn't work

### ISSUE THREAD

**Issue by vgzhn** [Tyrrrz/YoutubeDownloader#144]
until yesterday(i think, I have auto-update activated) entering a channel url(e.g. https://www.youtube.com/user/PewDiePie) would result in all uploads being listed. Now that doesn't work anymore.

**Comment by Tyrrrz** [comment]
Does it work on CI build?
https://github.com/Tyrrrz/YoutubeDownloader/actions/runs/315724845

**Comment by vgzhn** [comment]
I'm not able to replicate the issue. Everything is working as expected. Thanks for your attention and the whole project!
