### ISSUE TITLE
Unable to download any videos as of today

### ISSUE THREAD

**Issue by Hunanbean** [Tyrrrz/YoutubeDownloader#148]
Hello. I am unable to download anything. It just fails, nearly instantly.
The lists work, i can select videos, etc. but when it tries to actually download, they All fail.

Thank you for your project

**Comment by Hunanbean** [comment]
Update error message

error '}' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 8380

**Comment by Jeager2** [comment]
Look at the answer I provided here: https://github.com/Tyrrrz/YoutubeDownloader/issues/146#issue-726030394
It might help as I ran into this today...
