### ISSUE TITLE
YouTube-dl has received a DMCA takedown from RIAA. Will it affect this repo in the future?

### ISSUE THREAD

**Issue by cuno92** [Tyrrrz/YoutubeDownloader#149]
[YouTube-dl has received a DMCA takedown from RIAA (github.com/github)](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md)

**Comment by Tyrrrz** [comment]
Hi.
It's still not clear how the situation will resolve itself for youtube-dl, but in any case it's concerning.
At the very least, it seems like the screenshots in the readme should be updated to not show Imagine Dragons. :)

**Comment by cuno92** [comment]
Thanks for answering & thanks again for useful tool
