### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by fullsharez** [Tyrrrz/YoutubeDownloader#15]
hello as the title says it works over at all and its whatever the version php even changing server so ip

**Comment by Tyrrrz** [comment]
Hi,
I'm not sure I understand what you mean. What exactly is not working? What does it have to do with php version?

**Comment by fullsharez** [comment]
some video including this one I have the latest version

example test https://www.youtube.com/watch?v=oqLLVsYLR0c

**Comment by fullsharez** [comment]
I tested under several server notament a server with php7

**Comment by Tyrrrz** [comment]
Downloads just fine for me. Are you sure we're talking about the same YoutubeDownloader? This one doesn't use PHP.

**Comment by fullsharez** [comment]
no sorry it's a mistake could you close it
