### ISSUE TITLE
Exclude format list still not working

### ISSUE THREAD

**Issue by abyssox** [Tyrrrz/YoutubeDownloader#152]
Hi,

i'm sorry but the exclude format list is still not working.
I tested with only "ogg", only "mp3" and "ogg,mp3".

regards
abyssox

**Comment by Tyrrrz** [comment]
Are you sure? It seems to work for me.

**Comment by abyssox** [comment]
Yes, pretty sure:

![image](https://user-images.githubusercontent.com/4539953/100317235-4f8e1200-2fbc-11eb-9357-8bb151ca7630.png)

**Comment by Tyrrrz** [comment]
Ah, I checked only on single video downloads.
