### ISSUE TITLE
ogg download fails with exception

### ISSUE THREAD

**Issue by abyssox** [Tyrrrz/YoutubeDownloader#153]
Hello,

when i try to download a video as ogg it fails with an exception:
![image](https://user-images.githubusercontent.com/4539953/97135422-802a2400-1750-11eb-846b-839ae06cc620.png)

mp3 and mp4 work fine.
I verified it with various videos.

regards
abyssox

**Comment by derech1e** [comment]
I think this Issue can probably be closed. The Video(-ID) that is shown at the photo: "flWLT0QVPzw" got deleted.
Are there any other way to recreate this issue?
For me it works fine.

**Comment by Tyrrrz** [comment]
Ah, I didn't realize it was deleted. It might also be the cause of the original error.
