### ISSUE TITLE
JsonReaderException: 'a' is an invalid start of a property name

### ISSUE THREAD

**Issue by zjjohncq** [Tyrrrz/YoutubeDownloader#156]
when we try to extract the video https://www.youtube.com/watch?v=Q7QDDBRwwNg&t=6s, we got the following error:
![Capture](https://user-images.githubusercontent.com/49753486/98568851-8c010480-227f-11eb-90cc-332f6ae7c7dd.PNG)

**Comment by lanye74** [comment]
I'm getting the same error :/

**Comment by Tyrrrz** [comment]
Related https://github.com/Tyrrrz/YoutubeExplode/issues/479

**Comment by cycle00** [comment]
I'm also getting the same error. I've also verified that I have the correct version of DotNet installed.

**Comment by leonard2z** [comment]
Here with the same error

**Comment by ceramicbrad** [comment]
Same error, and all updated system. Error continued with "expected a '"' linenumber: 0

**Comment by RomeoDavide91** [comment]
I've same error, has anyone solved?

**Comment by cuno92** [comment]
i also got this error.But when i try to debug , i reference YoutubeExplode library as ProjectReference not nuget Reference and publish again it work well.
![image](https://user-images.githubusercontent.com/58431215/100533554-76f11300-3238-11eb-91ea-2b6c32681cdf.png)
