### ISSUE TITLE
Support .NET Core 5.0 Runtime

### ISSUE THREAD

**Issue by giwrgosmant** [Tyrrrz/YoutubeDownloader#157]
I tried to use the app with the latest version .NET 5.0 Runtime (which link is on Github FAQ) but it didn't worked. I had to use older version 3.1.
Any plans to update the app working with the latest version of .NET Core Runtime or mention in the FAQ that needs 3.1 version? 
Thanks! 😋

**Comment by Tyrrrz** [comment]
Probably going to do the latter to avoid breaking changes. Thanks for letting me know.

**Comment by Tyrrrz** [comment]
Updated readme
