### ISSUE TITLE
VideoStreamInfo is Null

### ISSUE THREAD

**Issue by mostafa901** [Tyrrrz/YoutubeDownloader#16]
Thanks for this Great tool.
you application was working very well for the past week. suddenly it returns null exception reference.
This is the You Tube video for test:
https://www.youtube.com/watch?v=Ko-ZboCzR64&list=WL&index=7&t=0s

![image](https://user-images.githubusercontent.com/12208720/56413278-04683500-6298-11e9-9176-269763cdea7c.png)

**Comment by Tyrrrz** [comment]
Hi, indeed YouTube has made some changes that broke the library YoutubeDownloader uses.
You can track the progress here: https://github.com/Tyrrrz/YoutubeExplode/issues/229

**Comment by mostafa901** [comment]
Many thanks for that quick response. I tracked the progress, and Downgrading youtube explode lib, resolves the issue for the link, many thanks @Tyrrrz

**Comment by yxd0018** [comment]
> Many thanks for that quick response. I tracked the progress, and Downgrading youtube explode lib, resolves the issue for the link, many thanks @Tyrrrz

How do I use this in youtube-dl?

**Comment by Tyrrrz** [comment]
New version is out
