### ISSUE TITLE
No selection in dropdown are available

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#164]
When I try to download the Video, there are not options for Quality and Subtitles available. I can't find out exactly where the error is coming from. Can someone help me?

Link: https://www.youtube.com/watch?v=uRs56jVc1S4&feature=youtu.be

![image](https://user-images.githubusercontent.com/39240736/101660846-eb516080-3a47-11eb-91aa-8f0ef5a380e1.png)

**Comment by Tyrrrz** [comment]
Do you see any streams if you try YoutubeExplode.Demo from https://github.com/Tyrrrz/YoutubeExplode/tree/master/YoutubeExplode.DemoWpf?

Sometimes YouTube just straight up returns no streams.

**Comment by derech1e** [comment]
Nop, there are no streams at all. 
![image](https://user-images.githubusercontent.com/39240736/101678873-d7fdbf80-3a5e-11eb-901f-f4bb4f3acc47.png)

**Comment by Tyrrrz** [comment]
Yeah sometimes that happens. Usually streams show up after some time. Not sure what exactly to do about it, maybe https://github.com/Tyrrrz/YoutubeExplode/issues/159 would help with it, but no guarantee.

**Comment by derech1e** [comment]
Mhhh, very strange. Now there are streams show up.
I will close this Issue here.
