### ISSUE TITLE
Lack of installer

### ISSUE THREAD

**Issue by AGaiki** [Tyrrrz/YoutubeDownloader#167]
Hey there!
I really like this program, and have used it for a few months. However, I've noticed that there isn't an installer, which might be a put-down for newer users. I'd like to suggest that you consider creating an installer for this program, in order to simplify the installation process. I also do have some experience making an installer, and have done so for this program, if you are interested!

**Comment by Tyrrrz** [comment]
Hi.
Thanks for the interest. I'm not planning to add an installer because I don't want the extra cost associated with its maintenance, continuous delivery concerns, and autoupdating.
I don't mind if it's a put down for newer users since ultimately it's just a project I use for myself.
