### ISSUE TITLE
Program only shows audio download

### ISSUE THREAD

**Issue by yxd0018** [Tyrrrz/YoutubeDownloader#17]
Try to download one clip https://www.youtube.com/watch?v=ceM8ho3kFz0
youtube-dl can do it through command line but this app only shows audio choice.

**Comment by Mike-7777777** [comment]
same problem.

**Comment by Tyrrrz** [comment]
Hi, this is a known issue caused by recent YouTube changes. #16

**Comment by yxd0018** [comment]
> Hi, this is a known issue caused by recent YouTube changes. #16

How do I use YoutubeExplode beta here?

**Comment by Tyrrrz** [comment]
If you can compile the source code, you can update the corresponding nuget package. I will update YoutubeDownloader when YoutubeExplode changes are in master.

**Comment by Tyrrrz** [comment]
New version is out
