### ISSUE TITLE
Timestamp in video

### ISSUE THREAD

**Issue by cowen1337** [Tyrrrz/YoutubeDownloader#170]
I wold like it when i cold set it up to split videos with preexisting timestamps. I seek such a downloader since i cold think about the use of it.

**Comment by Tyrrrz** [comment]
What do you mean by "split"? Do you mean start the video from a specific timestamp like YouTube allows you to?

**Comment by arsinclair** [comment]
I think what he means is to be able to clip video based on timestamps. So if there are 3 timestamps in the video, the downloader will download it in 4 separate pieces.

**Comment by cowen1337** [comment]
I mean what arsinclair wrote. Sorry English is not my native language.

**Comment by Tyrrrz** [comment]
I think it's pushing the scope of the project a bit too wide. I'd suggest downloading the whole video and then splitting them in specialized tools like FFmpeg or video editors.
