### ISSUE TITLE
.NET 3.1 problem

### ISSUE THREAD

**Issue by Dark3n89** [Tyrrrz/YoutubeDownloader#174]
I have a problem that the application cannot be run on 99% of computers even after installing netcore 3.1, what is missing on the computer?

**Comment by Tyrrrz** [comment]
Are you installing from the download link in the readme?

**Comment by Dark3n89** [comment]
Yes but no stress I know how to work this and it always works on my computer, but it's a mystery why it sometimes doesn't work, is some c ++ missing or something like that?

**Comment by Tyrrrz** [comment]
> is some c ++ missing or something like that?

Only if you are running Windows 7, otherwise should be fine.
