### ISSUE TITLE
List download error

### ISSUE THREAD

**Issue by zelohon** [Tyrrrz/YoutubeDownloader#175]
![QQ截图20210127222855](https://user-images.githubusercontent.com/36800197/106005307-10308e80-60ef-11eb-98ae-621e13043d60.png)

Most list downloads are wrong. Why?

**Comment by Tyrrrz** [comment]
Can you hover over "Failed", it should show the reason.

**Comment by zelohon** [comment]
> 可以悬停在"失败"上，它应该显示原因。

![S0@5FOH6_H1$PQ7@D$GE1DN](https://user-images.githubusercontent.com/36800197/106138407-11bd8d80-61a7-11eb-92c3-12185fa8fd2f.png)

**Comment by zelohon** [comment]
> Can you hover over "Failed", it should show the reason.

If you click to try again, there is still a chance to download successfully, hope to fix this problem!

Request to add the cover map to the video download at the same time.

**Comment by zelohon** [comment]
> Can you hover over "Failed", it should show the reason.

Another problem is that if you close the program accidentally, the download list disappears! This is troublesome!

**Comment by zelohon** [comment]
![2](https://user-images.githubusercontent.com/36800197/106149866-b21aae80-61b5-11eb-9c08-54db978d6d29.png)
