### ISSUE TITLE
Can't download age-restricted video

### ISSUE THREAD

**Issue by gmy77** [Tyrrrz/YoutubeDownloader#177]
I guys, i receive an error:

![Error01](https://user-images.githubusercontent.com/1058226/106811203-48474c80-666e-11eb-81ab-3ad5ea68bc07.jpg)

i find this error is related to "**AGE VERIFICATION**". Exist any way to bypass this or to add an option to "confirm" the AGE UP and to continue download? 

I find this type of error, for example, in this :

**https://www.youtube.com/watch?v=arONMWblvG8**

Thanks for any suggestions. 

Gimmy

**Comment by Tyrrrz** [comment]
Related: https://github.com/Tyrrrz/YoutubeExplode/issues/503

**Comment by gmy77** [comment]
Thanks 👍
