### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by arsinclair** [Tyrrrz/YoutubeDownloader#180]
**Any plans on supporting Linux?**

Because it uses WPF for UI, getting it on Linux even with Wine is problematic. I've succeeded only after I have built it as a self-contained app, but even then it is very laggy with Wine.

Mainly, I see two options: either we create a full-fledged Linux UI, or we abstract the main functionality into a CLI module to let other volunteers to make the UI.

I'm compelled to ask, as I am a little bit confused by the project status in the README: `warning: maintenance mode (bug fixes only).`
Does it mean that no new features, including Linux support, will ever be considered, and for this I have to make my own fork? Or it simply means that the repo owner can't promise the new features will be developed, but PRs are welcomed?

**Comment by Tyrrrz** [comment]
I don't use Linux, so I have no stake in this, but if I used Linux, i'd just use [youtube-dl](https://youtube-dl.org/) which I think does everything this app does too.

**Comment by arsinclair** [comment]
Thank you for the suggestion! Personally, I am not comfortable with _youtube-dl_ as it is written in Python: if anything breaks I have too little experience to be able to fix to it, or to contribute in general.

If there are contributions towards Linux compatibility here, will those PRs be accepted?

**Comment by Tyrrrz** [comment]
> If there are contributions towards Linux compatibility here, will those PRs be accepted?

Probably not, to be fair, as I don't want to take responsibility and maintain it.
If you want, you could write your own Linux version using [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode), which is the library YoutubeDownloader uses under the hood. Most of the hard work is handled by the library anyway.

**Comment by arsinclair** [comment]
> If you want, you could write your own Linux version using YoutubeExplode, which is the library YoutubeDownloader uses under the hood. Most of the hard work is handled by the library anyway.

Beautiful, I didn't know _YoutubeDownloader_ is just a wrapper. I'll be happy to spend a few hours/days building a new UI :) Thank you for a great library.

---

Btw, are you making any modifications to youtube stream blobs after you download them? In other words, what is the purpose of ffmepg - do you re-encode the video stream, or you just use it for bundling purposes?

**Comment by Tyrrrz** [comment]
> Btw, are you making any modifications to youtube stream blobs after you download them? In other words, what is the purpose of ffmepg - do you re-encode the video stream, or you just use it for bundling purposes?

The audio and video streams come in separately, so ffmpeg is used to multiplex them together. In some cases it's also used to convert into other formats.

**Comment by MesaBlack** [comment]
doesn't budge when opening with Wine

**Comment by arsinclair** [comment]
That would be a Wine problem, isn't it?

I don't know what framework this app uses for the UI purposes, but if it's WPF or UWP — you can't run those on Wine.

**Comment by Tyrrrz** [comment]
@Mrxx99 is in the process of migrating this from WPF to Avalonia, which would allow the app to be cross-platform: #361
