### ISSUE TITLE
Search seems to be broken

### ISSUE THREAD

**Issue by stacyh3** [Tyrrrz/YoutubeDownloader#181]
I've tried several time over the past few days to use search and get this result:

![image](https://user-images.githubusercontent.com/5132702/107729798-d69b7e00-6cbf-11eb-9f0d-64dc4f5bd961.png)

**Comment by Vilagamer999** [comment]
same, it seems that youtube has started preventing people from downloading videos...
pasting in a channel link or video link gives the same error:
![image](https://user-images.githubusercontent.com/30276916/107788151-5d983700-6d50-11eb-9314-6279f5b691e7.png)

**Comment by derech1e** [comment]
It is a known bug and a solution is already being sought.
See and help: Tyrrrz/YoutubeExplode#501
