### ISSUE TITLE
Playlist response is broken

### ISSUE THREAD

**Issue by Hunanbean** [Tyrrrz/YoutubeDownloader#182]
I have not waited hours, but i have waited some time. I keep getting the 'playlist response is broken' error message

Thank you

**Comment by Hunanbean** [comment]
Update: It has now been hours and the problem is still there so maybe YT changed something, I would not know.

Thank you

**Comment by derech1e** [comment]
Duplicate #181

**Comment by Combine900** [comment]
hope we get a fix soon :=)

**Comment by libaili-dev** [comment]
still no luck

**Comment by ghost** [comment]
08.03 - still not working 🦡

**Comment by relitrix-archive** [comment]
21.03 - still not working :l

**Comment by Technatro-uk** [comment]
Just ran into this issue as well.. hopefully a fix will be available soon.
Love this app!

![err_msg](https://user-images.githubusercontent.com/70385265/112541255-166b8000-8dab-11eb-9f4c-e796743e7b4f.png)

**Comment by ghost** [comment]
It works if you type in the url. Then you can check below whether you want to dl the video, audio, or whatever.
