### ISSUE TITLE
Unauthorized access error

### ISSUE THREAD

**Issue by Vilagamer999** [Tyrrrz/YoutubeDownloader#186]
The account I'm running the app on has full admin privileges, there shouldn't be any reason why it can't access the requested files...

![image](https://user-images.githubusercontent.com/30276916/109801973-7beea580-7c1f-11eb-9be5-76fd11b69d34.png)
![image](https://user-images.githubusercontent.com/30276916/109801619-01be2100-7c1f-11eb-83c8-d4211744fe0b.png)

**Comment by Tyrrrz** [comment]
Do you also run the application as administrator? To avoid this, just move the application into a directory that doesn't require elevated privileges to write to.

**Comment by Dark3n89** [comment]
> The account I'm running the app on has full admin privileges, there shouldn't be any reason why it can't access the requested files...
> 
> ![image](https://user-images.githubusercontent.com/30276916/109801973-7beea580-7c1f-11eb-9be5-76fd11b69d34.png)

Omg make source code compiled to one file.. only one problem what i spot.. FFPEG  must exists alone ...  right click on project name, publish and select all in one..   This will add net core too

**Comment by Vilagamer999** [comment]
> Do you also run the application as administrator? To avoid this, just move the application into a directory that doesn't require elevated privileges to write to.

I have moved the folder to the root directory and the problem doesn't happen anymore, I can even download videos without the playlist error people where having, thank you for helping :)

(p.s. you should include a footnote saying that its recommended to save the program in the "program files" directory)

**Comment by Tyrrrz** [comment]
> > Do you also run the application as administrator? To avoid this, just move the application into a directory that doesn't require elevated privileges to write to.
> 
> I have moved the folder to the root directory and the problem doesn't happen anymore, I can even download videos without the playlist error people where having, thank you for helping :)
> 
> (p.s. you should include a footnote saying that its recommended to save the program in the "program files" directory)

Good :+1:
