### ISSUE TITLE
Option to choose what characters to replace /, *, ", :, etc?

### ISSUE THREAD

**Issue by ghost** [Tyrrrz/YoutubeDownloader#188]
By default it replaces them with an underscore ("_") and I want to choose what to replace it with, either an empty character "" or a space " " when using $title as file name format.

**Comment by badijm** [comment]
Hi, I can pick this item. 

**UPD**: I could add the new textbox in setting view (also, length could be limited to 1 symbol)

**Comment by Tyrrrz** [comment]
Sorry for (very) late reply, but I decided to put the project into maintenance mode due to shifting priorities so it unfortunately won't be receiving new features.
