### ISSUE TITLE
Not downloading at full resolution

### ISSUE THREAD

**Issue by Hunanbean** [Tyrrrz/YoutubeDownloader#190]
While the playlist download is broken, i have been downloading videos manually one by one. The problem being, a proven 1080p video only downloads at 720p. This does not affect all videos, and has no discernable pattern. Here is one video that i have had problems with [https://www.youtube.com/watch?v=d6F72vjpESU](url)

closing and restarting everything has no effect.

Thank you

**Comment by Tyrrrz** [comment]
Yeah I've noticed that some videos don't provide their highest streams occasionally. I have a hunch that YouTube serves those higher rate streams from DASH, but I'm not 100% sure.

Related: https://github.com/Tyrrrz/YoutubeExplode/issues/159

**Comment by Hunanbean** [comment]
If you are looking for test videos, here is a video that should download at 1080, but downloads at 720 instead
[https://www.youtube.com/watch?v=wesKehVnhZY](url)

Thank you

**Comment by Hunanbean** [comment]
Here is another video that should download at 1080 but only gets 720 instead

`https://youtu.be/WtfLfYY_k2Y`

Thank you

**Comment by Jarol2K** [comment]
I can't download anything higher than 1080p. 4k and 8k videos are downloaded in 1080p :(

**Comment by YiYo97** [comment]
Currently the issue still persist 😢
