### ISSUE TITLE
The playlist make a error

### ISSUE THREAD

**Issue by Mageland29** [Tyrrrz/YoutubeDownloader#194]
![Capture](https://user-images.githubusercontent.com/31138970/112767882-68194200-9019-11eb-8696-2d02f3e6d5e9.JPG)

Hello, from some days, when i want download from every playlist he make an error and dont work for me

**Comment by CsknT** [comment]
Downloaded YouTubeDownloader code, removed the YouTubeExplode v5.1.9 and install v6.0.0-alpha via PMC. Rebuilt/Built the YouTubeDownloader and got the below compile time error on lines 74, 83, 92, and 100 in QueryService.cs.

Argument 3: cannot convert from 'System.Collections.Generic.IReadOnlyList<YoutubeExplode.Playlists.PlaylistVideo>' to 'System.Collections.Generic.IReadOnlyList<YoutubeExplode.Videos.Video>'

Failed code lines are: 
return new ExecutedQuery(query, playlist.Title, videos);
return new ExecutedQuery(query, $"Channel uploads: {channel.Title}", videos);
return new ExecutedQuery(query, $"Channel uploads: {channel.Title}", videos);
return new ExecutedQuery(query, $"Search: {query.Value}", videos);

Am I missing something or is this just a type conversion error/bug that needs to be fixed? Also, is there a quick and dirty workaround for this?
Thanks.
