### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by imarkone** [Tyrrrz/YoutubeDownloader#195]
Version 1.7.16, test url - "https://youtu.be/XTV13SDWB-g"
problem description: the video will not download and an error message will be displayed.

**Comment by kernrot** [comment]
![image](https://user-images.githubusercontent.com/3780878/113363219-9a47de00-9350-11eb-897e-889d8bada4e1.png)

**Comment by hyperpixel34** [comment]
I'm having the same error here.
I think YouTube changed something in the API

![image](https://user-images.githubusercontent.com/80213902/113397880-056bd180-939e-11eb-979c-adc2302f1d46.png)

**Comment by BobbyESP** [comment]
HI, this is a problem with the library that the program uses. Wait until the next version is launched and sorry.

**Comment by precary** [comment]
> HI, this is a problem with the library that the program uses. Wait until the next version is launched and sorry.

It downloads with YoutubeExplode 6.0.0-alpha2

**Comment by BobbyESP** [comment]
Yes, i made my own version of the program with that version. I needed to change some parts of the code, but no problem.

**Comment by Acromatic** [comment]
Working just fine for me
https://ibb.co/XyR3drb
I use the demo method, it's something you did.

**Comment by BobbyESP** [comment]
Maybe u are using this version of the library: YoutubeExplode 6.0.0-alpha2. With that version, the downloader works fine. i think im goingo to make a pull request lol

**Comment by Acromatic** [comment]
I'm using sharpgrabber... just sayin

**Comment by BobbyESP** [comment]
XDDD

**Comment by Teezton** [comment]
> Yes, i made my own version of the program with that version. I needed to change some parts of the code, but no problem.

Can you share your own version? Thank you.

**Comment by BobbyESP** [comment]
> > Yes, i made my own version of the program with that version. I needed to change some parts of the code, but no problem.
> 
> Can you share your own version? Thank you.

Well, it's in Spanish so let me do a version in English

**Comment by BobbyESP** [comment]
or i can share u the spanish version, but u will need to follow the UI or translate all.

**Comment by BobbyESP** [comment]
https://mega.nz/file/v4gSzKqS#hUPwxBJe5wk9PF2CP85HWPOCWMDAnGAcGTqjk0N187o

**Comment by Teezton** [comment]
> https://mega.nz/file/v4gSzKqS#hUPwxBJe5wk9PF2CP85HWPOCWMDAnGAcGTqjk0N187o

There is only 2 files inside, it's supposed to be like that?

**Comment by Teezton** [comment]
> or i can share u the spanish version, but u will need to follow the UI or translate all.

It's working, thanks a lot!

**Comment by BobbyESP** [comment]
Np men. You're welcome!

**Comment by somewhatuselessuser** [comment]
Thank you for the fix but for some reason the interface is now in Spanish?

**Comment by BobbyESP** [comment]
> Thank you for the fix but for some reason the interface is now in Spanish?

Because this version that i made is for getting update by me for my friends and we are Spanish.

**Comment by BobbyESP** [comment]
Give me 8 hours that i come back from school and i'll do the fix but in English.

**Comment by derech1e** [comment]
> Thank you for the fix but for some reason the interface is now in Spanish?

Checkout my PR and compile it yourself or download the Workflow Build files, it's in English.

**Comment by derech1e** [comment]
> > Thank you for the fix but for some reason the interface is now in Spanish?
> 
> Checkout my PR and compile it yourself or download the Workflow Build files, it's in English. 

https://github.com/Tyrrrz/YoutubeDownloader/actions/runs/730271308

The Link to the PR

**Comment by somewhatuselessuser** [comment]
Thank you, works perfectly and it's in English! 👍🏻
