### ISSUE TITLE
Video watch page is broken???

### ISSUE THREAD

**Issue by Internet-Smurf** [Tyrrrz/YoutubeDownloader#196]
Hi Guys,
thanks for developing - but since yesterday I cannot download any video any more - not even a video, I downloaded successfully two weaks ago!
What does it mean, "Video watch page is broken"?
Thanks, Holger.

**Comment by SoftwareMagicIT** [comment]
if you had read the other reports, you would have seen that the problem has already been reported a few days ago.
#195
