### ISSUE TITLE
"Up to 480p" is downloading 360p videos

### ISSUE THREAD

**Issue by christubuntu** [Tyrrrz/YoutubeDownloader#202]
### Version

1.8

### Details

If I select "Up to 480p" quality, the app downloads videos in 360p. This means it's impossible to download 480p videos.

### Steps to reproduce

1. Open app
2. Paste link 
3. select "up to 480p"
4. output is 360p, not 480p
5. I tried on this playlist https://www.youtube.com/playlist?list=PLrT1zCpaZbn4FBwPaX5lV67HccUXamh9L

**Comment by Tyrrrz** [comment]
Some videos may only have 480p in a given format, but not in the other.
