### ISSUE TITLE
$uploadDate option is missing

### ISSUE THREAD

**Issue by PrettyGoodMediaLLC** [Tyrrrz/YoutubeDownloader#204]
### Version

1.8

### Details

The option to include the $uploadDate in the file name was removed from this version.

Was that intentional?

If not, could you please put it back?

It still works on v1.7.16, so the field name is still functional in the YouTube api.

Other than that, thanks for the new version!

Charles

### Steps to reproduce

Just look under the Settings FileName template field; the option is no longer there, and no longer works if you had it there from before.

**Comment by Tyrrrz** [comment]
Yes, it was intentional. Unfortunately upload date can't be retrieved for search/playlist videos anymore.

**Comment by PrettyGoodMediaLLC** [comment]
But it still can for non-search/playlist videos.  So I guess I'll be using version  1.7.16 for downloading those videos so I can retrieve the upload date, and version 1.8.0 for downloading channels or playlists if I don't want to get the links one by one.

Seems to me that  the upload date could be incorporated into  the new version on a conditional basis, since the field is still there. But maybe that's too complicated.

Appreciate the new update and the work that went into it.  Maybe I'll have to take a look at the code to see if it's possible.

**Comment by Tyrrrz** [comment]
Will add this replacement token for single videos
