### ISSUE TITLE
Error - 404

### ISSUE THREAD

**Issue by Hunanbean** [Tyrrrz/YoutubeDownloader#209]
### Version

1.8.0

### Details

Copied link to a video by right clicking on video and copying url. 
![ScreenShot40](https://user-images.githubusercontent.com/52123900/118734738-ddbcb580-b7f3-11eb-9325-5a37f9d66832.jpg)

Thank you for your continued efforts
### Steps to reproduce

Just try to download a video. It is a video uploaded on april 30, 2021.

**Comment by Hunanbean** [comment]
This does not affect all videos. I do not know of a pattern.

**Comment by C2Pwn** [comment]
Able to reproduce error with the following URL: https://www.youtube.com/watch?v=d7riL6IXi5o

![image](https://user-images.githubusercontent.com/30189871/118752100-812bbb80-b830-11eb-8ffc-a2a954cff2a7.png)

**Comment by igormenin** [comment]
With all the links I tested to download gave this same error.

Last tested link https://www.youtube.com/watch?v=qc4kqZDX7zo

2021-05-19 09:40 BR - Tested now, and working with https://www.youtube.com/watch?v=o1MfxQXavHk

**Comment by Vilagamer999** [comment]
same error here, no idea what causes it although I'm pretty certain that the video or link doesn't matter... probably some sort of firewall or network error
![image](https://user-images.githubusercontent.com/30276916/119053306-2f1c9e80-b9c6-11eb-99a6-5922966396ae.png)

**Comment by cculianu** [comment]
Getting the same error here on all videos. Yeah I think YouTube changed their website again.  We need to wait for @Tyrrrz to reverse-engineering whatever they changed yet again...

**Comment by thisistorsten** [comment]
YouTube changed the get_video endpoint.

I have done a fix here. https://github.com/thisistorsten/YouTubeApiSharp

You need to add html5=1 to the url.

**Comment by cculianu** [comment]
Yep, can confirm it works now with latest that adds `&html5=1`. Thanks a lot for the quick turn around and in describing the fix.
