### ISSUE TITLE
App crashes for unavailable videos

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#21]
The app simply **CRASHES** by encountering a video that is **unavailable** on YouTube.  The URL is valid but the video might be removed by YouTube due to whatever reason.

Try this one for example:
https://www.youtube.com/watch?v=fGI2vCk6ykY

Need better error trapping.

![image](https://user-images.githubusercontent.com/22284653/58741117-b6d8ff00-83e3-11e9-80e9-8261c781e55f.png)

**Comment by xamarin-enthusiast** [comment]
@Tyrrrz  Is this bug crashing the same way as "App crashes for Video unavailable in Your Country" #24 ?

**Comment by Tyrrrz** [comment]
Yes it's the same problem
