### ISSUE TITLE
Error when trying to download

### ISSUE THREAD

**Issue by eren-erver** [Tyrrrz/YoutubeDownloader#211]
### Version

1.8.1

### Details

I am trying to download a video but it gives me this error

![image](https://user-images.githubusercontent.com/56906741/119446279-d71fc800-bd36-11eb-81f2-f277b7e908ac.png)

### Steps to reproduce

Try to download this video , https://www.youtube.com/watch?v=QJx4CABC7oE

**Comment by Tyrrrz** [comment]
Maybe related to https://github.com/Tyrrrz/YoutubeExplode/issues/542

**Comment by eren-erver** [comment]
New update fixed the issue , it was about the video being hdr .
