### ISSUE TITLE
Progress counter stops after Windows locks, but network activity continues

### ISSUE THREAD

**Issue by WmFjaCBCYWxs** [Tyrrrz/YoutubeDownloader#212]
### Version

v1.8.1

### Details

![Capture](https://user-images.githubusercontent.com/14607481/120249213-c512bd80-c23f-11eb-924c-db20e5a79a5a.PNG)
![Capture2](https://user-images.githubusercontent.com/14607481/120249215-c5ab5400-c23f-11eb-8ad4-266f0f3a255c.PNG)

My workstation locked, but didn't go to sleep, after about 20 minutes of inactivity. When I came back to the machine, I noticed that the progress counter hadn't moved for either of the 2 concurrent downloads for over an hour. I could hear my RAID storage writing to the disks about twice per second. Looking at Task Manager, I could see there is still network activity going on and that YoutubeDownloader was using all of it. I also periodically checked in on the tmp stream files, they continue to grow every so often.

I'm not sure if this is because Windows locked or if it was only a matter of time. I'm downloading a streamer's entire VOD playlist, hundreds of VODs at about 10 hours each, if this makes a difference.

### Steps to reproduce

Start the download for an entire VOD playlist.
Continue to work on the computer for a couple of hours.
Let your computer lock but not sleep.
Come back to the computer an hour or so later.

**Comment by WmFjaCBCYWxs** [comment]
After a while, network activity stops. The tmp stream doesn't move into the regular .mp4 file.

**Comment by Tyrrrz** [comment]
I don't think there's much we can do here. I've no idea how Windows handles process execution once you lock it and I also doubt that the process itself has any control over it.
