### ISSUE TITLE
Video download failed due to subtitles

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#218]
### Version

1.8.1

### Details

The download of this [video ](https://www.youtube.com/watch?v=O_ZFaiaTb1U) fails sometimes. I couldn't really figure it out why this is happening, but sometimes it works and sometimes not. I think in reference to the stack-trace, YoutubeExplode has a problem with fetching the subtitles. 

![image](https://user-images.githubusercontent.com/39240736/122440522-ed6b1d80-cf9c-11eb-8718-dbedc6557fb4.png)

### Steps to reproduce

Try to download that link: https://www.youtube.com/watch?v=O_ZFaiaTb1U

**Comment by Tyrrrz** [comment]
Related: https://github.com/Tyrrrz/YoutubeExplode/issues/564
