### ISSUE TITLE
Error 404 (Not Found)

### ISSUE THREAD

**Issue by Teezton** [Tyrrrz/YoutubeDownloader#219]
### Version

1.8.1

### Steps to reproduce

Try to download this [video](https://youtu.be/LGB6ZEjGm7Q).

![Image 001](https://user-images.githubusercontent.com/5905860/122555323-0eca1900-d032-11eb-9a16-5f7e38cd109f.png)

**Comment by Tyrrrz** [comment]
Related: https://github.com/Tyrrrz/YoutubeExplode/issues/565

**Comment by Teezton** [comment]
> Related: [Tyrrrz/YoutubeExplode#565](https://github.com/Tyrrrz/YoutubeExplode/issues/565)

There's any solution?

**Comment by Hunanbean** [comment]
Same error, same relation. Good luck, and thanks! Hard to imagine not having this projects function available.

**Comment by ryanpoh** [comment]
Same problem here. Unable to download any videos

For those, having this problem. A temporary alternative is to just search up the title and manually select it from the list, instead of using a direct link.

Hope there is a solution soon! Keep up the great work @Tyrrrz

**Comment by Teezton** [comment]
>**A temporary alternative is to just search up the title and manually select it from the list**, instead of using a direct link.

Thank you!
