### ISSUE TITLE
.NET Runtime (WindowsDesktop) v3.1.0 not installing 

### ISSUE THREAD

**Issue by GutHib1209** [Tyrrrz/YoutubeDownloader#220]
### Version

1.8.2

### Details

.Net Runtime v 3.1.0 is unable to install on my PC and YoutubeDownloader seems to only this run on this particular version. I have v5 installed but the program does not function with it. Is there some way to solve this issue?

### Steps to reproduce

1. Double click on "YoutubeDownloader.exe"
2. Prompt appears notifying user to install missing dependencies, in this case .NET Runtime (WindowsDesktop) v3.1.0 
3. Click "Install". .NET runtime is downloaded and the user is then prompted to install. 
4. YoutubeDownloader closes without installing the necessary dependency

**Comment by Tyrrrz** [comment]
No, v5 and v3.1 are not compatible, unfortunately.

Can you take a screenshot of your Add & Remove Programs with a list of installed runtimes? E.g. something like this:

![image](https://user-images.githubusercontent.com/1935960/123084677-4809dc80-d3d6-11eb-8f96-9d708f74f121.png)

**Comment by GutHib1209** [comment]
![image](https://user-images.githubusercontent.com/47790325/123114924-5b559000-d448-11eb-84da-e5b219e3bc50.png)

**Comment by Tyrrrz** [comment]
Looks like the runtime is installed. What happens when you run the application now?

**Comment by GutHib1209** [comment]
![image](https://user-images.githubusercontent.com/47790325/123149692-3114ca00-d46a-11eb-80aa-b89af4c3d9aa.png)

The .NET runtime will download, I'll be prompted to install and YoutubeDownloader will close by itself.

**Comment by Tyrrrz** [comment]
And if you click "Ignore", does it the app run?

**Comment by GutHib1209** [comment]
It doesn't.

**Comment by Tyrrrz** [comment]
Ok can you try going to the directory where you have `DiscordChatExporter.dll`, open command prompt and run:

```
dotnet DiscordChatExporter.dll
```

**Comment by GutHib1209** [comment]
Why `DiscordChatExporter.dll`?

**Comment by Tyrrrz** [comment]
Because that's the target assembly that gets executed when you run `DiscordChatExporter.exe`.

**Comment by Tyrrrz** [comment]
Sorry, for some reason I got confused and thought it was a different project 🤦🏻 
I meant `dotnet YoutubeDownloader.dll` of course.

**Comment by GutHib1209** [comment]
Someone suggested I get Microsoft Visual C + 2013 Redistributable and that solved it

**Comment by Tyrrrz** [comment]
Awesome
