### ISSUE TITLE
MP3 downloaded music missing background image 

### ISSUE THREAD

**Issue by EremitaDelle6Vie** [Tyrrrz/YoutubeDownloader#222]
### Version

1.8.2

### Details

When i download a song in MP3 version I don't get the image when I play it with VLC Media Player, there is only a black screen instead of the background (which is the thumbnail of the video I guess)
Is that bug or a problem with my media player or you intended to remove this feature in this version?

### Steps to reproduce

Download any video in MP3 version
Open the file with a media player

**Comment by KavyaKinjalk** [comment]
This only extracts audio from the video from YouTube, so there won't be any "tags" for the audio file, so this is not a bug, I suppose, as you are getting the audio only

**Comment by EremitaDelle6Vie** [comment]
@KavyaKinjalk yeah but with the previous version I could do it, so I don't know if they removed this feature

**Comment by M123-dev** [comment]
@EremitaDelle6Vie, I have the suffer from issue, I tried around with some older versions but it did not work there either, maybe its caused by some changes on the serverside.

**Comment by berkayyildi** [comment]
Same problem ++ Please add thumbnail images to mp3 files.

**Comment by M123-dev** [comment]
I can add on my previous comments. 

In the Audi entertainment system the thumbnails were shown, but not in Windows. 

Don't know if this is reproducible with the latest version because I used a older version in the process of getting it to work again. Just found out by accident

**Comment by Tyrrrz** [comment]
Duplicate of #210
