### ISSUE TITLE
.NET Runtime warning does not go away

### ISSUE THREAD

**Issue by 89z** [Tyrrrz/YoutubeDownloader#225]
### Version

1.8.2

### Details

I get a warning about .NET Runtime missing:

> ![Untitled](https://user-images.githubusercontent.com/73562167/125224319-052f7c00-e293-11eb-9005-53b1c1b256fb.png)

If I click Install, it appears to install the dependency and YouTubeDownloader launches as expected. However if I then close and open again, I am presented with the same warning.

**Comment by Tyrrrz** [comment]
Can you try running `dotnet --list-runtimes` and copy-paste here?

**Comment by 89z** [comment]
I dont have any program `dotnet` on my computer. Why would I need it?

**Comment by Tyrrrz** [comment]
It's installed by the runtime. If the runtime is installed correctly, it should be on your PATH which means you should be able to run the command I mentioned earlier.

**Comment by 89z** [comment]
No, I dont allow random programs to set my PATH, I set my own path with `Microsoft.PowerShell_profile.ps1`

**Comment by Tyrrrz** [comment]
Ok, in that case this is why it doesn't detect the .NET CLI. Just use the "Ignore" button to override it.

**Comment by 89z** [comment]
If the CLI is not required, then the warning shouldnt happen...
