### ISSUE TITLE
Error with 404 status code

### ISSUE THREAD

**Issue by 456yeah** [Tyrrrz/YoutubeDownloader#226]
### Version

lasted

### Details

bad request,404

### Steps to reproduce

![YoutubeDownloader v1 8 2 2021_7_22 12_03_34](https://user-images.githubusercontent.com/56508504/126588669-e0f2629b-34a5-4a9f-8389-f2c17660db51.png)

**Comment by Arrow2001** [comment]
Just a bug if you search the video within the app, it will download.

**Comment by UnboundGodz** [comment]
I can confirm @Arrow2001 suggestion gets around this bug.

**Comment by KYOUKA233** [comment]
I can search but failed to download

**Comment by git-h1gh** [comment]
> 
> 
> if you search the video within the app, it will download.

this does not enable 4K Download! The highest option using the search function offers only 1080p as maximum quality
