### ISSUE TITLE
Downloads slowing to a crawl

### ISSUE THREAD

**Issue by Hunanbean** [Tyrrrz/YoutubeDownloader#228]
### Version

1.8.3

### Details

Downloading a list of videos. Usually the last video being downloaded, not the order of, but the actual last, slows down to a crawl. This generally affected only one video on 1.8.2, but with 1.8.3 Many videos are crawling speed.

### Steps to reproduce

Download a playlist of videos
WHile downloaded, watch the speed.
Notice that the speed gets very slow after a short time.

**Comment by Tyrrrz** [comment]
Does it depend on the format?

**Comment by Hunanbean** [comment]
Do you mean the source end, or on my end? On my end, i just let it do its thing and download mp4/1080

**Comment by Tyrrrz** [comment]
I mean, does it also slow down if you download it as webm instead of mp4?

**Comment by Hunanbean** [comment]
webm has not shown up as an option - only mp4, mp3 and ogg.
For an example, on this playlist, [https://www.youtube.com/playlist?list=PLTztLWdi2XEE4-MQX2BQ3i6VICXCmd42W](url) the files AGR PRO Animation Debug Widget, and the file AGR PRO 2.1.1 Update, Power IK, Updated''' slow down, but the rest do fine.

Thank you

**Comment by Hunanbean** [comment]
So it is known, stopping and restarting the download does not fix it. but stopping, closing the progam, deleting the partial, restarting the progam and starting the download again seems to fix the problem.

Thank you

**Comment by Ramys** [comment]
I have this same problem, and sometimes the application closes without finishing the download.
There is no option to download the mix made by youtuber.
Exe: https://www.youtube.com/watch?v=MG_cjByleYI&list=RDMG_cjByleYI

**Comment by Tyrrrz** [comment]
Most likely related to https://github.com/Tyrrrz/YoutubeExplode/issues/573
