### ISSUE TITLE
Download pending for seconds and then failed

### ISSUE THREAD

**Issue by lucinda2214** [Tyrrrz/YoutubeDownloader#229]
### Version

ver 1.8.3

### Details

So basically I typed in the link to the playlist and I got this
![0](https://user-images.githubusercontent.com/89339815/130610482-7c7b83c8-584a-4af7-94a2-cbcd3ae0a162.png)
Then I clicked download, chose the saved path and this happened
![1](https://user-images.githubusercontent.com/89339815/130610698-d2127541-df73-47dd-a8c6-dfa033519181.png)
it was pending for a few seconds and then all failed

### Steps to reproduce

Type in the link and Enter
Click the Download button

**Comment by Jonny11bonk** [comment]
The issue is still there.
