### ISSUE TITLE
1 hour 4K video fails to download

### ISSUE THREAD

**Issue by a-habib** [Tyrrrz/YoutubeDownloader#236]
### Version

1.8.3

### Details

https://www.youtube.com/watch?v=7szcXCT-Oqw

This video always fails to download. When it fails I don't know at what percentage and the tmp file is deleted so I don't know how much was downloaded(the original file is still there but is 0 bytes). The status just shows failure. Based on checking it visually it fails around 30% (1.5GB) but I don't know for sure without a log. I have tried multiple times (also deleting the incomplete file) but it always fails.

I have not had issues with shorter content, or with 1080p content.

### Steps to reproduce

Enter https://www.youtube.com/watch?v=7szcXCT-Oqw
Select 2160p mp4 format
Wait until it fails.

**Comment by Tyrrrz** [comment]
Can you hover your cursor over "Failure" and see what the tooltip says?

**Comment by a-habib** [comment]
Ok I got a stack trace. Around ~23% there is a 403.

![image](https://user-images.githubusercontent.com/17305856/141238788-fe12cabc-2f0e-4066-a285-c9071fbfa39d.png)

**Comment by BlackMightyRavenDark** [comment]
My downloader is working fine with this video.

**Comment by a-habib** [comment]
> My downloader is working fine with this video.

What settings did you use for the video resolution and format.

Also it is not just this video. Any video that is approximately an hour long 4K will result in 403 error when ~ 20% has downloaded.
