### ISSUE TITLE
UI fails to scale

### ISSUE THREAD

**Issue by adamralph** [Tyrrrz/YoutubeDownloader#238]
### Version

1.8.3

### Details

My desktop is scaled to 200%, but the app UI doesn't respect this and stays at 100%

![image](https://user-images.githubusercontent.com/677704/140741636-b36f2e00-2eb3-41c0-9b6c-9068df93104c.png)

### Steps to reproduce

- Scale your desktop to something other than 100%
- Run the app

**Comment by Tyrrrz** [comment]
@adamralph do you have different DPI settings on one of your monitor? I'm wondering why this is happening, considering WPF apps should be system DPI-aware by default according to the [docs](https://github.com/microsoft/WPF-Samples/blob/main/PerMonitorDPI/readme.md).

**Comment by adamralph** [comment]
@Tyrrrz no, all monitors have the same setting (200%).

It seems to be really wonky. For example, if I set my main monitor to 100%, it opens with the same (absolute) size as shown in the screenshot above. If I then drag it to a 200% monitor, it expands up to the size it should be. Then if I close the app, and set the main monitor back to 200%, it again opens with the same absolute size as shown in the screenshot above. 😕

**Comment by adamralph** [comment]
I think I may have spotted a pattern—the app seems to react to _changes_ in scaling, e.g. dragging to a different monitor, or changing the scaling of the active monitor. But it always seems to start up with 100% scaling.

**Comment by adamralph** [comment]
BTW - I don't know if this is relevant, but it only started to happen recently. I last used the app a few weeks ago and it was fine.

**Comment by Tyrrrz** [comment]
Hm, interesting 🤔 

> BTW - I don't know if this is relevant, but it only started to happen recently. I last used the app a few weeks ago and it was fine.

This might mean that it's caused by the relatively recent addition of a bootstrapper. I think this might fix it in the future, if that's the case: https://github.com/Tyrrrz/DotnetRuntimeBootstrapper/issues/12
