### ISSUE TITLE
Download speed low

### ISSUE THREAD

**Issue by paulnsk** [Tyrrrz/YoutubeDownloader#240]
### Version

1.8.3

### Details

This app used to be able to download videos at 10 MB/sec which is the limit of my internet connection. Occasionally, some videos would start downloading at a much slower rate (~50KB/sec) but after a few re-tries the speed would rise to normal.
Recently though, this changed. I can no longer reach high speed no matter how many times I retry.
In browser, however, speed is still high, I can observe this when pressing a right arrow key which causes to jump 5 seconds forward - this happens instantly and can be seen as a peak on the speed graph.
There must be something in HTTP headers. I tried copying useragent from my Chrome and recompiling the sources - no luck.

### Steps to reproduce

- Download any long video
- Observe the speed

**Comment by Combine900** [comment]
Same problem.. @Tyrrrz any fix yet?

**Comment by DarshZero** [comment]
Same Problrm.

**Comment by DarshZero** [comment]
Same Problem.
