### ISSUE TITLE
Program labeled as virus

### ISSUE THREAD

**Issue by ghost** [Tyrrrz/YoutubeDownloader#242]
### Version

1.8.4

### Details

MaxSecure, Cyclance and SentinelOne detect this program as malicious, including "Trojan.Malware.300983.susgen". I don't think it's meant to be detected this way.

### Steps to reproduce

- Download the latest release
- Drag and drop on virustotal

**Comment by Tyrrrz** [comment]
Can you report false positive on it? Other than that I don't know what to suggest. Antiviruses seem to be suspicious for some reason of the bootstrapper which downloads and installs the runtime.

**Comment by MysticAx0lotl** [comment]
Building from source, for some reason, resolves most false-positives.
