### ISSUE TITLE
System.ApplicationExtension when trying to start

### ISSUE THREAD

**Issue by astronom-v-cube** [Tyrrrz/YoutubeDownloader#246]
### Version

1.8.4

### Details

![image](https://user-images.githubusercontent.com/63924364/150675793-b727fea5-18f2-4289-9d91-f6155b080d1a.png)

When trying to run on Windows 11, I get this error
The version, for example, 1.7.15 runs without problems

### Steps to reproduce

- download zip
- install .NET Runtime (WindowsDesktop) v3.1.0
- try to run the program

**Comment by Tyrrrz** [comment]
Can you uninstall all existing .NET Runtimes and let the app install them itself?

**Comment by astronom-v-cube** [comment]
Oh, I'm sorry for my long silence. Can I make a deletion using this utility: [https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows](url)
Or does it need to be done in some other way?

**Comment by Tyrrrz** [comment]
That should work. Also just uninstalling them from control panel should be fine too.

**Comment by astronom-v-cube** [comment]
I am interested because in the list of applications .NET is missing
![image](https://user-images.githubusercontent.com/63924364/154761664-a6925bfe-3479-4b35-a478-f7e918a29938.png)

**Comment by Tyrrrz** [comment]
What happens if you open the command shell and run `dotnet --info`?

**Comment by astronom-v-cube** [comment]
![image](https://user-images.githubusercontent.com/63924364/154857148-12f74218-2a3d-4a3c-b01e-c084a453c71c.png)

**Comment by Tyrrrz** [comment]
Looks fine to me 🤷🏻‍♂️
