### ISSUE TITLE
Not working over a PAC system proxy

### ISSUE THREAD

**Issue by PIndividual** [Tyrrrz/YoutubeDownloader#247]
### Version

1.8.4

### Details

![image](https://user-images.githubusercontent.com/62368342/152368164-7893779f-6e43-4dba-9f17-d894ee2587d6.png)

### Steps to reproduce

Anything that are pasted in the search bar will result in such an error.is

**Comment by Tyrrrz** [comment]
If the proxy is configured on your system correctly (i.e., in Internet Options), it should work. Otherwise, I'm afraid this is outside of this project's domain.
