### ISSUE TITLE
Not a issue it's discussion

### ISSUE THREAD

**Issue by mrnams** [Tyrrrz/YoutubeDownloader#25]
Hello,
Sorry for filling issue.
Actually i could not find community forum to add discussion,so reporting issue, but it's not issue at all.
Come to point.
Is there any existing desktop application to manage youtube channel like "tubebuddy" or "vidiq"?
If not can we start developing such application?

**Comment by Tyrrrz** [comment]
Hi,
I'm not sure whether there are apps like this, but I don't have any plans to develop one because I don't have time and I don't have any interest in making any more YouTube apps :)

**Comment by mrnams** [comment]
No issue thanks

**Comment by mrnams** [comment]
@Tyrrrz I found you have developed one more application 
https://www.tubebuddy.com
I strongly feel you can easily make application similar to https://www.tubebuddy.com, which has huge demand today.
