### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by brd-mikek** [Tyrrrz/YoutubeDownloader#251]
### Version

d3f0571c19ada5113a1add8313190ecb6ab1eab

### Details

After clean clone of the repo I cannot build it :(

### Steps to reproduce

Simple clone repo, then either build with VS 2022 or with `dotnet build`

![image](https://user-images.githubusercontent.com/77951000/152627752-1efb6ea6-ff58-4b89-ab3a-bad1b463bd27.png)

**Comment by Tyrrrz** [comment]
Remove these lines from the csproj for now:

https://github.com/Tyrrrz/YoutubeDownloader/blob/2d3f0571c19ada5113a1add8313190ecb6ab1eab/YoutubeDownloader/YoutubeDownloader.csproj#L31-L34

I will fix it later
