### ISSUE TITLE
HDR format missing from dropdown

### ISSUE THREAD

**Issue by a-habib** [Tyrrrz/YoutubeDownloader#261]
### Version

1.9.2

### Details

HDR format seems to be missing for some videos (verified video is HDR on LG HDR tv BT2020 colorspace). e.g.

https://www.youtube.com/watch?v=-qwuY0f6xuA

However HDR is available for this video

https://www.youtube.com/watch?v=eTiL_ohrWxQ

### Steps to reproduce

Download a HDR video e.g.

https://www.youtube.com/watch?v=-qwuY0f6xuA

HDR video format is not available from the dropdown.

**Comment by a-habib** [comment]
![image](https://user-images.githubusercontent.com/17305856/171017702-833f4a35-84e1-4d99-a7cd-3f9e3b76a6af.png)

The HDR format only appears under 480p and lower resolution but is missing from higher resolutions.

**Comment by mhombach** [comment]
@Tyrrrz Hey, any news on this issue? :)

**Comment by Tyrrrz** [comment]
@mhombach no, unfortunately. It seems that YouTube doesn't provide these additional formats to the Android client, which we use for reverse-engineering.

**Comment by Tyrrrz** [comment]
Nevermind, I checked again and the issue is something completely different than what I remembered. I will get it fixed this week.

**Comment by Tyrrrz** [comment]
Currently blocked by #322, so it might take longer because that issue is difficult to solve.
