### ISSUE TITLE
Video will not download to remote folder

### ISSUE THREAD

**Issue by xknat** [Tyrrrz/YoutubeDownloader#265]
### Version

1.9.2

### Details

![image](https://user-images.githubusercontent.com/10220139/170497643-3101a759-7439-412f-b5ae-852a5f9c5017.png)

### Steps to reproduce

Use SMB on a remote drive to download a video

**Comment by Tyrrrz** [comment]
Are you sure that it's because of the network folder? Does it work for that same video if you download it somewhere else?

**Comment by xknat** [comment]
> Are you sure that it's because of the network folder? Does it work for that same video if you download it somewhere else?

yes

**Comment by xknat** [comment]
using smb share

**Comment by Tyrrrz** [comment]
I can't see any error message in FFmpeg's output. It's possible FFmpeg just doesn't support it?

**Comment by xknat** [comment]
I am guessing this was because my documents folder was on a share as well
this has resolved a lot of game related issues as well (by putting documents on C:\).

tested on release and works fine for me
Will create new ticket if this happens again
