### ISSUE TITLE
Downloading in reverse order?

### ISSUE THREAD

**Issue by thewayur** [Tyrrrz/YoutubeDownloader#269]
### Version

ver 1.9.2

### Details

if i paste channel, the whole list is downloaded in reverse order?

lets suppose the playlist is in correct order E01, E02, E03.....E99

then it will download E99 first, why?

also while download it does not show any title or thumbnail :(

![image](https://user-images.githubusercontent.com/2944767/173224168-97c9e41d-77d3-4309-aa1d-e00e455a6f84.png)

### Steps to reproduce

while downloading channel

**Comment by ScottsplaysSus** [comment]
Not familiar with this, you can try to enable 'Inject media tags' option in the settings. If it doesn't work, try going to the destination folder (the folder that you downloaded these media to) and click the 'sort by date modified' button and see if it is still not in the correct order. If everything doesn't work, try reinstalling the app. 

I'm not the developer btw :)

**Comment by Tyrrrz** [comment]
The download order is not deterministic, it's on "first come first serve" basis in regards to worker threads.
As for not showing thumbnail and title – it might be related to #238.
