### ISSUE TITLE
App crashes when I put the app folder on C:\Program Files

### ISSUE THREAD

**Issue by ghost** [Tyrrrz/YoutubeDownloader#27]
With new version 1.4, I put the app folder to C:\Program Files and run the app, when I press X to close it, the app crashes.
![2019-06-14 09_41_07-Error occured](https://user-images.githubusercontent.com/51132011/59488869-5ccb4580-8e89-11e9-9059-ae766d37cea6.png)

**Comment by Tyrrrz** [comment]
The application needs write access to its immediate directory because it's a portable distribution. You need to either put it somewhere where there are no write restrictions or launch the app as administrator.

**Comment by ghost** [comment]
I see, thanks a lot.

**Comment by Tyrrrz** [comment]
You're welcome
