### ISSUE TITLE
No persistence of downloaded files  

### ISSUE THREAD

**Issue by puffy-puffy** [Tyrrrz/YoutubeDownloader#271]
### Version

ver 1.9.2

### Details

I don't know if this is an "international feature" but the app does not persist the details about the previously downloaded videos 

### Steps to reproduce

Step 1: Download a video 
![YoutubeDownloader_pBcn6tPiSL](https://user-images.githubusercontent.com/107198078/173550129-38e01853-2b95-4e80-9a7c-cee9e7198406.png)

Step 2: Close and Reopen the app, the "details" about the downloaded video is not visible
![YoutubeDownloader_gbCoYxKevl](https://user-images.githubusercontent.com/107198078/173550322-f4b83e47-3953-4453-896a-64adc968a07f.png)

**Comment by Tyrrrz** [comment]
Yep, it's intentional.
