### ISSUE TITLE
Cannot download all videos

### ISSUE THREAD

**Issue by ghost** [Tyrrrz/YoutubeDownloader#272]
### Version

1.9.2

### Details

hi, if i want to download all videos from some youtube channel, i cannot do this, because not loading all videos from channel, only part of videos.
on some channel appear 20 videos to download, on another channel 14 videos, etc

### Steps to reproduce

Open app
try to download from here https://www.youtube.com/user/toplesofficial/videos
i able to download only 20 videos

**Comment by Tyrrrz** [comment]
Duplicate of #273
