### ISSUE TITLE
Problem with downloading videos from channels with custom URLs

### ISSUE THREAD

**Issue by mahadinur** [Tyrrrz/YoutubeDownloader#273]
### Version

v1.9.2

### Details

I was querying a channel URL but instead of getting all videos from said channel, I got videos from different channels.

![image](https://user-images.githubusercontent.com/77368058/176326298-058cd9b0-ed29-4c18-8c8d-ee9b739387bc.png)
![image](https://user-images.githubusercontent.com/77368058/176326355-d95ec0d3-335f-48b6-9a71-ef32b5c0b382.png)

However, this does not happen when querying a channel URL which doesn't have a custom URL.

![image](https://user-images.githubusercontent.com/77368058/176326474-b4d30bc2-08bd-4a01-897a-110ba9aaf8ac.png)
![image](https://user-images.githubusercontent.com/77368058/176326639-b0bbdde8-884b-4c1a-9189-a57ee0913714.png)

A way I found around this is by creating a playlist and adding all videos from said channel into it.  This takes a lot of time.

I want to archive the videos of entire channels and fixing this would be helpful.

### Steps to reproduce

1. Find any custom channel URL (ex. https://www.youtube.com/user/PewDiePie)
2. Query it

**Comment by Tyrrrz** [comment]
I think the issue is that links like [youtube.com/user/PewDiePie](https://www.youtube.com/user/PewDiePie) etc are currently not parsed and treated as search queries

**Comment by Tyrrrz** [comment]
Fixed

**Comment by mahadinur** [comment]
Thank you!  Much appreciated!
