### ISSUE TITLE
Отрубить долбанное окно с сообщением об укр/рос войне

### ISSUE THREAD

**Issue by W1nKille3r** [Tyrrrz/YoutubeDownloader#274]
### Version

1.9.3

### Details

Я хз почему функции по этому поводу нету. Потому что я как пользователь который качает кучу контента из ютуба это начинает капать на нервы. Нету кнопки или галки чтобы отключить это надоевшее окно. (Юзаю потому что метадата автоматом закидывается при скачке условных mp3).

### Steps to reproduce

1

**Comment by kxrn0** [comment]
juts use yt-dlp
