### ISSUE TITLE
I do not agree with the terms of use

### ISSUE THREAD

**Issue by KoLeS2109** [Tyrrrz/YoutubeDownloader#276]
### Version

1.93

### Details

I was reading terms of use, i expected to read terms of use, but russophobia happened

### Steps to reproduce

- Go to this page https://github.com/Tyrrrz/YoutubeDownloader
- read terms of use
- profit!

**Comment by derech1e** [comment]
Dude, he is from Ukraine. What should he prove? He live there?!
