### ISSUE TITLE
Application crashes without any error message

### ISSUE THREAD

**Issue by mrnams** [Tyrrrz/YoutubeDownloader#28]
Enter below playlist
https://www.youtube.com/playlist?list=PLuP1A7qpEl3cdMSqBPWITlWBPaRCoylgo
It will list 66 videos,now select mp3 option and hit ok,immediately  application crashes without any error, I have not looked log as it can easily reproduced.

**Comment by Tyrrrz** [comment]
Which version are you using?

**Comment by mrnams** [comment]
latest version1.4

**Comment by Tyrrrz** [comment]
Doesn't crash for me

**Comment by mrnams** [comment]
@Tyrrrz  I could not reproduce issue when i used exe build at your side, but when I complied source code with latest visual studio then it crashed.
