### ISSUE TITLE
I want to download never gonna give you up or all video error

### ISSUE THREAD

**Issue by karstenlee10** [Tyrrrz/YoutubeDownloader#287]
### Version

1.9.4

### Details

i want download but show this error 
![YoutubeDownloader v1 9 4 26_9_2022 21_57_22](https://user-images.githubusercontent.com/91263511/192296517-b253c23a-510d-4dce-91d5-e3194c09a1c6.png)

### Steps to reproduce

- Open YoutubeDownloader
- Download Never gonna give you up
- HAVE ERROR

**Comment by Tyrrrz** [comment]
You don't have access to that path
