### ISSUE TITLE
Could not find signature decipherer function name

### ISSUE THREAD

**Issue by justseeseesee** [Tyrrrz/YoutubeDownloader#29]
Could not find signature decipherer function name，what should i do ? My OS is win10

**Comment by Tyrrrz** [comment]
Yeah this is how things go with YouTube downloader apps, YouTube breaks something every now and then.
Sit tight and wait for https://github.com/Tyrrrz/YoutubeExplode/issues/252

**Comment by mrnams** [comment]
@Tyrrrz 
Video link
https://www.youtube.com/watch?v=BBAyRBTfsOU
Error:
![2019-06-22 00_18_37-YoutubeDownloader](https://user-images.githubusercontent.com/31761152/59944826-79680e80-9483-11e9-8a52-3fb089ad5a3f.png)

**Comment by mrnams** [comment]
@Tyrrrz Fortunately 4K video downloader work well all time for all video, You can learn how they manage it.
