### ISSUE TITLE
Downloaded video has subtitle option, but actually there is no subtitle

### ISSUE THREAD

**Issue by thebluedarker** [Tyrrrz/YoutubeDownloader#300]
### Version

1.9.5

### Details

I can select subtitle options in the player, but each option has no subtitle.

### Steps to reproduce

-step1，download a video
-step2，play the video(A subtitle option is selected, but there is no subtitle)

**Comment by Tyrrrz** [comment]
What do you mean? Can you elaborate with screenshots?

**Comment by thebluedarker** [comment]
![图片](https://user-images.githubusercontent.com/49782161/205472803-2cfce50e-7e1b-4f53-8ea4-2e8c756a4772.png)There is a subtitle option, but each subtitle does not work.
![图片](https://user-images.githubusercontent.com/49782161/205472878-167d154d-2b3e-4ce0-935d-3eed71ec0f14.png)
This is the screenshot of the subtitle that works normally.This video was not downloaded from YouTube.

**Comment by Tyrrrz** [comment]
What video did you download?

**Comment by thebluedarker** [comment]
https://www.youtube.com/watch?v=oPKGhlnYmrY

**Comment by Tyrrrz** [comment]
Seems to work for me in VLC Media Player

![image](https://user-images.githubusercontent.com/1935960/205491453-b9171cf2-a91c-494b-a9a1-22f51c5e2a39.png)
