### ISSUE TITLE
A video cannot download because its wrong subtitles

### ISSUE THREAD

**Issue by thebluedarker** [Tyrrrz/YoutubeDownloader#301]
### Version

1.9.5

### Details

The video url is https://www.youtube.com/watch?v=iT8NATexxmw.There is something wrong with chinese[simplified] of the video on YouTube.The video cant be downloaded by YoutubeDownloader,but it can be downloaded by youtube-dl.
![图片](https://user-images.githubusercontent.com/49782161/205817710-b526f9e8-817c-48d9-a277-2162a0239ae3.png)
![图片](https://user-images.githubusercontent.com/49782161/205818159-d362ec75-3eb5-41f5-9d9b-391bc7231a2e.png)

### Steps to reproduce

just download https://www.youtube.com/watch?v=iT8NATexxmw

**Comment by Tyrrrz** [comment]
~~Can you hover over `Failed` and take a screenshot of the error message?~~

Nevermind, I was able to reproduce:

![image](https://user-images.githubusercontent.com/1935960/205981357-3ce6a952-d4a3-4378-8f85-28f05065bf56.png)

It looks like the track is completely empty:

https://www.youtube.com/api/timedtext?v=iT8NATexxmw&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1670373289&sparams=ip,ipbits,expire,v,caps,xoaf&signature=14E81420576504D95CB99197017B55D0A070E622.7BCA02983CB17C18C6052517A68BE34E40CC4778&key=yt8&lang=zh-Hans&fmt=srv3

![image](https://user-images.githubusercontent.com/1935960/205982314-d537a064-2b13-48a6-9811-67b6d4ac88ee.png)
