### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by MoritzHinterleitner** [Tyrrrz/YoutubeDownloader#309]
### Version

newest

### Details

https://www.virustotal.com/gui/file/6803a3fdbc4a173c98c92bbf720c9571d4786e1d2f4a03c61036a6ebf550d8d6?nocache=1
virustotal shows 6 av saying its malicious? why?

### Steps to reproduce

https://www.virustotal.com/gui/file/6803a3fdbc4a173c98c92bbf720c9571d4786e1d2f4a03c61036a6ebf550d8d6?nocache=1

**Comment by Tyrrrz** [comment]
I don't know. Use at your own risk.
