### ISSUE TITLE
The download speed is far less than the network speed

### ISSUE THREAD

**Issue by xiele88787** [Tyrrrz/YoutubeDownloader#315]
### Version

1.9.8

### Details

 Using a tool like idm, you can download at about 100MB per second, but my program is only 40MB at the fastest download speed. Is there a problem with multi-threaded downloads?  I'm using a solid state drive, so it's unlikely that I have an io issue 

### Steps to reproduce

1

**Comment by Tyrrrz** [comment]
There's a limit to how fast the streams are served by YouTube
