### ISSUE TITLE
Startup error after upgrading to v1.9.9

### ISSUE THREAD

**Issue by Corgile** [Tyrrrz/YoutubeDownloader#321]
### Version

1.9.9

### Details

I was clicking youtube downloader icon and error spawns (showed in picture )

![image](https://user-images.githubusercontent.com/48396880/221802841-615de81a-dfd6-4640-87ed-0109fbb531d7.png)

after closing this dialog, the main app exited.

### Steps to reproduce

1. upgrade to 1.9.9
2. with windows 11 Pro 22H2 build: 22621.1265
3. click icon to start this app
4. errors happened.

**Comment by Tyrrrz** [comment]
Can you try deleting your settings file (`Settings.dat`) and try again? Your settings will be reset but the app should be able to run.

**Comment by Corgile** [comment]
after I downloaded some previous version zip files, it still doesn't work. double clicking the exe file only results in a spinning mouse cursor but no window or relevant processes can be found on the system. I try to find some logs through windows event viewer but still no luck. Probably not an issue of [YoutubeDownloader](https://github.com/Tyrrrz/YoutubeDownloader).
