### ISSUE TITLE
Very slow download speed

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeDownloader#322]
### Version

v1.9.9

### Details

Download speeds are much slower than before.

Related issue: https://github.com/Tyrrrz/YoutubeExplode/issues/688

### Steps to reproduce

Download any video

**Comment by devilbear** [comment]
Having the same issue myself. I'm lucky to get as "high" a speed as 5Mbps... on my 60Mbps connection, and usually it dips down to 2Mbps for most of a video download then 600kbps for the final 3% or so (which multiplies the time taken to download by a significant amount).

Of interest, I tried a website called Cobalt Video Downloader which does much the same thing as this program and it's showing the same results. So this might be something on YouTube's end...?
