### ISSUE TITLE
Automatic update to 1.9.10 not functioning as expected

### ISSUE THREAD

**Issue by ToxiClay** [Tyrrrz/YoutubeDownloader#323]
### Version

1.9.9

### Details

Youtube Downloader 1.9.9 fails to automatically update to 1.9.10, which would be expected.

This isn't a *huge* issue, seeing as I can simply manually download 1.9.10, but I figured you'd want to know about it.

https://user-images.githubusercontent.com/13796683/222306249-878d24af-b835-4fb6-b4d0-da70da39b54f.mp4

### Steps to reproduce

YoutubeDownloader 1.9.9 is located in my Downloads directory. When launching 1.9.9, it states that it's downloading 1.9.10, as expected, and informs the user that it will be installed on exit.

Exiting the program, either with the Install Now button or manually Xing it, does not cause the program to update.

Running the program as administrator does not fix the issue.

**Comment by ToxiClay** [comment]
Apparently it was working and Windows was just being a butt. Goddammit.

**Comment by Tyrrrz** [comment]
That looks weird but I'm glad you figured it out
