### ISSUE TITLE
Restricted region is broken

### ISSUE THREAD

**Issue by shemm11** [Tyrrrz/YoutubeDownloader#328]
### Version

1.9.10

### Details

Kazakhstan is not Russia. Disable setting "FUCK RUSSIA" for my county. 
![dsadsa](https://user-images.githubusercontent.com/44135180/229122331-2ba2a481-9784-4710-a652-293598554f17.png)

### Steps to reproduce

Living is Kazakhstan

**Comment by Tyrrrz** [comment]
The restriction check is based on your computer settings, which means you have russia configured as your system region or location.
