### ISSUE TITLE
Can't make subtitle files independent?

### ISSUE THREAD

**Issue by martjay** [Tyrrrz/YoutubeDownloader#329]
### Version

lasted

### Details

I downloaded the video and found that the subtitles were all embedded, and I couldn't manipulate the subtitle file.
Or is there an option to download subtitles, I can choose to download subtitles?

### Steps to reproduce

1

**Comment by Tyrrrz** [comment]
No, subtitles are always embedded. You can extract them using VLC or some other tool if you want.

**Comment by HolisticDeveloper** [comment]
In case anyone else is looking to do this... I found a solution from [Reddit](https://www.reddit.com/r/VLC/comments/v1vei4/comment/iaph1q2/) for extracting the subtitles:
`ffmpeg -i 'input.mp4' -map 0:s:0 'output.srt'`
