### ISSUE TITLE
Unable to download this video

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#33]
This video plays fine on YouTube but fails in YoutubeDownloader.

https://www.youtube.com/watch?v=fDQZLyUU2D4

Any idea why?

![image](https://user-images.githubusercontent.com/22284653/60396769-889a2c80-9b13-11e9-8e0b-2fd016ab2fb3.png)

**Comment by Tyrrrz** [comment]
The video is unavailable in my country but 404 probably means something else.
No idea, need to investigate

**Comment by xamarin-enthusiast** [comment]
Tested in v1.5.4.  Same issue.

**Comment by Tyrrrz** [comment]
Unfortunately I can't reproduce this because the video is not available in my country

**Comment by xamarin-enthusiast** [comment]
Also unable to download this video:
https://www.youtube.com/watch?v=I-tb9LIQEd0

![image](https://user-images.githubusercontent.com/22284653/61792487-df311880-adea-11e9-9899-050be1df0c42.png)

Any idea why?

**Comment by Tyrrrz** [comment]
Looks like that video doesn't have adaptive streams. That's weird. I've created a matching issue in the other repo.
