### ISSUE TITLE
Some videos are super slow to download

### ISSUE THREAD

**Issue by ScottsplaysSus** [Tyrrrz/YoutubeDownloader#332]
### Version

1.9.10

### Details

Hey there! I noticed an issue during my recent downloads of files. Some videos are very slow to download recently, especially videos that are longer (>40 minutes), while other videos are quick to download. I think it is not related to my WiFi speed as other videos can download at a stable speed and are quick, but every once in a while some longer videos are downloading like 1% every 30 seconds. Other videos are downloading at 30~40% every 30 second, which is weird as this issue has not happened before (at least for me). Is there any fix to this problem? 

For example, this video downloaded very slowly: https://www.youtube.com/watch?v=PRKqvZKbY2k

Thanks for this awesome application by the way :) 

### Steps to reproduce

- Step 1 open the app (1.9.10)
- Step 2 download this link https://www.youtube.com/watch?v=PRKqvZKbY2k or some other videos that are long (>40 minutes) (I'm using MP3 format, not sure about MP4 and other file formats) 
- Step 3 video will download at an extremely slow speed (around 1% every 30 seconds compared to the usual 30%~40% every 30 seconds)

**Comment by Tyrrrz** [comment]
Related: https://github.com/Tyrrrz/YoutubeExplode/issues/706

The current workaround is just to cancel and retry the video until it's fast again. Might require waiting a few minutes in-between retries.

**Comment by ScottsplaysSus** [comment]
Alright, thanks for the help :)

**Comment by ScottsplaysSus** [comment]
Hey there, the issue is fixed in 1.9.11 release, thanks for the help!
