### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden)

### ISSUE THREAD

**Issue by tryittogether52** [Tyrrrz/YoutubeDownloader#333]
### Version

1.9.10

### Details

Hello Oleksii Holub,

I am using your application https://github.com/Tyrrrz/YoutubeDownloader.
It works great.

But recently, I got the following errors:
`Response status code does not indicate success: 403 (Forbidden)` when download long video:

https://www.youtube.com/watch?v=Oa2IpTyjbxQ
https://www.youtube.com/watch?v=6XM7BgoQdhU
https://www.youtube.com/watch?v=yvL9JRFsAQw
https://www.youtube.com/watch?v=33FbdGicc84
https://www.youtube.com/watch?v=orFNbppc6_0

![image](https://user-images.githubusercontent.com/119604817/234851109-0745afa8-9df3-4ca0-8f7e-966b65677c05.png)

Could you help me to fix it?'

### Steps to reproduce

- Step 1: copy the following URLs:
https://www.youtube.com/watch?v=Oa2IpTyjbxQ
https://www.youtube.com/watch?v=6XM7BgoQdhU
https://www.youtube.com/watch?v=yvL9JRFsAQw
https://www.youtube.com/watch?v=33FbdGicc84
https://www.youtube.com/watch?v=orFNbppc6_0

- Step 2: paste to the text box and press Enter
- Step 3: Select all by press Ctrl + A
- Step 4: click to Download button

**Comment by Tyrrrz** [comment]
Looks like YouTube may have changed something. Would take a while to figure out. For now, see if retrying a couple of times (or later) helps work around the issue.

**Comment by zzzzsssl** [comment]
i have the same problem...

**Comment by ScottsplaysSus** [comment]
I have the same issue too, hope it can be fixed soon :)

**Comment by manfroid** [comment]
Got the same problem, Tyrrrz. I am using the latest and greatest V1.9.10 (via auto update) Even tried with a new download of the stable binaries from GitHub. Error only occurs a while after download has started, thus downloading the same file in different formats succeeds if the file can be downloaded fast enough for the error emission not to kick in.

I tried a video of about 1 hr playing time with the format from 1080p down to 480p which all failed. The 360p resolution, however, and the mp4 audio file worked just fine. Seems like YT now detects applications which keep downloading (on the same connection?? via HTTP?!) for an extended period of time (beyond simple buffering?) HTTP status 403 indication varies for me between 10 and 20 seconds into the download. Videos that take no more than 20 seconds to grab typically succeed.

Hope this information helps.

On this opportunity I'd also like to say thank you for this great utility which helps me pursue my learning efforts off-line with no distraction. I only watch educational content downloaded using your application.

And finally I'd like to send my best wishes and regards to you and all the people in the Україна. You have my sympathy and at least some monetary support, folks 🤝

**Comment by Tyrrrz** [comment]
Thank you, that helps investigate it further. I can't give any promises though as I don't have a lot of free time now.

**Comment by luopan007** [comment]
have same question

**Comment by Tyrrrz** [comment]
@manfroid are you downloading one video at a time or multiple in parallel?

**Comment by manfroid** [comment]
@Tyrrrz Great to see you're digging into the topic, man -- Дякую 👍 The first time the problem occurred I was actually downloading a playlist. But the case I described above (video of 1+ hr playing time) I only did one single video at a time. I also tried several resolutions/formats of this video one by one with the results as described. If you want me to try anything else, please let me know. I'm wholeheartedly ready to assist.

**Comment by manfroid** [comment]
Got the automatic update to V1.9.11 -- works like a charm! Thanks so much!


 

Gesendet: Dienstag, 02. Mai 2023 um 18:12 Uhr
Von: "Oleksii Holub" ***@***.***>
An: "Tyrrrz/YoutubeDownloader" ***@***.***>
Cc: "manfroid" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [Tyrrrz/YoutubeDownloader] Response status code does not indicate success: 403 (Forbidden) (Issue #333)


 

Closed #333 as completed via eb072b0.

**Comment by Tyrrrz** [comment]
I found a workaround for the problem, we'll see how long it'll last.

**Comment by tryittogether52** [comment]
Thank you very much.

I found that there is no issue with https://github.com/yt-dlp/yt-dlp.
Not sure how it works, but it's good for your reference.

Vào 23:24, T.4, 3 Th5, 2023 Oleksii Holub ***@***.***> đã
viết:

**Comment by Tyrrrz** [comment]
> Thank you very much. I found that there is no issue with [yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp). Not sure how it works, but it's good for your reference.

They're using a slightly different approach from what I do in [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode), but thanks anyway.
