### ISSUE TITLE
Error after pasting a Youtube link

### ISSUE THREAD

**Issue by Silver347** [Tyrrrz/YoutubeDownloader#337]
### Version

YoutubeDownloader v1.9.11

### Details

After pasting my Youtube link,this error pops up:

<img width="448" alt="Screenshot_1" src="https://github.com/Tyrrrz/YoutubeDownloader/assets/52638612/b3a9f1c0-0369-4699-99de-2161a55c11d9">

### Steps to reproduce

1. Copying a link from Youtube
2. Pasting it in the search bar
3. Error message pops out

**Comment by Tyrrrz** [comment]
Does it happen consistently for you? I can't reproduce it.

Does the CI build work for you? https://github.com/Tyrrrz/YoutubeDownloader/actions/runs/5042850066

**Comment by jack2002jack** [comment]
it may be youtube's api changed

**Comment by Tyrrrz** [comment]
> it may be youtube's api changed

That doesn't sound like it should be related to that, based on the exception message.
