### ISSUE TITLE
Add 4 columns to summary view

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#34]
Please add the following 4 important columns to the summary view:

- Uploader
- Length
- File Size
- Upload Date

![image](https://user-images.githubusercontent.com/22284653/60397885-dddc3b00-9b1f-11e9-83cd-0e9e961d63de.png)

**Comment by xamarin-enthusiast** [comment]
Hope this feature will be implemented soon.  Very useful!  :-)

**Comment by xamarin-enthusiast** [comment]
Would LOVE to see this feature implemented.  👍

**Comment by Tyrrrz** [comment]
File size can't be accurately displayed until the streams are fully muxed.
As for Uploader/UploadDate, what's your use case that you need them visible on the main screen?
