### ISSUE TITLE
Subtitles saving incorrectly

### ISSUE THREAD

**Issue by ShrootBuck** [Tyrrrz/YoutubeDownloader#342]
### Version

1.19.12

### Details

Simply save a video. Instead of the embedded subtitles saving correctly, they're in a weird moving format. A line is printed, but then the next subtitle screen shows the lines moving downward. Harder to explain, so I've attached a video.

I'm wondering if this is a bug in YoutubeDownloader or just something with Youtube itself. Or, is this an intended feature?

https://github.com/Tyrrrz/YoutubeDownloader/assets/70227235/febac708-32b7-428b-a11d-74bdfb754dd8

### Steps to reproduce

- Save any video (auto-generated subtitles count, so the video doesn't need it's own to reproduce)

**Comment by Tyrrrz** [comment]
I'm not sure what you're talking about? The subtitles are rendered by your player. They're stored inside the video in a text format, with just timing information. The player is what decides how they "move" on your screen.

**Comment by ShrootBuck** [comment]
It appears to be a YouTube issue with the auto generated subtitles.

**Comment by Tyrrrz** [comment]
Can you share a video ID/URL so I can check?

**Comment by ShrootBuck** [comment]
The ID was `8hly31xKli0`. Subtitles on VLC player worked perfectly in the past, so I'm convinced it's not a player issue. I think it's just a timing relapse, where the second set of timing information (second "sentence") is being combined with the first or something.

**Comment by Tyrrrz** [comment]
Here's how the subtitles are encoded for that section of the video:

```srt
13622
04:13:23,600 --> 04:13:27,760
time we're not doing anything to narrow

13623
04:13:25,750 --> 04:13:27,760



13624
04:13:25,760 --> 04:13:29,279
down the search each time we have to

13625
04:13:27,750 --> 04:13:29,279



13626
04:13:27,760 --> 04:13:30,960
search all of it

13627
04:13:29,269 --> 04:13:30,960



13628
04:13:29,279 --> 04:13:32,800
if you're searching a big list or

13629
04:13:30,950 --> 04:13:32,800



13630
04:13:30,960 --> 04:13:34,880
searching it repeatedly this amount of

13631
04:13:32,790 --> 04:13:34,880



13632
04:13:32,800 --> 04:13:36,960
time can slow your whole lap down to the

13633
04:13:34,870 --> 04:13:36,960

```

As you can see, the captions do overlap in timing. For example:
- `time we're not doing anything to narrow` **ends** at 04:13:27
- `down the search each time we have to` **starts** at 04:13:25, which is 2 seconds earlier

That being said, however, I noticed that the video actually has two subtitle tracks, where one of them doesn't have overlapping captions. I don't know how exactly that happened, so I will have to look at it. But it does seem that the overlap is produced on YouTube's side.

**Comment by ShrootBuck** [comment]
Alright, thanks for clarifying. Sorry for the irrelevant issue.

**Comment by Tyrrrz** [comment]
> Alright, thanks for clarifying. Sorry for the irrelevant issue.

It should be better now
