### ISSUE TITLE
Downloading large videos freezes at end

### ISSUE THREAD

**Issue by ShrootBuck** [Tyrrrz/YoutubeDownloader#343]
### Version

1.19.12

### Details

The specific video is [here](https://youtu.be/8jLOx1hD3_o). The video, downloading at max quality, is fine for the most part. Then, at 95.3%, it gets stuck indefinitely. Other large videos get stuck at the same exact percentage. In task manager, it shows the process taking up memory (obviously), but no CPU usage or any other network tasks. I left it like that for a few hours, and it stayed stuck. Any ideas what this may be caused by?

### Steps to reproduce

see above

**Comment by Tyrrrz** [comment]
Is it consistently reproducible for you on that video? Which format did you choose to download?

**Comment by ShrootBuck** [comment]
It is reproducible, very consistently. I chose highest quality.

**Comment by Tyrrrz** [comment]
It does appear to finish eventually, just takes a while and does not report progress for whatever reason. I'll look into it.

**Comment by ShrootBuck** [comment]
How long does it take you for the video to finish? It's been an hour for me and I'm not seeing any change.

**Comment by Tyrrrz** [comment]
I think around 40 minutes. You should be able to see progress if you look at the output file and keep refreshing to see it grow in size.

**Comment by ShrootBuck** [comment]
That's weird. It's been 6 hours and nothing's happening.

**Comment by Tyrrrz** [comment]
> That's weird. It's been 6 hours and nothing's happening.

Do you not see the output file changing in size at all? There should be a couple of `.tmp` files next to it too.

**Comment by ShrootBuck** [comment]
I see the temp files, but the output doesn't change all.

**Comment by ShrootBuck** [comment]
Fixed in [d925d87](https://github.com/Tyrrrz/CliWrap/commit/d925d87b6a0c5191a2459752550ad0ccc0ff2593).

**Comment by Tyrrrz** [comment]
Should work now
