### ISSUE TITLE
Launching fails with a big JSON error message

### ISSUE THREAD

**Issue by WangleLine** [Tyrrrz/YoutubeDownloader#344]
### Version

1.9.12

### Details

I was just trying to launch the program as usual, then this error greeted me. Trying again did not work, restarting my computer did not work. I'll try re-installing soon.

![Discord_TDeX0ytHAC](https://github.com/Tyrrrz/YoutubeDownloader/assets/34343336/367e2ad1-f9b2-4b7e-8ff8-0d4eb84e63ff)

### Steps to reproduce

- Launch the program
- It crashes

**Comment by Tyrrrz** [comment]
Hmm. That's weird. Can you copy-paste the contents of your `Settings.dat` file? Should be in the same directory as `YoutubeDownloader.exe`.

**Comment by WangleLine** [comment]
Oh, it was completely empty. That's wild.

Deleting the file fixed the issue

**Comment by Tyrrrz** [comment]
Did the application crash at some point? I wonder why would it end up writing an empty file

**Comment by WangleLine** [comment]
I can't remember the program crashing at any point, no

**Comment by Tyrrrz** [comment]
@WangleLine did you install YTD using `scoop` by any chance?

Related: https://github.com/Tyrrrz/DiscordChatExporter/issues/1050

**Comment by WangleLine** [comment]
Oh hey, sorry - I don't use scoop or YTD at all.
The issue appeared again today, seemingly out of nowhere. Had to delete settings again.

![chrome_v5g44PkATq](https://github.com/Tyrrrz/YoutubeDownloader/assets/34343336/ff6f6284-0ec5-4c84-a8e0-6363a47372c2)

**Comment by WangleLine** [comment]
oh right, I'll also update to the latest release now.

**Comment by Tyrrrz** [comment]
Yes, please update. If it doesn't help, delete `Settings.dat` file and try again.
