### ISSUE TITLE
Nothing loads

### ISSUE THREAD

**Issue by LaganYT** [Tyrrrz/YoutubeDownloader#345]
### Version

1.9.12

### Details

I tried downloading a video or even searching a query and nothing came up.

### Steps to reproduce

type anything in the box
get stuck at the loading screen

**Comment by Tyrrrz** [comment]
Works for me

**Comment by K3rhos** [comment]
Same problem here, it was working perfectly like 1-2 months ago, now it's completely broken, nothing is loading.

**Comment by K3rhos** [comment]
Update: It's seem that sometimes it load, but it takes years when before 1.10 they were no issues, that's strange.
