### ISSUE TITLE
Windows Title Bar should show Download % progress

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#35]
During a download, it would be good if the Windows title bar can show the overall _Download % progress_ of all pending downloads.  

![image](https://user-images.githubusercontent.com/22284653/60398356-f3079880-9b24-11e9-8da0-4faa639c5f40.png)

If that math is too difficult to calculate, at least change the Windows title bar to say **(Pending...)** or **(Downloading...)** while YoutubeDownload is downloading.

![image](https://user-images.githubusercontent.com/22284653/60398377-25b19100-9b25-11e9-87aa-df58823e72f1.png)

Show the regular Windows title bar when YoutubeDownloader is just sitting idle.

Right now it's difficult to tell if YoutubeDownloader is sitting idle or if it is downloading something.  This small modification will help.

**Comment by Tyrrrz** [comment]
There's already a progress bar right below the search query and in the task bar

**Comment by xamarin-enthusiast** [comment]
@Tyrrrz You are right.  Just noticed it after you pointed it out.  Must be because the UI treatment is so light color and subtle which makes it easy to miss.

**Comment by Tyrrrz** [comment]
I like it this way. :)
I don't think it's wise to add another form of progress, because there are already three (actual progress bar, taskbar progress bar, individual download progress).
