### ISSUE TITLE
Problem downloading "video" folder even though videos exist

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#36]
Found a bug.  Try putting this in the "URL or search query" text box:

https://www.youtube.com/channel/UCxJrxUKsNvxa5PkYrOLwXzg/videos

Even though videos exist, YoutubeDownloader will say "Nothing found":

![image](https://user-images.githubusercontent.com/22284653/60402234-cbcbbe00-9b5a-11e9-8275-684ba4e0c2f3.png)

**Comment by Tyrrrz** [comment]
Related to https://github.com/Tyrrrz/YoutubeExplode/issues/259
