### ISSUE TITLE
Can't download any video at all

### ISSUE THREAD

**Issue by Oceanboy1330** [Tyrrrz/YoutubeDownloader#364]
### Version

v1.10.2

### Platform

Windows 11

### Steps to reproduce

Video or playlist URL: Basically Any Video.

Steps:
Basically the Only Step is to Try to Download a Video by Pasting a Link

### Details

Expected Behavior: It Works.
Actual Behavior: 401 Error (Unauthorized) for First Time, "Video watch page is broken. Please try again in a few minutes." for the Rest.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Works just fine for me

**Comment by ScottsplaysSus** [comment]
Unfortunately, I have encountered this issue too, same app version, but I'm using Windows 10. 

Edit: Found the fix, just log out of your account (if it's authenticated in the app), works fine for me now. :)
