### ISSUE TITLE
Auto-update error

### ISSUE THREAD

**Issue by Tsaitou7361** [Tyrrrz/YoutubeDownloader#366]
### Version

v1.9.13

### Platform

Windows 11

### Steps to reproduce

When I open application
it shows need update, and I clicked INSTALL
window was exit, and nothing
I have open it again, still 1.9.13
This problem took many places, just like 1.9.9, 1.9.10
What Problem is it?

### Details

for i in range(1, n)
 [System] : Downloading update to v1.10.2
 [System] : Update has been downloaded and will be installed when you exit  INSTALL NOW
 me : INSTALL NOW
 [System] : Window has been broke
 me : open it again
 i +=1

For under checkboxes
3. I have made sure that this bug is reproducible on the least version (that I have) of the application.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [ ] I have made sure that that this bug is reproducible on the latest version of the application
- [x] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
There were some issues in earlier versions, see #323, #353. It should be fixed now.
