### ISSUE TITLE
Setting for default download path

### ISSUE THREAD

**Issue by abyssox** [Tyrrrz/YoutubeDownloader#37]
A setting for "standard download path" would be very useful so you don't have to choose one each time.

**Comment by Tyrrrz** [comment]
Your last download path is preserved in the dialog

**Comment by abyssox** [comment]
Yes i noticed that, but it would be realy nice to reduce this one click and store the default path in settings.dat

**Comment by abyssox** [comment]
Fixed it on my own. Anyway great App, love it!!! Keep on the good work!

**Comment by Tyrrrz** [comment]
Thank you :)
