### ISSUE TITLE
I'm not in Russia or Belarus

### ISSUE THREAD

**Issue by Callemul** [Tyrrrz/YoutubeDownloader#370]
### Version

new, not opened your app

### Platform

Windows 10

### Steps to reproduce

Install and run

### Details

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/18458401/6ff3778d-2c15-40ac-accf-a2c0dbce1561)

App not oppened with Error Box.
I`m in Ukraine, Vinnitsa

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Read the second paragraph of the error message

**Comment by kovalensky** [comment]
"_Open-source_"
