### ISSUE TITLE
Program isn't launching at all

### ISSUE THREAD

**Issue by Obimydudee** [Tyrrrz/YoutubeDownloader#372]
### Version

v1.10.2

### Platform

Windows 10

### Steps to reproduce

starting it

### Details

launch exe 'YoutubeDownloader.exe'
nothing happens

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Try uninstalling all instances of .NET (Core) installations on your system and try again
