### ISSUE TITLE
Program is inoperable when trying to download large lists of videos

### ISSUE THREAD

**Issue by GamerzHell9137** [Tyrrrz/YoutubeDownloader#376]
### Version

v1.10.3

### Platform

Windows 10

### Steps to reproduce

If you try downloading a whole youtube channel the app gets impossible to operate. Channel doesn't matter and the settings are default. The number of videos on the channel might be the key factor as to why the program gets inoperable.

### Details

1. Copy link of any youtube channel
2. Paste it in the program
3. Long wait and program starts to chug and freeze

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by DanielOberlechner** [comment]
I downloaded my private music youtube playlist with more than 500 videos and it worked quite fine. A few videos failed to download but then I clicked the retry button and everything worked.

Are 500+ videos not enough to trigger this problem?

**Comment by Tyrrrz** [comment]
The move to Avalonia should have made this better
