### ISSUE TITLE
File name template $num adds [ ] in the number of any playlists

### ISSUE THREAD

**Issue by OMSmolina** [Tyrrrz/YoutubeDownloader#377]
### Version

1.10.3

### Platform

Windows 10

### Steps to reproduce

With any youtube playlist $num adds [ ]

For example: https://www.youtube.com/playlist?list=PL3eBqMwkHPomNoHnm9cjf5CUrvYAapB3m

**Application Settings:**

File name template: $num - $title

or

File name template: S01E$num - $title

### Details

 **Expected:** 
- 01 - Title Name of the video
or
- S01E01 - Title Name of the video

**Actual:**
- [1] - Title Name of the video
or
- S01E[01] - Title Name of the video

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
This is not really a bug as it's just how `$num` has historically come to be. The file name templates are pretty inflexible, overall.

**Comment by OMSmolina** [comment]
Oh, I didn't know, I just found this program and when I saw that the parameter was there, it said $num for the number, I expected a number not [00]. I will have to do a fork or look for another program since Jellyfin or Plex do not detect the number with [ ] sorry for the inconvenience, thank you.

**Comment by Tyrrrz** [comment]
Yeah, you're right. I don't remember exactly why square brackets are there, but I remember it was intended. It's not the best design, admittedly.

I think you should be able to strip the brackets in all files using a simple shell script or using some batch rename tool.

**Comment by OMSmolina** [comment]
The issue was that I didn't want to use other tools. After looking at several tools, in the end I decided to compile a version without the square brackets since with these it was no longer a number, it took 2 seconds and it works perfectly with all the combinations.

Whether you decide to change it or not, you can close the issue, thank you.

**Comment by Tyrrrz** [comment]
I added an undocumented `$numc` token that doesn't include `[]`
