### ISSUE TITLE
"Channel page is broken. Please try again later" error message

### ISSUE THREAD

**Issue by ghost** [Tyrrrz/YoutubeDownloader#378]
### Version

1.10.3

### Platform

Windows 10 Pro

### Steps to reproduce

Open YoutubeDownloader.exe, paste https://www.youtube.com/@HoracioFrazao/videos url in it, "Channel page is broken. Please try again later" error message show up.

Ins't a specific issue with this channel, as i'm unable to download anything with this program as same error messages show up.

### Details

Expected behavior is to work and download videos, actual behavior is described in 'steps to reproduce' section here.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Works now

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/1935960/a66242a4-f8e5-4808-ab47-dd88239b784c)
