### ISSUE TITLE
Always stuck at 100%

### ISSUE THREAD

**Issue by wangzhenjjcn** [Tyrrrz/YoutubeDownloader#384]
### Version

v1.10.4

### Platform

windows 11

### Steps to reproduce

https://www.youtube.com/@yuansir

### Details

download a list over 100 videos
sometime always have more than 5 videos shows 100% for a long time 
it keeps 100%

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project

**Comment by wangzhenjjcn** [comment]
when download this https://www.youtube.com/@12KScenicRelaxation
it canceled a lot liniks without click cancele btn 
and i have loged in with my account

**Comment by Tyrrrz** [comment]
If you open task manager, do you see any `ffmpeg.exe` processes?

**Comment by Tyrrrz** [comment]
Could not reproduce the issue

**Comment by wangzhenjjcn** [comment]
@Tyrrrz  when stuck shows,cannot find ffmpeg.exe 
but I click cancel on items shows 100% it changes to done then start a new parallel in list 
so maybe the completion judgment mechanism of the program  can be diversified

**Comment by wangzhenjjcn** [comment]
@Tyrrrz maybe can adding a timeout detection when reaching 100% or 99% progress to prevent stuttering and temporarily increasing the number of download threads that exceed the threshold

**Comment by wangzhenjjcn** [comment]
heres my gif screen record at 3fps
![GIF 2023-11-9 18-24-39](https://github.com/Tyrrrz/YoutubeDownloader/assets/1842578/f1372a4e-9246-46ba-8dcf-940a00c86ee5)

**Comment by Tyrrrz** [comment]
I think it just takes a while to complete the conversion process. The progress is reported directly from FFmpeg, unfortunately it can't get more precise than this.

**Comment by wangzhenjjcn** [comment]
@Tyrrrz i dont know it is  monitor the pid of ffmpeg.exe  or catch a  return from the processor

maybe it has a err on cal whether it is completed or not, I think

and with the number of tasks increases, it is more common to encounter this stuck state, which will continue to be stuck at 100% of the maximum number of tasks without human intervention
it realy shows on my computer
