### ISSUE TITLE
Long video will error during download

### ISSUE THREAD

**Issue by LUQ94** [Tyrrrz/YoutubeDownloader#385]
### Version

v1.10.4

### Platform

Windows 10

### Steps to reproduce

long video will download error, won't success.
It seems that the problem started today.

### Details

long video will download error, won't success.
It seems that the problem started today.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [x] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Can you give an example?

**Comment by LUQ94** [comment]
This video for example.
https://youtu.be/JGlaRUvul3c?si=tCznfxpdwOVHUCR4

It will run to almost 99% than it will show fail.

**Comment by Tyrrrz** [comment]
Can't reproduce

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/1935960/55321180-8438-44cd-a192-17662b603fde)
