### ISSUE TITLE
[MacOS] Build failed

### ISSUE THREAD

**Issue by antwal** [Tyrrrz/YoutubeDownloader#4]
[build log here](https://pastebin.com/fS8kQJyw)
[custom DownloadFfmpeg.ps1](https://pastebin.com/wcUDh7rh)

**Comment by Tyrrrz** [comment]
I think mono doesn't support WPF, so this is why it can't build it

**Comment by pheonixfirewingz** [comment]
get a stable window and Linux version first then try porting it to mac
