### ISSUE TITLE
Value parameter cannot be 0

### ISSUE THREAD

**Issue by Diva-333** [Tyrrrz/YoutubeDownloader#40]
When I try to download any video, either from URL and through search it fails with no error code, the only thing that program says is that value parameter cannot be equal to zero.
![image](https://user-images.githubusercontent.com/52682533/60850468-cc65f380-a1ef-11e9-9e1f-e82b9a0ae912.png)

**Comment by HamzaAnis** [comment]
For more details. [#266](https://github.com/Tyrrrz/YoutubeExplode/issues/266)

It will be fixed soon.

**Comment by romainvandooren** [comment]
I have this issue too

**Comment by Tyrrrz** [comment]
Duplicate of #41
Even though this issue was raised earlier, that other one has slightly better description.
