### ISSUE TITLE
The subtitles are not automatically enabled

### ISSUE THREAD

**Issue by lizzyliu666** [Tyrrrz/YoutubeDownloader#400]
### Version

v1.10.8

### Platform

Windows 11

### Steps to reproduce

any playlist

### Details

The subtitles in the videos are not automatically enabled and there is not an option in the setting. Is there a way to export the subtitles as a single file or in jason/csv?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project

**Comment by Tyrrrz** [comment]
The subtitles are embedded inside the video file. You can enable them in your player of choice.
