### ISSUE TITLE
Livestream VOD download fails with "Video 'xxxxx' does not contain any playable streams"

### ISSUE THREAD

**Issue by LukeTheVirus** [Tyrrrz/YoutubeDownloader#404]
### Version

1.10.8

### Platform

Windows 10

### Steps to reproduce

Trying to download my favourits musician's vods does not work for a while after the stream has ended.
1. https://youtu.be/-EuXplJPP6Q (May start working at some point but doesn't work now 11:00-UTC)
  - Other recent (max few hours old) vods should reproduce the error if the provided link stops working
3. Entering URL into downloader and hitting "process query" ends in the error `Video '-EuXplJPP6Q' does not contain any playable streams.`

### Details

I expect to be able to download live stream vods directly after the live stream has ended ~or even while the live stream is running~ (seems to be limitation of youtubeexplode).
My best guess to what's happening is that youtube is reprocessing the vod after stream ends and only after this the client is able to download the "video".
Reason why i can't wait for the link to start working is because the artist deletes their vods shortly after.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by LukeTheVirus** [comment]
While debuging myself found it it's an issue with youtubeexplode.

**Comment by Tyrrrz** [comment]
Active live streams cannot be downloaded. As for live streams that have concluded, it might take some time (up to 24 hours) for the static streams to become available.
