### ISSUE TITLE
Specific videos failed at around 95% complete due to ffmpeg conversion failure

### ISSUE THREAD

**Issue by JerryC436** [Tyrrrz/YoutubeDownloader#405]
### Version

v1.10.8

### Platform

Windows 11

### Videos URL
https://www.youtube.com/watch?v=NtQkz0aRDe8
https://www.youtube.com/watch?v=F1Hq8eVOMHs
https://www.youtube.com/watch?v=dSu5sXmsur4
https://www.youtube.com/watch?v=LEENEFaVUzU

### Expected behaviour
All videos download successfully.

### Actual behaviour
The four videos above all failed at around 95% complete when using ffmpeg command-line tool.
In the error log, it shows this warning message: "Application provided duration: _{a huge number around 4294910296000}_ is invalid" and then the ffmpeg video conversion failed.
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/116790678/7ca3dba7-64ae-41ee-8089-03616462af72)
This same issue was reported recently with a different video which now seems to download fine: https://github.com/Tyrrrz/YoutubeDownloader/issues/397

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
> This same issue was reported recently with a different video which now seems to download fine: #397

This issue is not related to that one. #397 is about invalid subtitle language codes, while this one seems to be about mismatching track durations.

**Comment by Tyrrrz** [comment]
Crazy time debugging this, but it looks like the Chinese subtitles are broken. The last entry includes text content that is valid SRT, but contains incorrect length.

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/1935960/63058771-4102-4125-81db-3392f907f05b)

I assume these subtitles were added to the YouTube video by importing from an SRT file but something went wrong in the process.
