### ISSUE TITLE
Specific YouTube Short plays fine, will not download

### ISSUE THREAD

**Issue by QINGCHARLES** [Tyrrrz/YoutubeDownloader#406]
### Version

v1.10.9

### Platform

Windows 11

### Steps to reproduce

https://www.youtube.com/watch?v=JQgKhZZyBYg

### Details

Saw this comment on Hacker News and confirm that it won't download:

https://news.ycombinator.com/item?id=38831357

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by QINGCHARLES** [comment]
Update: this only fails if the MP4 copy is selected, the WEBM version works.

**Comment by Tyrrrz** [comment]
It appears the issue is that the best mp4 stream for this video returns 404 for some reason.
