### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [Tyrrrz/YoutubeDownloader#407]
### Version

1.10.10

### Platform

Win 7

### Steps to reproduce

  vv

### Details

Does this work with Win 7?

Thanks

### Checklist

- [ ] I have looked through existing issues to make sure that this bug has not been reported before
- [ ] I have provided a descriptive title for this issue
- [ ] I have made sure that this bug is reproducible on the latest version of the application
- [ ] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
I don't know, try it
