### ISSUE TITLE
Unable to download this video - Value cannot be null

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#41]
Try this sample video:
https://www.youtube.com/watch?v=PpG0z-npFIY

It will return this error:
![image](https://user-images.githubusercontent.com/22284653/60887908-77dc6b80-a223-11e9-99af-f6fb6a491da2.png)

**Comment by xamarin-enthusiast** [comment]
Is this related to [this bug](https://github.com/Tyrrrz/YoutubeExplode/issues/266)?

**Comment by mrnams** [comment]
@xamarin-enthusiast  @Tyrrrz  @floatas I am getting same error even in release 1.5.3
