### ISSUE TITLE
Video download fails due to invalid cookies

### ISSUE THREAD

**Issue by 12345xinkai** [Tyrrrz/YoutubeDownloader#411]
### Version

1.10.10

### Platform

win10

### Steps to reproduce

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/121651626/eff907ea-838e-457b-ae71-7070768311ac)
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/121651626/591b5bc7-6507-4d2c-a0d2-6d5ec37db002)
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/121651626/805d42b0-f735-4029-a47c-49461cd848dd)

### Details

An error occurred when parsing the cookie header for uri

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [ ] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by crolyss** [comment]
Came to report same issue, any video tried doesn't work. However I had never tried logging in to use the app, I logged in to my Google account, and could download again. I didn't want to log in to use it, so I think this is still valid issue to raise.

<img width="407" alt="Screenshot 2024-01-18 214551" src="https://github.com/Tyrrrz/YoutubeDownloader/assets/45496883/25dc2822-e5e7-4413-ae66-73f49ace03c9">

<img width="443" alt="Screenshot 2024-01-18 215047" src="https://github.com/Tyrrrz/YoutubeDownloader/assets/45496883/2a5804fb-088c-4afb-9068-ecc58cf7a5d1">

<img width="437" alt="Screenshot 2024-01-18 215126" src="https://github.com/Tyrrrz/YoutubeDownloader/assets/45496883/a5fa0e66-0ddb-4150-872d-e17c07c4a4e7">

**Comment by WeihanLi** [comment]
The same problem met
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/7604648/f4ee46bf-cc29-4ed8-9d74-97db87086b27)

**Comment by WeihanLi** [comment]
seemed related to https://github.com/Tyrrrz/YoutubeExplode/issues/762
