### ISSUE TITLE
Still can't download, shows error

### ISSUE THREAD

**Issue by LUQ94** [Tyrrrz/YoutubeDownloader#413]
### Version

V 1.10.11

### Platform

Windows 10

### Steps to reproduce

Still can't download, show Error. "V1.10.11"

![Error2](https://github.com/Tyrrrz/YoutubeDownloader/assets/111036955/c9135bd7-dbfb-41a6-8d73-f9e6a810dd23)

### Details

![Error1](https://github.com/Tyrrrz/YoutubeDownloader/assets/111036955/507ffd67-c246-4d2b-b31e-12855abf6bf7)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by MHasenmaier** [comment]
I might have a similar error:

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/25233028/8ba1cb55-d02f-4a2f-a1bb-1efa2245a72e)

I use Win 11 (actual patch installed) and the YoutubeDownloader v1.10.11

Am I right and this is also a symptom of the same problem or should I open another thread?

**Comment by smallprogram** [comment]
some issue
