### ISSUE TITLE
Compare already downloaded videos from same URL prior to downloading

### ISSUE THREAD

**Issue by HighProSoft** [Tyrrrz/YoutubeDownloader#419]
### Version

V1.10.11

### Platform

Windows 11

### Steps to reproduce

Hi, I've noticed if you insert a YT link and select search it lists all videos as normal, then select a folder for the download, If the app stops or you quit the app and restart and insert the same url and select search it lists all the videos again as expected when you select the same download folder it shows the folder as empty and starts downloading all the videos again.

It would be great if when selecting the download folder the app compares already downloaded videos with the search list and removes the downloaded videos from the list. Thanks

Standard app settings.

https://www.youtube.com/playlist?list=PLPSWeKehU4HCFx9fPzz85-Zk1R1ufE5E5

### Details

Be able to compare previously downloaded video's in download folder to search list and remove from search list.

Not comparing already downloaded videos from same URL.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
It's already an option in the settings, although the comparison is done by filename since there is no way to know which video/stream had been downloaded.
