### ISSUE TITLE
Unhandled exception crash on launch

### ISSUE THREAD

**Issue by Retr0-01** [Tyrrrz/YoutubeDownloader#438]
### Version

v1.11 (YoutubeDownloader.win-x86)

### Platform

Windows 11 23H2

### Steps to reproduce

- Run the executable.
- See crash window.

![0QNMh1MDaS6NcP7](https://github.com/Tyrrrz/YoutubeDownloader/assets/61121754/d2afe67c-a45c-4bc7-a5ab-c159ecb572bb)

### Details

- Running the application crashes without any log or error generated.
- The event viewer contains no errors generated from the application.
- There are no debug tracelogs generated.
- .NET 8.0 Runtime is installed (v8.0.4)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Are you sure you're on x86 Windows?

**Comment by Retr0-01** [comment]
Yes I am.

**Comment by Tyrrrz** [comment]
Can you try running `dotnet YoutubeDownloader.dll` from the command line, inside the directory where YoutubeDownloader is extracted?

**Comment by Retr0-01** [comment]
```
PS C:\Users\Retr0\Downloads\YoutubeDownloader.win-x86> dotnet YoutubeDownloader.dll
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'YoutubeDownloader, Version=1.11.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by Retr0-01** [comment]
I apologize as I have misinterpreted your previews question. By checking the system information I released that I indeed tried to run a x86 application on a 64-bit operating system. You are more than welcome to execute me, preferably through public stoning.

The x64 version works without any issues. Closing this before I embarrass myself even more.
Thanks for the help. 👍

**Comment by Tyrrrz** [comment]
No worries, it's a common mistake 🙂
