### ISSUE TITLE
Error downloading any video

### ISSUE THREAD

**Issue by youssef-mohamed-aly** [Tyrrrz/YoutubeDownloader#442]
### Version

1.11.0

### Platform

windows 10

### Steps to reproduce

when ever i try to download a video or playlist it shows me this error 
![zzzz](https://github.com/Tyrrrz/YoutubeDownloader/assets/72819796/80409781-6e4a-4921-9b12-737dfe359f73)

### Details

when ever i try to download a video or playlist it shows me this error 
![zzzz](https://github.com/Tyrrrz/YoutubeDownloader/assets/72819796/80409781-6e4a-4921-9b12-737dfe359f73)

I not signed in on the application 
I tried to sign in and try it again but still the same error occurs
tried to delete and reinstall the application but still

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
That sounds like a transient issue. Does it still happen?

**Comment by youssef-mohamed-aly** [comment]
yep. still facing this issue

**Comment by youssef-mohamed-aly** [comment]
-UPDATE-
i figured out why it was not working, I have been using a VPN related to my work so it used to block any suspicious connection/website 

I appreciate your concern and keep up the good work <3
