### ISSUE TITLE
Failed to extract own playlist title when authenticated

### ISSUE THREAD

**Issue by igormenin** [Tyrrrz/YoutubeDownloader#446]
### Version

1.12.1

### Platform

Windows 11

### Steps to reproduce

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/223437/46e5193d-9500-4dea-9a1c-9b56a17b410d)

Playlist: https://www.youtube.com/playlist?list=PLDJiUIi7YahU4xFJNu-I4DWWN_7k4jjdl

### Details

YouTube login made.
When trying to download the first playlist, the problem occurred.

However, when YouTube is not authenticated, the application works perfectly

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Works for me, are you sure it's not a transient issue?

**Comment by zhaozhao777** [comment]
I have the same problem. I can extract other people's list but not work on mine...
So is this list created by youself?

**Comment by igormenin** [comment]
Exactly, I forgot to mention, the playlist I was trying to download is mine. I didn't test it with other playlists.

When I'm logged in with my YouTube account, my playlists can't be downloaded.

**Comment by igormenin** [comment]
> Works for me, are you sure it's not a transient issue?

Exactly, I forgot to mention, the playlist I was trying to download is mine. I didn't test it with other playlists.

**Comment by Tyrrrz** [comment]
Does it work if you log out?

**Comment by igormenin** [comment]
> Does it work if you log out?

Yes. After disconnecting, the download occurred normally.
