### ISSUE TITLE
Cannot select preferred language for "inject subtitles"

### ISSUE THREAD

**Issue by bentangfat** [Tyrrrz/YoutubeDownloader#458]
### Version

v1.12.2

### Platform

Windows 11

### Steps to reproduce

Cannot select preferred language for "inject subtutles"

### Details

Cannot select preferred language for "inject subtutles"

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project
- [X] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
You don't need to, all languages are injected.

**Comment by hansnolte** [comment]
> You don't need to, all languages are injected.

Hi Tyrrrz,
doesn't work for me.
I have only English Subtitles, but I want German Subtitles.

I have tested with the old Build from here
https://github.com/Tyrrrz/YoutubeDownloader/releases/tag/1.12.2
and a newer one from here.
https://github.com/Tyrrrz/YoutubeDownloader/actions/runs/9752964195

I am on Windows 10.

Best regards
Hans

**Comment by Tyrrrz** [comment]
Which video are you having issues with?

**Comment by hansnolte** [comment]
Hi Tyrrrz,
many thanks for your Answer.
> Which video are you having issues with?

With all of them.
E.g. this one.
https://www.youtube.com/watch?v=GRzoEl3hQEE

Best regards
Hans

Edit:
Do I even have the right version of the YoutubeDownloader or is there another download somewhere that I just haven't found yet?

**Comment by Tyrrrz** [comment]
@hansnolte for that video, I only see the auto-generated English subtitles:

![image](https://github.com/user-attachments/assets/5945ca14-8994-4175-9c61-450db24f86eb)

So it matches what you get in the app. I tried to simulate a German client by requesting the `de-DE` locale, but I still only got the English language (screenshot from YoutubeExplode demo):

![image](https://github.com/user-attachments/assets/989376d9-4194-4dfd-8ed0-bc3d2701ffb9)

So not sure how you're able to see more than one subtitle track.

**Comment by hansnolte** [comment]
Hello Tyrrrz,

thank you very much for testing.

> @hansnolte for that video, I only see the auto-generated English subtitles:



That is strange.

I normally use the [3D Youtube Downloader](https://yd.3dyd.com/home/).
Unfortunately, this no longer works.
It only loads the subtitles and no longer the video.
And with this Davinci-Video, it downloads the German-subtitles without any problems.

Best regards
Hans

German Subtitle:
[DaVinci Resolve 19's AI-Powered Editing Features Explained.de-at.zip](https://github.com/user-attachments/files/16280489/DaVinci.Resolve.19.s.AI-Powered.Editing.Features.Explained.de-at.zip)

**Comment by Tyrrrz** [comment]
I'm not sure then

**Comment by hansnolte** [comment]
> I'm not sure then

?

First, activate the Subtitle once.
Then you can activate the automatic translation.


https://github.com/user-attachments/assets/f0292d1f-95eb-4617-94bf-9fce2ed6f48f
