### ISSUE TITLE
New Option to Include Upload Date in Filename

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#46]
Please add an option so that we can include the **Upload Date** in the filename.

For example:

Title: **Belly Flop Contest**
Upload Date: **July 11, 2019**

Resulting filename:  **Belly Flop Contest 2019-07-11.mp4**

![image](https://user-images.githubusercontent.com/22284653/61126922-bec49e00-a47b-11e9-9f10-2a6a929fa72f.png)

**Comment by Tyrrrz** [comment]
Are you sure this is needed? You can always see the date the file was created at in File Explorer.

**Comment by Tyrrrz** [comment]
Nevermind, I misread upload for download
