### ISSUE TITLE
App gets crashed when typing "FI"

### ISSUE THREAD

**Issue by iminet** [Tyrrrz/YoutubeDownloader#463]
### Version

v1.12.2

### Platform

Windows 11

### Steps to reproduce

- start typing with the letter F... seems no issues
- then type letter I... app crashes immediately.
No other letter combination causes this but F...I... (for example, you'd want to search for "fight")

Tried on 2 different laptops: Asus Zenbook (Windows 11 Home), Dell Latitude (Windows 11 Pro - corporate) and resulted the same experience.

### Details

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/27138272/929d70d7-8aea-4703-a0c5-89cead21d226)

Please fix this to make app able to search for queries starting with FI

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by mikaelmello** [comment]
Looks like a bug on Avalonia: https://github.com/AvaloniaUI/Avalonia/issues/14939

Fixed here, but not released yet: https://github.com/AvaloniaUI/Avalonia/pull/16120

**Comment by Tyrrrz** [comment]
Thanks @mikaelmello. What a crazy bug.

**Comment by iminet** [comment]
Thank you guys for your support.

**Comment by Tyrrrz** [comment]
Will be fixed in Avalonia `11.1.2` judging by this RC: https://github.com/AvaloniaUI/Avalonia/releases/tag/11.1.2-rc1

**Comment by badjuice** [comment]
I was going to report this, decided to check first if any other similar were already created and I was surprised to see that the exact thing was happening with someone else. I was going to download songs from the "Flatbush Zombies", crashing all the time. Ended up writing "fatbush" to circunvent it haha.
