### ISSUE TITLE
Indexed video IDs

### ISSUE THREAD

**Issue by benhmd** [Tyrrrz/YoutubeDownloader#465]
### Version

latest

### Platform

windows 10

### Steps to reproduce

is there a way to number the videos in the playlist, e.g
1. videoa
2. videob
3. videoc

### Details

just a request: is there a way to number the videos in the playlist, e.g
1. videoa
2. videob
3. videoc

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Yes, you can use the `$numc` or `$num` replacement token in the filename template.
