### ISSUE TITLE
Unable to download binocular videos correctly when downloading 180 degree VR 3D videos, only monocular 2D flat videos are available

### ISSUE THREAD

**Issue by xsisiw** [Tyrrrz/YoutubeDownloader#466]
### Version

V1.12.2

### Platform

WIN11

### Steps to reproduce

Unable to download binocular videos correctly when downloading 180 degree VR 3D videos, only monocular 2D flat videos are available

### Details

Unable to download binocular videos correctly when downloading 180 degree VR 3D videos, only monocular 2D flat videos are available

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Can you provide an example video?

**Comment by Tyrrrz** [comment]
This may have been fixed by #519. Please re-open if the issue persists.
