### ISSUE TITLE
Can't download some videos 

### ISSUE THREAD

**Issue by youssef-mohamed-aly** [Tyrrrz/YoutubeDownloader#471]
### Version

1.12.2

### Platform

win10 pro

### Steps to reproduce

video URL:  https://youtu.be/MF1r7MW8UvQ?list=PLgIi4lM74yW0ChmzTdT1w5ruCnqP0bv3J

### Details

![image](https://github.com/user-attachments/assets/bbf0af23-d6fc-490e-8633-a7926327b558)
![image](https://github.com/user-attachments/assets/164f776e-97f2-48ed-84d3-d3b3d74550da)
![image](https://github.com/user-attachments/assets/bc92d2af-c792-442e-b592-cb27ef1f89bc)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
`500 Internal Sever Error` indicate a transient error on YouTube's side. Try again after some time.
