### ISSUE TITLE
No chapters included

### ISSUE THREAD

**Issue by midonasser** [Tyrrrz/YoutubeDownloader#483]
### Version

v1.12.2

### Platform

Windows 11

### Steps to reproduce

![YoutubeDownloader_GODg1i6GQJ](https://github.com/user-attachments/assets/be46fbab-e660-477b-9ccf-2ac64a5779b4)

### Details

no chapters included while downloading arabic videos or any videos

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project
- [X] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by clicky6** [comment]
@Tyrrrz Can this be added as a feature, the ability to inject chapters into the video would be useful for when we want to watch some specific sections of a long video or navigating etc.
