### ISSUE TITLE
cant download videos anymore

### ISSUE THREAD

**Issue by josaicmosaic** [Tyrrrz/YoutubeDownloader#484]
### Version

v1.12.2

### Platform

Windows 11

### Steps to reproduce

https://www.youtube.com/watch?v=51o5J0XVGoc (every video i try does this i just used this video as an example) ![image](https://github.com/user-attachments/assets/739508e2-63bb-4ef7-9bbd-485d31173832) 

### Details

ive been using the program for about 2 weeks now and only today did it start happening, i am authenticated

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by josaicmosiac** [comment]
playlist download works perfectly though with not errors

**Comment by josaicmosaic** [comment]
sometimes playlist downloader works? its like if its the first thing i try to download then it works

**Comment by josaicmosaic** [comment]
never mind a reinstall fixed it
