### ISSUE TITLE
All videos are unavailable

### ISSUE THREAD

**Issue by rddwavecc** [Tyrrrz/YoutubeDownloader#49]
![1564467235724](https://user-images.githubusercontent.com/50062356/62105473-08fbab00-b2d5-11e9-9258-56b683294735.jpg)

I can't use url or youtube videoID to download media today.
any ideas? or youtube just change their rules...

**Comment by Tyrrrz** [comment]
Caused by https://github.com/Tyrrrz/YoutubeExplode/issues/281
