### ISSUE TITLE
Video thumbnail not included in the downloaded file

### ISSUE THREAD

**Issue by mango-1221** [Tyrrrz/YoutubeDownloader#490]
### Version

v1.13.0

### Platform

Windows 10

### Steps to reproduce

https://www.youtube.com/watch?v=BS6fPqnGLWs

Options
Inject media tags, inject subtitles turned on

### Details

On previous versions, when I download the video, the youtube thumbnail was included in the file. After the update, the youtube thumbnail is not included.

![2024-08-24 145447](https://github.com/user-attachments/assets/2286f098-1dc0-45de-9d3e-3d13fe14374d)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Asianese** [comment]
Video files have thumbnails for me, but only when I download stuff as mp3, the album art isn't included. Might be related; started happening since the last update.

Ty

**Comment by Tyrrrz** [comment]
Works for me

![image](https://github.com/user-attachments/assets/4497e145-0549-4d0a-b6b6-8d4ca6a73871)
