### ISSUE TITLE
I can download but authentication is nothing

### ISSUE THREAD

**Issue by ghost** [Tyrrrz/YoutubeDownloader#491]
### Version

v1.13.0

### Platform

win10

### Steps to reproduce

![222](https://github.com/user-attachments/assets/09250831-c8a0-44bd-a703-48e8bf47021f)

### Details

so what can i do.
now most video is not available.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
I have no idea what you are asking

**Comment by ghost** [comment]
> I have no idea what you are asking

sorry.
I tried to log in to my account, but when I clicked the authentication button, the dialog box that popped up was black and nothing.

**Comment by Tyrrrz** [comment]
Try downloading the WebView2 runtime: https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download (Evergreen Bootstrapper)

**Comment by ghost** [comment]
> Try downloading the WebView2 runtime: https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download (Evergreen Bootstrapper)

ok now, thx~
