### ISSUE TITLE
"ntdll.dll" randomly crashes application 

### ISSUE THREAD

**Issue by mezz-source** [Tyrrrz/YoutubeDownloader#493]
### Version

1.13

### Platform

Windows 11

### Steps to reproduce

Open the application, and usually after a random amount of time (you're still able to download videos and edit settings), it crashes. It happens randomly, but it usually occurs within the first minute.
https://youtu.be/RYLrHr3aG4I

### Details

It might be related to a Windows 11 issue, considering System32 isn't a thing anymore. This was the full event log.
I verified my system integrity to make sure it wasn't due to any underlining hard drive corruption, and I'm not sure why after 1.13 it started this issue. It crashes consistently within the minute or two, but functions normally for the time it works.

This at least happens with the `YoutubeDownloader.win-x64.zip` release.

```
Faulting application name: YoutubeDownloader.exe, version: 1.13.0.0, time stamp: 0x66960000
Faulting module name: ntdll.dll, version: 10.0.22621.3733, time stamp: 0x67ca8829
Exception code: 0xc0000409
Fault offset: 0x000000000008f0bf
Faulting process id: 0x0xFD8
Faulting application start time: 0x0x1DAF8D0B90D35E7
Faulting application path: C:\Users\Camey\OneDrive\Desktop\apps\ytDownloader\YoutubeDownloader.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: a49e09c7-3737-437c-8c03-10db309258a4
Faulting package full name: 
Faulting package-relative application ID: 
```

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
That's very unusual, I haven't seen this before.
