### ISSUE TITLE
When trying to download a channel with too many videos it doesn't work

### ISSUE THREAD

**Issue by Honza572** [Tyrrrz/YoutubeDownloader#499]
### Version

1.13.0

### Platform

Windows 10

### Steps to reproduce

https://www.youtube.com/@1AAuto (I like cars)
everything on; parralel limit: 1; file name template: $title, theme: system dark
this is the error I get: https://i.imgur.com/beoFs7n.png

btw the last checkbox is pure gold

### Details

expected behavior: download starts
actual behavior: it throws an error, maybe increase the time it looks for videos? if there's an issue with youtube ban or something, just make it search, wait (and TELL the user it's waiting in order to not get detected), repeat

### Checklist

- [ ] I have not read any of the above and just checked all the boxes to submit the issue
- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [x] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by laggard00** [comment]
I was playing around with this issue, but suddenly I can't replicate it anymore. 
I'm on windows, version 1.13.3 same settings as yours

**Comment by Honza572** [comment]
@laggard00 thanks for the info, I'll try it again in some time

**Comment by Tyrrrz** [comment]
@Honza572 were you able to try again?

**Comment by Honza572** [comment]
@Tyrrrz yes I tried it multiple times in several days that are ~9 months apart, I can try again tomorrow just to reassure it's still an issue with the newest version

**Comment by Tyrrrz** [comment]
Just for context, "playlist is unavailable" has nothing to do with how many videos are in the playlist/channel. Something else is happening.

**Comment by Tyrrrz** [comment]
I tried to reproduce the issue and got the same error as you. Then I opened the corresponding channel uploads playlist in my browser: https://www.youtube.com/playlist?list=UUVvE8kQTuZEykvMFZBVzftg

After that, it seemed to work just fine. My guess is that the corresponding system playlist was not fully materialized until I opened it in the browser. After I did that, the app was able to fetch all 9750 videos without issue.

![image](https://github.com/user-attachments/assets/452a4357-2fa2-469e-a30c-f8b66d7b4cf1)

I'll just file it under an infinite list of YouTube-related oddities.

**Comment by Honza572** [comment]
~~Hi, sorry that it took so long, when I tried it today it threw the error after like 2 seconds. Can you please tell me how you were able to make that playlist? I can't see in on their channel and have no idea how to do so with other channels.~~

Oh wait you simply pasted the text from the error message, interesting. How can I get the same text from any channel?

**Comment by Tyrrrz** [comment]
> Oh wait you simply pasted the text from the error message, interesting. How can I get the same text from any channel?

When you enter a channel URL, YoutubeDownloader automatically converts that to an auto-generated "videos uploaded by channel" system playlist. It works by substituting the `UC` in the beginning of the channel ID with `UU` and using that as the playlist ID.

**Comment by Honza572** [comment]
oh alright thanks😄
