### ISSUE TITLE
Virus total say It's a virus but why ?

### ISSUE THREAD

**Issue by Abraham313** [Tyrrrz/YoutubeDownloader#50]
Here is the scan result of YoutubeDownloader.exe 

https://www.virustotal.com/gui/file/f98434b24a74919dc44b215ed6e32ec156938176d5feab060312d8ae33afc31e/detection

**Comment by Tyrrrz** [comment]
Looks like there's just one scarcely known tool saying it's "suspicious"?

**Comment by eat-it** [comment]
SecureAge APEX marked it as malicious because the files aren't signed that is all. Its not a virus.
