### ISSUE TITLE
Not download long musics

### ISSUE THREAD

**Issue by korenevskiy** [Tyrrrz/YoutubeDownloader#501]
### Version

1.13

### Platform

windows 11

### Steps to reproduce

https://www.youtube.com/watch?v=K3dXnyQjnx8

I can't download music from this music composition.
Downloads up to 30%, and returns an error.
I want to get mp3 or audio webm

### Details

this music track lasts 12 hours, I can't download the audio track in Mp3

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
What is the error?

**Comment by korenevskiy** [comment]
> What is the error?

The fact that it is impossible to download the video from this and other links.
I can't even download just the audio.

**Comment by barboa91** [comment]
You stated there was an error returned. That is what he is asking for. You stated your problem again.

**Comment by korenevskiy** [comment]
Strangely, everything is already working and downloading as it should. I downloaded one file at a time.
But there were mistakes before.
Let me describe the process.
I used the same video link to launch several download
at once, i.e. I download the same video in 2 different formats at once. After that, both downloads gave errors after a long time. That is, if the download was 600 MB, then both jumps for this volume for one video swung maybe by 30% and then gave an error download.
Perhaps such logic should be taken into account in the program, and the download should be run sequentially in this case?
### Or just pop-up to warn about possible problems.

**Comment by Tyrrrz** [comment]
You need to provide the errors you're referring to. It could be any number of things, and I'm not a mind reader.
