### ISSUE TITLE
No login button on Linux

### ISSUE THREAD

**Issue by barboa91** [Tyrrrz/YoutubeDownloader#504]
### Version

1.13.0

### Platform

Arch Linux

### Steps to reproduce

Download package. Unzip run YoutubeDownloader

There is only a cog wheel next to the search query and the Settings does not contain a login function.

### Details

There is only a cog wheel next to the search query and the Settings does not contain a login function.
![Screenshot from 2024-09-05 15-29-10](https://github.com/user-attachments/assets/c5d36c18-80d1-4dcb-a825-2ebecb982ab8)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Yes, this feature is only supported on Windows currently because it relies on the WebView2 runtime. I tried getting it to work on Linux/macOS through other embedded browser runtimes but was unsuccessful.
