### ISSUE TITLE
No thumbnails when downloading videos

### ISSUE THREAD

**Issue by elef88** [Tyrrrz/YoutubeDownloader#506]
### Version

v1.13

### Platform

Windows 10

### Steps to reproduce

Get any youtube link, paste in the url, download as mp3 or other audio file.

### Details

Whenever I download any audio file the thumbnail from YouTube is no longer included. I've tried re-installing the application, but still have the issue. It used to download thumbnails but it seems to have randomly stopped like over a month or so ago.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Did it stop a month ago or does it still work with one of the previous versions?

**Comment by elef88** [comment]
> Did it stop a month ago or does it still work with one of the previous versions?

Ok so I just tested it by downloading v1.12.2 and on that one it is downloading with thumbnails like normal, seems to be just v1.13 that is having the issue

**Comment by Tyrrrz** [comment]
Just to confirm, if you download the same video as mp4/webm, the thumbnail is present? Can you give the video URL?

**Comment by elef88** [comment]
> Just to confirm, if you download the same video as mp4/webm, the thumbnail is present? Can you give the video URL?

Video files show a thumbnail but it's not the same as what is the actual thumbnail which is set on youtube. There's no specific video url I was referring to, it's just in general but here's one as an example: https://youtu.be/FTQbiNvZqaY 

<img width="343" alt="example" src="https://github.com/user-attachments/assets/dc28e545-1dac-4330-8c2d-3b0d79ebf81d">

Here's a screenshot as well, the one on the far left is an mp4 downloaded with v1.12.2, this has the correct thumbnail, next to that is an mp3 also downloaded on v1.12.2, again with the correct thumbnail. To the right of that is an mp4 downloaded with v1.13, it has an incorrect thumbnail and then next to that is the mp3 downloaded with v1.13, with no thumbnail at all. 

Settings are set the same on both downloaders.

**Comment by Tyrrrz** [comment]
Okay then this issue is the same as #490.

I can't reproduce the issue when it comes to `mp4` files -- I see the same thumbnail across both old and new versions.

When it comes to `mp3` files, the thumbnail is indeed not shown in the file explorer, but it is shown when you open the file in a media player, such as VLC. Can you confirm that you see the same behavior here?

**Comment by Tyrrrz** [comment]
Also, out of curiosity, does anything change when you run the app as administrator?

**Comment by elef88** [comment]
Ran the app as admin and the downloads came out the same, so no difference. 

When I open the mp3 from v1.13 in a media player it does not show any thumbnail for me (tried with mpv, vlc, media player and windows media player, all show nothing).

Also yes, I can see now it is a similar issue to that previous thread, but the main reason I opened this one was because the mp3s have no thumbnails at all for me, so I do think my original title is still more suitable.

**Comment by Tyrrrz** [comment]
This is very interesting. Can you please upload the final `mp4`/`mp3` files that your copy of the app produced? I wanna see if there's any difference to mine.

**Comment by elef88** [comment]
https://mega.nz/file/TdNTAR5K#y1HIkNbkIqv62c-VCgxIgHmleCpEyCqnK83Z99IdTSQ
https://mega.nz/file/zBdWSKBK#xjCSPAKo-He-TdqJ4nbHDf7pAcuW0iigHOC6Tq7rIho

heres a mega link for each (mp3 and mp4 downloaded in v1.13), since you cant upload mp3s here

**Comment by Tyrrrz** [comment]
Comparing the `mp4` file:

- My version

![image](https://github.com/user-attachments/assets/38947971-2b16-48f7-bec9-3350b8f5ca2a)

![image](https://github.com/user-attachments/assets/213b0336-1359-4798-a2a4-2661a1857209)

- Your version

![image](https://github.com/user-attachments/assets/6608f656-32df-4e45-bd44-3191f59b6d2b)

![image](https://github.com/user-attachments/assets/bc7d54ea-12f7-47b9-aaf0-463121819c98)

**Comment by Tyrrrz** [comment]
Made sure to download the same stream set as you did (`720p` instead of `1080p`) for a direct comparison:

![image](https://github.com/user-attachments/assets/bd179b83-64be-4193-849d-2e08eef5ed0b)

![image](https://github.com/user-attachments/assets/fd2abd13-b640-459d-aeb8-45762f9db798)

**Comment by Tyrrrz** [comment]
For some reason, your video files are not getting any metadata injected in the post-processing stage and it's not immediately clear to me why.

**Comment by Tyrrrz** [comment]
@elef88 please try this build: https://github.com/Tyrrrz/YoutubeDownloader/actions/runs/10928352117

This should report any errors it encounters during the tagging process

**Comment by EremitaDelle6Vie** [comment]
I have the same issue, for me it has been since 27 august.
I use VLC media player and it doesn't show the thumbnail image when I open the mp3

**Comment by Tyrrrz** [comment]
> I have the same issue, for me it has been since 27 august. I use VLC media player and it doesn't show the thumbnail image when I open the mp3

See above

**Comment by EremitaDelle6Vie** [comment]
I don't understand what I should do in that link but after I updated to the latest version it works properly.
Just one bug, I have the same thumbnail on some mp3 from NCS, sometimes it show the right one, but recently I noticed that different song have the same thumbnail as months ago

**Comment by elef88** [comment]
> @elef88 please try this build: https://github.com/Tyrrrz/YoutubeDownloader/actions/runs/10928352117
> 
> This should report any errors it encounters during the tagging process

Hey sorry forgot about this thread for a while, but I have downloaded the new v1.13.2 today and it is working all correctly on that release, so whatever was changed seems to have fixed the issue for me at least. 

I tried another download just to test it again on v1.13.0 as well and the result is the same as before with no thumbnail, so it looks like there was something wrong with that release specifically with the thumbnails.

I did also try on the build you linked (v999.9.9) but the download just straight up failed for me on that version.

But like I said, it is now working on the latest release so seems pointless to worry about an old release any further.

Thanks

**Comment by Tyrrrz** [comment]
@elef88 thanks for confirming. I still want to understand exactly what was failing.

Did the download fail for unrelated reasons (i.e. the #513 issue that appeared yesterday) or is it related to media tags? You can hover your mouse over the error icon and see the error. You can also copy it by clicking the icon.

**Comment by Tyrrrz** [comment]
Closing since the underlying error is fixed.

**Comment by elef88** [comment]
> @elef88 thanks for confirming. I still want to understand exactly what was failing.
> 
> Did the download fail for unrelated reasons (i.e. the #513 issue that appeared yesterday) or is it related to media tags? You can hover your mouse over the error icon and see the error. You can also copy it by clicking the icon.

I don't believe it was the #513 error, iirc it would look like it's downloading and then just show 'Failed' under the status in red text. It did not show the 403 error pop up like the #513 error. I tried another download on that release just now and now it is the #513 error though, so I can't check what the initial error was right now.

**Comment by Tyrrrz** [comment]
@elef88 try this build please: https://github.com/Tyrrrz/YoutubeDownloader/actions/runs/11074716215
This has the #513 issue fixed.

**Comment by elef88** [comment]
Downloaded this release and it all worked correctly, mp3 had a thumbnail and mp4 thumbnail was also correct.
