### ISSUE TITLE
Watch page is broken please try again in few minutes

### ISSUE THREAD

**Issue by Lurasz** [Tyrrrz/YoutubeDownloader#508]
### Version

v1.13.0

### Platform

Windows 11

### Steps to reproduce

Since yesterday, I receive a 'Video watch page is broken. Please try again in a few minutes.' message when attempting to convert videos. Strangely, this only affects single videos, playlists work just fine. It worked perfectly in the previous days and I have not done anything differently since then.

### Details

I have confirmed that I'm using the latest update. The issue also occurs on other systems/PCs. Any help or suggestions would be greatly appreciated. Thank you!

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by MartitoTV** [comment]
+1 same issue

**Comment by HappyMac3920** [comment]
Same with me.

**Comment by furry72** [comment]
same with me

**Comment by LetsPlayNintendoITA2023** [comment]
same

**Comment by InvixGG** [comment]
Same, tested other versions as well, same issue.

**Comment by a1anon** [comment]
Same,  though it worked 1 time today but now I get the error again.

**Comment by SirPytan** [comment]
Same, for me, also tested it on the 1.12.2 version, same issue.

**Comment by SirPytan** [comment]
![grafik](https://github.com/user-attachments/assets/5bd8c9c3-dda0-40b2-ae7b-4595067b3603)
See image for issue.

**Comment by mohamadpk** [comment]
same as same
