### ISSUE TITLE
403 forbidden download error

### ISSUE THREAD

**Issue by Xxxxmmm** [Tyrrrz/YoutubeDownloader#513]
### Version

v1.13.2

### Platform

windows 11

### Steps to reproduce

![微信截图_20240924214224](https://github.com/user-attachments/assets/9c2564b1-b8e6-49b3-8fe6-0452eb010a60)

### Details

After copying the url and pressing Enter, an error was reported.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by WeihanLi** [comment]
The same issue +1
403 error even when I logout and re-login

![image](https://github.com/user-attachments/assets/0d9866eb-6a38-4728-881e-2daf470f018e)

**Comment by janz420** [comment]
same error
![image](https://github.com/user-attachments/assets/893ec873-a527-496e-9248-84a343a27e1a)

**Comment by DwadeWoW** [comment]
+1

**Comment by verygrape** [comment]
+1

**Comment by Megalaoofania** [comment]
+1, downgrading doesn't seem to help

**Comment by duanbiao2000** [comment]
+1

**Comment by Amanthrai** [comment]
+1
Windows 10 64bit
v1.13.2

**Comment by sprudello** [comment]
+1
Windows 11 
v1.13.2

**Comment by robertofantasy** [comment]
+1

**Comment by puyofan06** [comment]
+1

**Comment by Lurasz** [comment]
+1
Windows 11 Home
v1.13.2

**Comment by yanglc721** [comment]
+1

**Comment by chicpsj1130** [comment]
+1
Windows 11 Home
v1.13.2

**Comment by ishmaelcamillo** [comment]
+1
Windows 11 Home
v1.13.2

**Comment by kevin020803** [comment]
+1
Windows 11 家庭版
v1.13.2

**Comment by elef88** [comment]
same

**Comment by ptly1420** [comment]
+1

**Comment by Tyrrrz** [comment]
Underlying issue: https://github.com/Tyrrrz/YoutubeExplode/issues/817

**Comment by RILuse** [comment]
+1

**Comment by barrettsmithbb** [comment]
I have the same issue on latest 1.13 as well as older 1.9 versions.

**Comment by lamrongol** [comment]
@Tyrrrz You said [the underlying error is fixed](https://github.com/Tyrrrz/YoutubeDownloader/issues/506#issuecomment-2374350156) but if the cause is [android player api is completely turned off](https://github.com/Tyrrrz/YoutubeExplode/issues/817#issuecomment-2374766038), fixing seems impossible. You mean you start to use [YouTube IFrame Player API](https://developers.google.com/youtube/iframe_api_reference)?

**Comment by ElVallon** [comment]
Sadly i'm facing the same issues. I hope they find a solution soon enough as i'm subscribed to various channels that, daily, upload several videos which is a pain to download each of them, individually.

I was going to create a new issue page, when i saw this.

I'm using v1.13.2 on Windows 10 Pro 64 bits.

**Comment by cowling-china** [comment]
+1

**Comment by mrnams** [comment]
![2024-09-26 12_51_45-_new 5 - Notepad++](https://github.com/user-attachments/assets/c11f1eec-cf36-41b2-ad4a-2bd43c4ada10)
Getting same error with latest release v1.13.2

**Comment by EremitaDelle6Vie** [comment]
same issue

**Comment by kennymccormick122** [comment]
Also facing the same issue with the newest release.
![image](https://github.com/user-attachments/assets/9706abc0-f892-46aa-b959-463cb9470e68)

**Comment by woodendoors7** [comment]
![image](https://github.com/user-attachments/assets/51eebcba-daee-476b-acb4-e4d80ae52fe1)
Yup, same issue on v1.13.2

**Comment by GameStartStudio** [comment]
same issue
![Uploading same issue.png…]()

**Comment by ghscode** [comment]
连IDM都不能下载了，也是报403 Forbiden

**Comment by Ertersilva** [comment]
### Same problem, and the search quarry isn't working either

![image](https://github.com/user-attachments/assets/65a819fb-d446-468b-a74f-2518e9380fdd)
![image](https://github.com/user-attachments/assets/3e5bdd7a-56e5-4e6e-ba6f-8c3a31bce7fa)

**Comment by DrunkenMoose** [comment]
Lol I was just about to try to fix the error when I saw it was downloading correctly through Visual Studio. Thanks for the quick fix @Tyrrrz !
