### ISSUE TITLE
403 forbidden download error

### ISSUE THREAD

**Issue by shinogithub202238** [Tyrrrz/YoutubeDownloader#515]
### Version

v1.13.2

### Platform

windows11

### Steps to reproduce

Hello, this is my first time posting a bug.
I use youtubedownloader a lot, but one day I suddenly encountered an error that prevented me from downloading youtube videos.
When I try to recognize the URL, the error message screen shown in the attached image appears.
If you have any suggestions on how to fix this, could you please let me know?
Thank you in advance.

![Snipaste_2024-09-25_20-43-42](https://github.com/user-attachments/assets/32e0d720-4300-43ff-9626-c59e77bf7eec)

Edition Windows 11 Home
Version 23H2
Installation date ‎2024/‎03/‎15
OS Build 22631.4169
Experience Windows Feature Experience Pack 1000.22700.1034.0

### Details

After copying the url and pressing Enter, an error was reported.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by svr333** [comment]
I'm in the exact same situation, I download regularly but today I'm getting the same 403 Forbidden error

**Comment by ptly1420** [comment]
是的，我今天下载的时候也遇到了这个报错，我的版本是 v1.13.2 
![image](https://github.com/user-attachments/assets/dd245faf-6d75-4d2f-b4e3-c0c9228cb1ee)

**Comment by elef88** [comment]
This bug was already posted yesterday

**Comment by HTSPOP** [comment]
I Am also Get Same issue Please Solve It Please

**Comment by Tyrrrz** [comment]
Duplicate of #513
