### ISSUE TITLE
Failed error on downloading videos MP3s and playlists

### ISSUE THREAD

**Issue by calvingalabuzi** [Tyrrrz/YoutubeDownloader#518]
### Version

1.13.2

### Platform

Windows 11

### Steps to reproduce

All URLs are giving the error

### Details

Failed for all Videos i am trying 

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by v100evBG** [comment]
It doesn't work for me too

**Comment by knhkse** [comment]
Also for me..

**Comment by edoardoCame** [comment]
same for me...

**Comment by montypx** [comment]
also for me

**Comment by Tyrrrz** [comment]
Duplicate of #513
