### ISSUE TITLE
Prepend numbering option for playlists

### ISSUE THREAD

**Issue by FullstackSensei** [Tyrrrz/YoutubeDownloader#52]
It would be nice to have an option to prepend a number to each video in a playlist, to maintain order. This is especially useful in courses, which sometimes don't have the lecture number in the video name and depend on the order in the playlist.

Debugging the code, it looks the change needs to be in the DownloadMultipleSetupViewModel.Confirm, by replacing the foreach with a good-old for, and using the (string formatted) loop counter to prepend the filename if the option is selected

**Comment by xamarin-enthusiast** [comment]
@iraqigeek Please vote for this feature request as well. https://github.com/Tyrrrz/YoutubeDownloader/issues/46
