### ISSUE TITLE
An error occurs after pasting the video address and pressing enter

### ISSUE THREAD

**Issue by Fuuto-Joker** [Tyrrrz/YoutubeDownloader#528]
### Version

1.13.3

### Platform

Windows 11

### Steps to reproduce

All settings: default
Logging state: logged
Step 1: paste a URL and press Enter

Result: An error below occurs
![image](https://github.com/user-attachments/assets/b95a2aac-0ac9-4f61-ae89-7d20202823e4)

### Details

![image](https://github.com/user-attachments/assets/bff5a3c3-3131-4405-a1e7-2e7f2c6d478e)
![image](https://github.com/user-attachments/assets/102574c2-bbea-421d-8761-357d6702a573)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by dragokas** [comment]
Same error on Windows 10 with same inputs.
Most likely this is due to "Warning" from Youtube like "materials with dangerous content" where additional mouth click is required.

**Comment by Tyrrrz** [comment]
Try the latest CI build

**Comment by Tyrrrz** [comment]
If this still persists, it could be a duplicate of #540 or #476

**Comment by homersyd** [comment]
this error is happening again, same steps. Could be because it's an age restricted video?

**Comment by Tyrrrz** [comment]
> this error is happening again, same steps. Could be because it's an age restricted video?

Yeah that's very likely
