### ISSUE TITLE
Cannot find documentation on adding a track name under 'file name template'

### ISSUE THREAD

**Issue by pbakes** [Tyrrrz/YoutubeDownloader#529]
### Version

1.13.3

### Platform

Windows 10

### Steps to reproduce

Application settings has option for 'file name template' and gives an example $title as the default, no idea how to add a track number to your files.

### Details

No documentation on other usages. Looking for something that would have a $track or $tracknumber function.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
What is a track number in the context of youtube videos?

**Comment by pbakes** [comment]
If you were downloading a long YouTube playlist that was ordered a specific way, The final output of the download is always going to be alphabetical, it is not going to adhere to the way the playlist was organized.

**Comment by Tyrrrz** [comment]
`$num` (`[1]`, `[2]`, ...) and `$numc` (`1`, `2`, ...)` is what you're looking for. At least the former is documented in the tooltip.

https://github.com/Tyrrrz/YoutubeDownloader/blob/c81e56c201c7b24f602a55668e5b1b1675e8a27d/YoutubeDownloader.Core/Downloading/FileNameTemplate.cs#L18-L19
