### ISSUE TITLE
Cannot play a video downloaded in quality above than 1080p in mp4

### ISSUE THREAD

**Issue by Jienniers** [Tyrrrz/YoutubeDownloader#531]
### Version

v1.33.3

### Platform

Windows 10

### Steps to reproduce

Video URL: https://www.youtube.com/watch?v=bB3-CUMERIU
Video Quality: 2160p
Click download
Play the downloaded video
I have tried running the video in windows media player and also in after effects

### Details

Expected Behavior: video plays at 2160p resolution fine.
Actual Behavior: Video doesn't play and give this error The Item was encoded in a format that's not supported
![Screenshot 2024-10-22 231242](https://github.com/user-attachments/assets/0ce73505-787c-4ea9-af08-aa323c8e4f5f)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by 7urnin** [comment]
try webm format？

**Comment by Jienniers** [comment]
it works with webm but not mp4

**Comment by Tyrrrz** [comment]
It might just be a missing (proprietary) codec, as it says.

Try downloading the K-Lite Codec Pack: https://codecguide.com/download_kl.htm

**Comment by Jienniers** [comment]
so it means you can't do anything and, it just depends on youtube?

**Comment by Tyrrrz** [comment]
Most likely, but try installing the codec pack to ensure it's not just a corrupted video stream

**Comment by Jienniers** [comment]
Okay
