### ISSUE TITLE
There is no format option

### ISSUE THREAD

**Issue by rongchaua** [Tyrrrz/YoutubeDownloader#54]
I try to download this video
https://www.youtube.com/watch?v=R9XFucAl3nQ&t=4s

But there is no Format Option in the drop down

![1](https://user-images.githubusercontent.com/6661713/64713390-118ef600-d4bd-11e9-93fe-334d1f6cd5e1.PNG)

**Comment by Tyrrrz** [comment]
Caused by https://github.com/Tyrrrz/YoutubeExplode/issues/296

**Comment by Tyrrrz** [comment]
YouTube reverted their changes
