### ISSUE TITLE
Video watch page is broken?

### ISSUE THREAD

**Issue by DipperTheCoder** [Tyrrrz/YoutubeDownloader#543]
### Version

1.13.3

### Platform

Windows 10

### Steps to reproduce

![01](https://github.com/user-attachments/assets/9bd2a65e-da73-416d-83ff-9e51248c1c40)

### Details

it was alright yesterday,suddenly shows this,no matter what video url I put in.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by DipperTheCoder** [comment]
half an hour later,it repaired itself,i don't know why

**Comment by knhkse** [comment]
Same problem here.. In my case, it doesn't repair at all ㅜ_ㅜ

**Comment by knhkse** [comment]
> Same problem here.. In my case, it doesn't repair at all ㅜ_ㅜ

I solved this problem by removing authentication (logout). It seems there is an issue about google account or something..?

**Comment by Tyrrrz** [comment]
> half an hour later,it repaired itself,i don't know why

This happens sometimes. Certain transient errors are easier to outwait than to diagnose.
