### ISSUE TITLE
Download a video in alternative languages

### ISSUE THREAD

**Issue by kersplash-wav** [Tyrrrz/YoutubeDownloader#549]
### Version

1.13.3

### Platform

Windows 11

### Steps to reproduce

Trying to download murder drones https://www.youtube.com/watch?v=mImFz8mkaHo in english

### Details

No language options

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Language options are not supported currently
