### ISSUE TITLE
Error: Object reference not set to an instance of an object in v1.5.7

### ISSUE THREAD

**Issue by xamarin-enthusiast** [Tyrrrz/YoutubeDownloader#55]
In v1.5.7, we are getting a lot of "**Object reference not set to an instance of an object**" errors when trying to download.

![image](https://user-images.githubusercontent.com/22284653/64714325-73833780-d48c-11e9-8061-5ba3cddd776d.png)

Then app crashes...

![image](https://user-images.githubusercontent.com/22284653/64714492-bb09c380-d48c-11e9-8bdc-b2aa43d38260.png)

**Comment by Tyrrrz** [comment]
Duplicate of #54 
Caused by https://github.com/Tyrrrz/YoutubeExplode/issues/296
