### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by DipperTheCoder** [Tyrrrz/YoutubeDownloader#558]
### Version

1.13.3

### Platform

Windows 10

### Steps to reproduce

I used to use this downloader pretty well,but now it's always like this,why?

### Details

![0](https://github.com/user-attachments/assets/93e287ca-4c78-433b-b2f2-e8f7c8654a4f)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by yizhibibao125** [comment]
I also have the same problem. I haven't found the correct solution.

**Comment by redmangame** [comment]
+1

**Comment by DipperTheCoder** [comment]
I updated newest version,it back to this rate limit bug again:
![2](https://github.com/user-attachments/assets/06c0daa8-052f-4ada-8497-7ebe4934d968)

**Comment by DipperTheCoder** [comment]
now it back to 400 bad request again,cool.
![3](https://github.com/user-attachments/assets/38c45185-fa5e-4356-899d-fd1cd10cad46)

**Comment by cucarol** [comment]
try log out ur google account, it works for the same error i met🧐

**Comment by DipperTheCoder** [comment]
> try log out ur google account, it works for the same error i met🧐

yeah i know, it used to work for me, but now it doesn't work.

**Comment by blancopedro** [comment]
I have the same problem with private videos. Any solution?

**Comment by DNA-I-CHING** [comment]
+1

**Comment by DalbanDalban** [comment]
+1
Already tried logging out -> logging in again -> still not solved. 
Also tried using a different Google account but still doesn’t work.

**Comment by introspection3** [comment]
same

**Comment by ShiroQuest** [comment]
Same here

**Comment by snowshoes** [comment]
same

**Comment by Tyrrrz** [comment]
The 429 rate limit error means that YouTube has rate-limited requests from your client, so you have to wait before the restrictions clear.

The 400 bad request error is already covered by the #550 issue.
