### ISSUE TITLE
Cant seem to login with the authenticator 

### ISSUE THREAD

**Issue by IshMocha** [Tyrrrz/YoutubeDownloader#559]
### Version

1.13.3

### Platform

windows 10

### Steps to reproduce

not being logged in
trying to authenticate

### Details

tried logging in and the authentication screen just goes black

![image](https://github.com/user-attachments/assets/04d3cd2a-bf18-4c02-ac47-2091ef9ced43)

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Try installing WebView2 runtime: https://developer.microsoft.com/microsoft-edge/webview2

It should normally be part of your Windows distribution.
