### ISSUE TITLE
Notification when new update version is avaible

### ISSUE THREAD

**Issue by giwrgosmant** [Tyrrrz/YoutubeDownloader#56]
Is it possible to add a notification when you open the app and new update version is avaible with redirect link to releases?

**Comment by Tyrrrz** [comment]
It should update automatically on launch if you let it open for a minute.

**Comment by giwrgosmant** [comment]
Oh! I didn't knew that and I never noticed it.

Then maybe a notification: new version avaible and updating or something like that. It will be kinda useful to know when the app is going to update, in what version..etc, even better with changelog.

If you find it difficult or uncessery to be implemented no worries. 
Thanks for your clarification anyway.👍

**Comment by Tyrrrz** [comment]
A notification makes sense, I'll implement it. Thanks.
