### ISSUE TITLE
Download not original audiotrack

### ISSUE THREAD

**Issue by manveldavid** [Tyrrrz/YoutubeDownloader#560]
### Version

1.14

### Platform

Windows 11

### Steps to reproduce

Video URL: https://www.youtube.com/watch?v=tpg3VvoIVfA&ab_channel=MarkRober
Download Settings: any
Application Settings: any
Without Authorization
------
- Step 1: Paste link in query textbox
- Step 2: Choise any downloading option
- Step 3: Download video
- Step 4: Check the video audiotrack not original

### Details

- Expected behaviour: download video with original audiotrack
- Actual behaviour: download video with random multi-language audiotrack

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Cannot reproduce. I see all languages and English is the default.

![image](https://github.com/user-attachments/assets/47825a92-31d0-4d85-84b6-b62a181f2b19)

**Comment by manveldavid** [comment]
I'm sorry. It's my fault. I worked with master branch and the issue reproduced.
