### ISSUE TITLE
Remove malware for russian users

### ISSUE THREAD

**Issue by ROKBAS** [Tyrrrz/YoutubeDownloader#569]
### Version

v1.14

### Platform

Windows 11

### Steps to reproduce

Open program from region that contains russia

### Details

- Expected behaviour
Works like intended, not trying to promote propaganda speeches into yours apps.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by ROKBAS** [comment]
![2024-12-27 13 28 26](https://github.com/user-attachments/assets/98b4c55d-da88-48e5-b1c4-1657b3e411ff)

**Comment by Tyrrrz** [comment]
Russian users _are_ the malware
