### ISSUE TITLE
Can't add to queue with a download in progress in v1.6.0

### ISSUE THREAD

**Issue by BDaddyG** [Tyrrrz/YoutubeDownloader#59]
Hello

After updating to v1.6.0 I can no longer add additional videos to the download queue while a download is in progress.  The additional video URL can be entered in the download field but clicking the --> or pressing Enter has no effect. 

Thanks for this program!

**Comment by Tyrrrz** [comment]
Has this actually been possible pre-1.6? 😮

**Comment by BDaddyG** [comment]
I was running v1.5.7 and was able to add to the running queue.  The auto update took me to v1.6.0 where the I no longer could.

**Comment by Tyrrrz** [comment]
Sorry about that. I'll look into fixing it.
