### ISSUE TITLE
Tag Audio Files missing - "$num" and "date" infront and in the end of file name

### ISSUE THREAD

**Issue by giwrgosmant** [Tyrrrz/YoutubeDownloader#60]
With version 1.16.1, when I  download MP3, the file has infront of name: "$num" and in the end "the date" and also doesn't automatically tag audio files like version 1.16.

**Comment by Tyrrrz** [comment]
Can you give me video URL?
And have you tried the exact same video in 1.16?

**Comment by giwrgosmant** [comment]
I've tried couple of different songs-videos and happens to all of them.
Just checked now with 1.16 version and doing the same thing... but I am pretty sure it wasn't like that before couple of days.
You can try this link for example (but happens to every song-video I've tried): https://www.youtube.com/watch?v=ssFWRxMJjYg

**Comment by Tyrrrz** [comment]
Looks like something very specific, tagging works for me.
![image](https://user-images.githubusercontent.com/1935960/65457311-f2487f00-de53-11e9-8e15-ceff6948fb5d.png)

**Comment by Tyrrrz** [comment]
Regarding the second part, go to settings and change file name format by removing `$num` and `$uploadDate`

**Comment by giwrgosmant** [comment]
> 
> 
> Regarding the second part, go to settings and change file name format by removing `$num` and `$uploadDate`

Auto Tag seem fixed now, and by removing $num and $uploadDate the name of the file is fixed too.
I don't know why that happened...it was fine before, I didn't change anything besides I did the update. 
Anyways...thanks a lot! 👍 Keep it up 😜

**Comment by Tyrrrz** [comment]
>I don't know why that happened...it was fine before, I didn't change anything besides I did the update.

Yeah it was added last update to let you configure default file names. `$num` thing is a bug which will be fixed next release.

>Anyways...thanks a lot! 👍 Keep it up 😜

Thanks :)
