### ISSUE TITLE
Add adaptive updating playlist

### ISSUE THREAD

**Issue by eat-it** [Tyrrrz/YoutubeDownloader#61]
I have a playlist that updates every few days, some new videos, maybe some get deleted or privated. But when downloading the same playlist to the same folder it will overwrite to all 0 bytes and redownload videos that are already downloaded. Also the program doesn’t respond and sometimes crashes when dealing with playlists that have more than a thousand videos.

**Comment by Tyrrrz** [comment]
There is now an option to skip downloading existing files, which should do the trick.
