### ISSUE TITLE
Failed all time

### ISSUE THREAD

**Issue by ycaoyang** [Tyrrrz/YoutubeDownloader#63]
I'm using Window10, after deploying by executing powserscript (by "unblock-file"). It works fine until downloading Failed All Time at about 11%~13%.
I have not installed .NET CORE 3.0 so the project can't be debug. If you have some idea about the issue, please send me the instructions.
Thanks very much

**Comment by Tyrrrz** [comment]
>I'm using Window10, after deploying by executing powserscript (by "unblock-file").

What exactly do you mean by "deploying by executing powserscript (by "unblock-file")"?

**Comment by ycaoyang** [comment]
Hello,
There is a Powershell script in Deploy folder. Since the execution policy on my computer, I used Unblock-File comlet to open the gate to the script. The installation has been done successfully. That’s all.
The application works but the download never succeeds.

**Comment by Tyrrrz** [comment]
Can you simply download the latest release here?
https://github.com/Tyrrrz/YoutubeDownloader/releases

**Comment by ycaoyang** [comment]
Thanks very much.
The release version works on my machine.

Le 29 septembre 2019 à 10:51, Alexey Golub <notifications@github.com> a écrit :



Can you simply download the latest release here?
https://github.com/Tyrrrz/YoutubeDownloader/releases

**Comment by Tyrrrz** [comment]
Great
