### ISSUE TITLE
Convert error on 32-bit OS because of 64-bit ffmpeg.exe

### ISSUE THREAD

**Issue by abyssox** [Tyrrrz/YoutubeDownloader#65]
When running this program on a 32-bit OS the conversion to e.g. mp3 fails with error "the specified executable file is not a valid application for this operating system platform" due to 64-bit ffmpeg.exe.

Maybe don't include ffmpeg.exe in zip file at all and instead download the appropriate version at first program start?

**Comment by Tyrrrz** [comment]
Generally 32bit OS are a thing of the past. I'll see if it's worth addressing.

**Comment by abyssox** [comment]
> 
> 
> Generally 32bit OS are a thing of the past.

Totally agree with you on that. Don't waste too much time on this. It's just one user who complained about it.

**Comment by Tyrrrz** [comment]
Closing as won't fix because there are a lot of problems with getting the app working properly on 32 bit, and I think in this day and age it's not really worth it anymore.
