### ISSUE TITLE
Auto Link Import from Clipboard

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#66]
Hey, can you add the feature that the YT-Downloader automatically copy the Links from the Clipboard into the search bar, when new Links are copied?

**Comment by Tyrrrz** [comment]
If I understand it correctly, you want it to automatically paste for you so that you don't have to press Ctrl+V?

**Comment by derech1e** [comment]
Not quite, my idea was that the program is open in the background and offers to you to to download the Video when a YT link was copied. It should appear a little Windows Notification/Infobox at the bottom right.
Like here: https://www.howtogeek.com/wp-content/uploads/2015/05/sshot-0.png.pagespeed.ce.Z-ea4fnhi0.png
