### ISSUE TITLE
How do you run the application?

### ISSUE THREAD

**Issue by tbMan100** [Tyrrrz/YoutubeDownloader#67]
Sorry if this sounds like a basic question, but how do you run this?

**Comment by mwarth** [comment]
1. Download latest YoutubeDownloader.zip from [Release Page](https://github.com/Tyrrrz/YoutubeDownloader/releases)

1. Unzip

1. Double Click YoutubeDownloader.exe

**Comment by tbMan100** [comment]
Thanks
