### ISSUE TITLE
Add the size of video

### ISSUE THREAD

**Issue by A-bahattab** [Tyrrrz/YoutubeDownloader#68]
need to let the user know the size of the video will be downloaded. when the user chose 720p or 480 how much the size of each kind? i hope that this is the right place to implements some kind of problems. thanks

**Comment by Tyrrrz** [comment]
Unfortunately the size is not known beforehand because the video is muxed from two separate streams. It can only be estimated.

**Comment by Tyrrrz** [comment]
Related/duplicate of #34
