### ISSUE TITLE
Must detect already downloaded file

### ISSUE THREAD

**Issue by mrnams** [Tyrrrz/YoutubeDownloader#69]
It must detect already downloaded file in downloaded location and if file exist then just show finish.
While downloading playlists many time same video is added in different playlist and currently it gets downloaded multiple times.

**Comment by mrnams** [comment]
@Tyrrrz @floatas  Hi All anybody working on issue #69 
https://github.com/Tyrrrz/YoutubeDownloader/issues/69#issue-518272531 

This is very easy to fix and **MOST useful** functionality.

**Comment by Tyrrrz** [comment]
Hi.
You are welcome to create a pull request with the changes.

**Comment by mrnams** [comment]
@Tyrrrz Ok I shall try once time permit me.

**Comment by mrnams** [comment]
Thanks @Tyrrrz @floatas @mostafa901
