### ISSUE TITLE
Livestream downloader

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#70]
I had today an interesting idea. Can you add a "Livestream-Writer"? The Downloader should start writing the livestream and convert to the selected format when finished. Is that possible?

**Comment by Tyrrrz** [comment]
Unfortunately, it's currently not possible because https://github.com/Tyrrrz/YoutubeExplode doesn't support live streams.

**Comment by derech1e** [comment]
Okay, that is sad :/
