### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [Tyrrrz/YoutubeDownloader#71]
Hello! Thank you very much for the program! Added it to our free software website ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/ss-youtube-downloader-%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-%D1%81-youtube.html)).
I’ll duplicate the text in Russian, if it will be more convenient.
The old very popular program for downloading videos from YouTube stopped working, for a long time did nothing with the page and then decided to replace it without major changes. Therefore, the name of the program on the page is slightly different, it is necessary for search engine optimization.
I sincerely hope that you will not give up such a cool project!

Здравствуйте! Спасибо большое за программу! Добавил её на наш сайт о свободном программном обеспечении ([ссылка](https://континентсвободы.рф/мультимедиа/прочее/ss-youtube-downloader-скачать-видео-с-youtube.html)). 
Продублирую текст на русском языке, если так удобнее будет.
Старая очень популярная программа для скачивания видео с ютуб перестала работать, долгое время ничего не делал со страницей и тут решил заменить без кардинальных изменений. Поэтому на странице название программы немного отличается, это нужно для поисковой оптимизации.
Искренне надеюсь, что Вы не будете бросать столь крутой проект!

**Comment by Tyrrrz** [comment]
Cool :)
