### ISSUE TITLE
Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by mrnams** [Tyrrrz/YoutubeDownloader#73]
Version 1.7 

Issue
When try to open https://www.youtube.com/watch?v=XokfEvGAgiE, 
it gives below error
Value cannot be null. (Parameter 'source')
Screenshot attched.
![2019-11-15 15_27_23-YoutubeDownloader v1 7 0](https://user-images.githubusercontent.com/31761152/68934506-cb0b8f80-07bc-11ea-9d5d-6058cdbd20bb.png)

**Comment by ewkratz** [comment]
Same here, but it looks like you already recognize this as a bug. Reverting to 1.6.1 for now.

**Comment by Tyrrrz** [comment]
Does it work on 1.6.1?

**Comment by ewkratz** [comment]
> Does it work on 1.6.1?

Yes, that's working and in the code as well. You moved the skip existing from the code I have, it's on the download page in that code.
It downloaded the update but I didn't run it.

**Comment by Tyrrrz** [comment]
Thanks for reporting, should be fixed now.

**Comment by ewkratz** [comment]
Yes, it's working now. Thank you for all your work, this is a great tool!

**Comment by Tyrrrz** [comment]
Glad you like it :)
