### ISSUE TITLE
Album Media Cover

### ISSUE THREAD

**Issue by the-karanshah4** [Tyrrrz/YoutubeDownloader#74]
Hi, I have been using this wonderful All in One application for 2 days. I appreciate your work.
The reason I found this application was, I was looking for an application to save audio from youtube with **album media cover** (picture, thumbnail). To date I had to do it manually, if you can implement this feature it would be great. One more I am not sure about is, I don't see **Singer or album name in saved audio files** whereas your webpage mentions 'Automatic media tagging for audio downloads'. It would be great for me to have such information taken from youtube video description and added directly in the file. This one seems difficult, so if you can say anything about it.

**Comment by Tyrrrz** [comment]
Hi, thank you for using this.

>To date I had to do it manually...

Have you tried [MusicBrainz Picard](https://picard.musicbrainz.org/) or other similar tools? They are specifically for tagging audio files and you can batch an entire collection of music through them.

>...Singer or album name in saved audio files whereas your webpage mentions 'Automatic media tagging for audio downloads'...

It will try to infer the artist/song name from video title and then search musicbrainz to verify the match. If it can't extract the info from the title or if musicbrainz doesn't have info on a specific song, the metadata will not be injected. Generally speaking, the success rate is not as high as one could hope and I'm open for ideas on how to improve it.

**Comment by the-karanshah4** [comment]
Alright.
I already have tools for such things. I was just expecting it if it was possible to get the cover image injected directly from your application taken from youtube thumbnail.
Anyway, thanks.

**Comment by Tyrrrz** [comment]
Using video thumbnail is possible, I didn't realize that was what you were suggesting.
