### ISSUE TITLE
Version 1.7.1 does not work

### ISSUE THREAD

**Issue by giwrgosmant** [Tyrrrz/YoutubeDownloader#75]
I've updated from 1.6.1 to 1.7.1 and after that the application does not run. I double click the .exe and nothing happens. I've tried to run as admin, same result.
I've downloaded the whole version from github but again nothing happens.
I've tried to go back to 1.6.1 and it's working fine.

**Comment by Tyrrrz** [comment]
Hey, you need to install .NET Core Runtime.
The details are here: https://github.com/Tyrrrz/YoutubeDownloader/releases/tag/1.7

**Comment by giwrgosmant** [comment]
Oh yeah just saw the changelog. 
Thanks 👍

**Comment by Tyrrrz** [comment]
Great!
I know it's bad UX that the app doesn't work after auto-updating, but this shouldn't happen in the future.
