### ISSUE TITLE
Program doesn't launch at all

### ISSUE THREAD

**Issue by aphexetwine** [Tyrrrz/YoutubeDownloader#76]
For the past week or so the program simply stopped launching when I try to run it. I tried with the latest version as well and still doesn't work. I'm running Windows 10 x64.
Is there any data file/folder I can delete so I can try again?

**Comment by Tyrrrz** [comment]
Hi, starting from version 1.7 you need to install .NET Core runtime as [mentioned in release notes](https://github.com/Tyrrrz/YoutubeDownloader/releases).

**Comment by Simulacrux** [comment]
Hi,

would it be possible to do a "zip" package with the .Net Core as beside loading? A self-contained executable is it called official from MS I think. And with a bit of tweaking only the used DLLs would be part of that set (see [https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx](url))
Would be much appreciated and a bit easier then installing the Framework.

Cheers
Simulacrux
