### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by lucidBrot** [Tyrrrz/YoutubeDownloader#77]
I love this program, thank you very much for it!
However, I have now encountered a crash.

## Issue
link: https://www.youtube.com/watch?v=DDAsAyAqaHk
Results in this error once I press Download:
![image](https://user-images.githubusercontent.com/4920691/70825687-488ae580-1de5-11ea-93f5-cd340d383f09.png)
The reason for the crash is likely that I have no Format selected. That is because there is no option - the dropdown list is empty. All previous downloads worked flawlessly as mp3.

One thing that jumps out to me in this Error Message is that it happens in `D:\a\YoutubeDownloader\YoutubeDownloader\YoutubeDownloader\ViewModels\Dialogs\DownloadSingleSetupViewModel.cs` while the program is installed on drive F under `F:\Programme\Tools\youtubeDownloaderTyrrz`. `D:\\` is my CD drive.
But that's probably not that relevant. The [line where the exception occurs can be found here](https://github.com/Tyrrrz/YoutubeDownloader/blob/master/YoutubeDownloader/ViewModels/Dialogs/DownloadSingleSetupViewModel.cs#L47)

I have found a `YoutubeDownloader.exe.12216.dmp` file in `AppData\Local\CrashLogs` from the time it crashed. I do not know what information it contains, so I would prefer to not upload it publicly.

## System
Win 10 Pro, 64 bit
Version 1703 (Build 15063.1058)

## Expected Behaviour
Download the video. If that does not work, tell me without crashing.

## Reproducability
This happens both with the link above as well as with the short link https://youtu.be/DDAsAyAqaHk . It keeps happening with those links, but other links work - they have formats listed.

**Comment by lucidBrot** [comment]
https://youtu.be/LSbi55d842Q exhibits the same behaviour whereas https://www.youtube.com/watch?v=TEM4J8b4XIU and https://youtu.be/TEM4J8b4XIU work as expected.

**Comment by lucidBrot** [comment]
I wanted to make sure this is still reproducible on my machine... and it is still for https://www.youtube.com/watch?v=DDAsAyAqaHk and the short form https://youtu.be/DDAsAyAqaHk , but https://youtu.be/LSbi55d842Q is now working. 😅

**Comment by Tyrrrz** [comment]
Hey, this is caused by recent YouTube changes, fix is coming soon.

**Comment by Tyrrrz** [comment]
Related to #78
