### ISSUE TITLE
No entries in the dropdown menu for "format"...

### ISSUE THREAD

**Issue by JAKAMI99** [Tyrrrz/YoutubeDownloader#78]
when downloading with an url.
Only if I use the search function, then the drop down menus has any entries :/
Runtime 3.1.0 installed (windows 10)

**Comment by JAKAMI99** [comment]
Nevermind, it only happens with a few examples like "billie eilish bad guy" for some reason...

**Comment by lucidBrot** [comment]
This is likely the same issue as https://github.com/Tyrrrz/YoutubeDownloader/issues/77

**Comment by Tyrrrz** [comment]
Hey, this is caused by recent YouTube changes, fix is coming soon.
