### ISSUE TITLE
New version prompts to download .Net Core after installation

### ISSUE THREAD

**Issue by ewkratz** [Tyrrrz/YoutubeDownloader#79]
I ran the update today and after it completes an message box pops up and says .Net core needs to be downloaded and prompts to install but clicking yes to download does nothing.

**Comment by Tyrrrz** [comment]
Weird that nothing happens, it should open [this link](https://dotnet.microsoft.com/download/dotnet-core/current/runtime). There you can follow the steps for "run desktop apps".

**Comment by ewkratz** [comment]
Thanks, I did download it and install it separately, I just posted on here because it looks like it will install but doesn't load it automatically.
Thanks for all your work on this and your responsiveness!

**Comment by Tyrrrz** [comment]
Thank you!

This indeed sounds like a problem, I'll report it to Microsoft.

There are still lots of potential improvements here on their side, at least it informs that a runtime is missing instead of silently exiting like before :)

https://github.com/dotnet/core-setup/issues/8902

**Comment by Tyrrrz** [comment]
@ewkratz 
Could it be that you had .NET Core runtime 3.0 installed previously? One other user reported a similar error and they said that after uninstalling previous runtime, clicking on 'yes' worked correctly. Just trying to gather additional info for the report.

**Comment by ewkratz** [comment]
Yes, that was the issue, still odd that the MS downloader doesn't recognize it and prompt to update instead of it showing as missing. Thanks

**Comment by Proaxel** [comment]
I would like to expand on this issue; the error still occurs even when I have both of the .Net installations installed. This version still refuses to launch, giving said prompt telling me to install it. I even reinstalled both .Net installations just to make sure. Why is it telling me to install it when it is already installed? Is it a detection issue?

**Comment by Tyrrrz** [comment]
Just to confirm, what do you mean by "both" .NET installations?

**Comment by Proaxel** [comment]
The .NET Core Runtime, and the .NET Core Desktop Runtime.

**Comment by Tyrrrz** [comment]
Did you install version 3.0 or 3.1?

**Comment by Proaxel** [comment]
I’m using 3.0, as that was the one linked in the changelog.md. Should it be 3.1? If so the message should be a bit more clear, something like “this requires 3.1 to run, you have (current version/not installed)”. Maybe also mention that on the release page as well.

**Comment by Tyrrrz** [comment]
Good point, it started targeting 3.1 but changelog doesn't reflect that, I will update it. The link in readme should take you to 3.1 though. https://dotnet.microsoft.com/download/dotnet-core/current/runtime

**Comment by Tyrrrz** [comment]
Gonna be closing this as the underlying issue on Microsoft's side and they are tracking it already. I replaced all links to point towards 3.1 so hopefully it will avoid further confusion.
