### ISSUE TITLE
Suggest on feature

### ISSUE THREAD

**Issue by pheonixfirewingz** [Tyrrrz/YoutubeDownloader#8]
can you add multiple options of quality to the mp3 sound format and can you add .wav support to this is turning out to be awsome

**Comment by lckinggis** [comment]
Download subtitles！

**Comment by Tyrrrz** [comment]
What kind of qualities do you want for mp3?

**Comment by cdlixucd** [comment]
can you release a mac Version?i used it in PC,it's very awsome!!!

**Comment by pheonixfirewingz** [comment]
128bit to 320bit

**Comment by pheonixfirewingz** [comment]
@cdlixucd just download mono and use that compiler to run it on mac for the libs used idk youtube how to convert it

**Comment by Tyrrrz** [comment]
Does it really make a difference for you which bitrate it is? What's your use case?

You can't use it with mono. Don't have plans for a Mac version, mostly because I don't use one.

**Comment by pheonixfirewingz** [comment]
@Tyrrrz , when you are converting them to midi it dose do to you, have to convert it to mp3 first to convert it to midi

**Comment by Tyrrrz** [comment]
I'm not sure I understand how 128bit/s vs 320bit/s matters here

**Comment by cdlixucd** [comment]
Ok. Thanks very much
