### ISSUE TITLE
What quality is used for a playlist

### ISSUE THREAD

**Issue by raelb** [Tyrrrz/YoutubeDownloader#80]
Hi,
When downloading a single url, a whole list of quality options is available.
For a playlist only a simple dropdown is shown:

![image](https://user-images.githubusercontent.com/13108198/71660934-40bfc080-2d55-11ea-80e5-c67dfd6e7ca4.png)

What download quality is used in this case?

**Comment by Tyrrrz** [comment]
Hi,
That's because every video has different set of qualities available.
This will download highest possible quality stream for selected format in case with webm or mp4. In case with mp3 or ogg, it will download highest bitrate audio and convert it.

**Comment by raelb** [comment]
It would be useful if some selection could be made, and then program will download that format or less. For example if 1080p is available and it's a large playlist, there could be a large difference in bandwidth  / computer space and user may only want 720/480. In a way for a playlist, selecting the desired format is more important :)

**Comment by Tyrrrz** [comment]
That's a good point. Perhaps the selection could instead be "Maximum quality".

**Comment by raelb** [comment]
Sounds good. Also, for some playlists e.g. from the same author, all videos may be of the same quality.
