### ISSUE TITLE
General option to (de)select download formats

### ISSUE THREAD

**Issue by raelb** [Tyrrrz/YoutubeDownloader#81]
Hi,
A suggestion: To have a general option where one can effectively exclude certain formats from formats dropdown.
For e.g., I usually want to download in mp4 not webm. So if webm is excluded from the dropdown list, it would make selecting the desired format easier, instead of having to wade through a large list of formats I'm never interested in.

**Comment by grafst** [comment]
This would also be a great feature for less experienced users who don't know much about audio/video codecs
