### ISSUE TITLE
Program cannot be opened after 1 use

### ISSUE THREAD

**Issue by thisisreallife** [Tyrrrz/YoutubeDownloader#82]
I can use your program very well, thanks for your hard work! 

**Just 1 problem that the program can not be reopened after one download task.** 

**Description of my user journey:**
1. downloaded your zip and unziped it.
2. click `YoutubeDownloader.exe` to open it and download some playlist 
3. can not reopen `YoutubeDownloader.exe`. (I clicked it and my mouse pointer showes a sand clock for about 0.1 sec. After that, nothing happened.)

**My environment:**
1. win10 **enterprise** edition with english language interface
2. use it with SSR since I am in China

**My solution:**
I delete my old folder and then unzip to install again. This trick always workes. However,  I am wondering why this happend? Anyone have the same issue with me?

**Comment by Tyrrrz** [comment]
Hi.
What version of the program did you launch that works?

**Comment by thisisreallife** [comment]
The issue happened on  `version 1.6.1`.  I updated to `1.7.2` today and downloaded severl playlists. The issue do not show up anymore

**Comment by Tyrrrz** [comment]
Great then :)
