### ISSUE TITLE
For big playlists, only the first 200 titles will be added

### ISSUE THREAD

**Issue by polynoman** [Tyrrrz/YoutubeDownloader#83]
As the title says, only the first 200 titles of a playlist will be shown for a big playlist.

When opening a big playlist on YouTube, also only the first 200 titles will be shown on the side of the video. So maybe this could be related to the YouTube Explode library in use.

Here is an example playlist with more than 200 titles:
https://www.youtube.com/watch?v=X0H2FNAH4bY&list=OLAK5uy_mtOdjCW76nDvf5yOzgcAVMYpJ5gcW5uKU

As workaround, I used another way to get the links of the remaining titles and added them afterwards.

**Comment by Tyrrrz** [comment]
Hm, weird. I'll take a look.

**Comment by polynoman** [comment]
I believe I found the reason:

In the file  YoutubeExplode/YoutubeExplode/YoutubeClient.Playlist.cs of the YoutubeExplode Library there is the request URL for the playlist:

https://youtube.com/list_ajax?style=json&action_get_list=1&list={playlistId}&index={index}&hl=en

with index set to zero. This will return the first 200 titles of the playlist (1-200). When I set the index to 201, it returned the titles 101 to 300, which is also 200. When I use an index that is higher than the max of playlist titles, then it returns the first 200. (I tried it with index=400 on the example playlist, which has 369 titles). For index 301, it returns titles 170-369, which is the last 200 titles.

Is there a way to get the playlist size beforehand and then calculate how many requests have to be done, or another way to request the complete playlist at once?

Here is mentioned that a playlist has a maximum of 5000 titles:
https://support.google.com/youtubemusic/thread/3590426?hl=en

**Comment by Tyrrrz** [comment]
> with index set to zero. This will return the first 200 titles of the playlist (1-200). When I set the index to 201, it returned the titles 101 to 300, which is also 200. When I use an index that is higher than the max of playlist titles, then it returns the first 200. (I tried it with index=400 on the example playlist, which has 369 titles). For index 301, it returns titles 170-369, which is the last 200 titles.

That's right. But if I remember correctly, that's how it's supposed to work right now. Have you managed to figure out why it stops at the first 200 videos?

> Is there a way to get the playlist size beforehand and then calculate how many requests have to be done, or another way to request the complete playlist at once?

I guess it's possible with another request + HTML parsing. But I don't think there's any info regarding this in the response we're currently using.

**Comment by Tyrrrz** [comment]
So umm I checked and found two interesting things:

1. https://www.youtube.com/watch?v=X0H2FNAH4bY&list=OLAK5uy_mtOdjCW76nDvf5yOzgcAVMYpJ5gcW5uKU only shows 200 videos as well
2. All videos seem unavailable from the embed player but they're playing normally on watch page.

Which is weird. But since YoutubeExplode relies on the results from the embed page, it seems to only return those 200 videos.

**Comment by polynoman** [comment]
I have found the bug in YouTubeExplode and made a pull request for that.

**Comment by Tyrrrz** [comment]
Linking https://github.com/Tyrrrz/YoutubeExplode/issues/337
