### ISSUE TITLE
Reverse the order of downloaded videos?

### ISSUE THREAD

**Issue by JesperHalvorsen** [Tyrrrz/YoutubeDownloader#84]
For me, it would make more sense, if the newest download was at the top of the list, not the bottom.

Not a big issue, but I would make it easier to monitor the progress of the last video without have to scroll to the bottom of the list.

**Comment by badijm** [comment]
Hi, I can grab this one, if available.

@Tyrrrz

**Comment by Tyrrrz** [comment]
@badijm sure.

**Comment by badijm** [comment]
@Tyrrrz 

I've sent PR. Lemme know about any code improvements. 

#132
