### ISSUE TITLE
Add options to specify a default path for downloads, default format and default resolution

### ISSUE THREAD

**Issue by Kareem-42** [Tyrrrz/YoutubeDownloader#85]
Just to save time for people who most of the time download the same format and resolution in the same path, so you can save two steps (choosing the format & resolution then the path) when you use the default options.

**Comment by Tyrrrz** [comment]
The path and format are already pre-selected based on your last input.

**Comment by Kareem-42** [comment]
For the path, yes it remembers the last input, but you have to do the path selecting step anyway, for the format, it always select the first format from the format/resolution list, my point is it would be great if there is a way to do a "one step download", where the user adds the link and click download, if his default format and resolution is available in the list and the default path is a correct one, you spare him from those steps and download directly.

**Comment by Tyrrrz** [comment]
Just double-checked, if you, say, downloaded a video in `mp4 / 720p` then the app will try to select that same download option next time you try to download a video. It will only fallback to the first one if that option is not available.
