### ISSUE TITLE
Add an option to choose the resolution when downloading a playlist

### ISSUE THREAD

**Issue by Kareem-42** [Tyrrrz/YoutubeDownloader#86]

**Comment by mrnams** [comment]
@Tyrrrz @Kareem-Badr @mostafa901  
Add an option to choose the resolution when downloading a Playlist Or Please download highest available quality videos,while downloading playlist.

**Comment by Tyrrrz** [comment]
It's already downloading highest quality for the selected format @mrnams

**Comment by brogowski** [comment]
Hi, I took a spin on adding resolutions to playlist download modal - can you take a look at #139 ?
