### ISSUE TITLE
Export Playlist info to CSV?

### ISSUE THREAD

**Issue by josephrooks** [Tyrrrz/YoutubeDownloader#87]
Any chance of taking the data you pull from YouTube and show in the UI, and making it possible to export that as a CSV file instead of downloading the videos?

I'd love to be able to grab a listing of the actual contents of some long running series playlists for a project, not necessarily download the videos themselves, and in trying out your tool it seems like all of the data I would need is getting pulled in.

I don't know how easy or difficult this would be, but it'd be incredibly useful.

**Comment by Tyrrrz** [comment]
If you're writing in C#, you can already use [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode) for that.

**Comment by josephrooks** [comment]
I'm not actually developing an application for it myself, just using this one in various ways, so I was curious to know if it was the kind of thing that might be supported in your UI. Is there a way to do that through the command line with YoutubeExplode? I'm not a developer but I can usually figure these things out if pointed in the right direction.

**Comment by Tyrrrz** [comment]
It's not possible to do with YoutubeDownloader as it's a bit out of scope. You can try using [youtube-dl](https://youtube-dl.org) with the command described [here](https://superuser.com/a/1359132) to save the list of videos in a playlist.
