### ISSUE TITLE
Video Failed to Download

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#89]
Hey, why i can't download that Video?

https://www.youtube.com/watch?v=-nIV5e1v93w

**Comment by Tyrrrz** [comment]
Underlying issue: https://github.com/Tyrrrz/YoutubeExplode/issues/349

**Comment by Teezton** [comment]
> Underlying issue: [Tyrrrz/YoutubeExplode#349](https://github.com/Tyrrrz/YoutubeExplode/issues/349)

When it's gonna be fixed? Thank you.

**Comment by Tyrrrz** [comment]
I'm planning to invest some time into this issue later next week.

**Comment by ewkratz** [comment]
Is there a way to turn off the auto update besides digging in the code? Version 1.7.2 works fine, but it downloads the update when opened so once I close it will be updated again.

**Comment by lgphy** [comment]
version 1.7.5 can't download: https://www.youtube.com/watch?v=bOzPTtzdhFk    
please check and update what's the problem ?

**Comment by NeilMJohnson** [comment]
Tyrrrz - the new release fixed the problem - there are only 2 videos where the content restriction message shows up - both from a specific author.  All of the rest which did not download previously, now work.  Thanks!
BTW, sometime in the last 2-3 releases the performance improved quite dramatically.  At one point, many of my downloads failed at 98%, the failure rate has dropped way down and the speed at which videos download has improved.  Thanks for that as well.

**Comment by Tyrrrz** [comment]
@NeilMJohnson glad to hear!
