### ISSUE TITLE
Failed to save settings

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#90]
I got this error, when I close the Downloader:
![image](https://user-images.githubusercontent.com/39240736/77074198-c0723880-69f0-11ea-9799-7a5fdfa5fac4.png)

It only happen, when I hide the Main Folder and execute the downloader over the shortcut.

**Comment by Tyrrrz** [comment]
It looks like it can't have settings because the directory you put it in has write protection.
