### ISSUE TITLE
Download a list fail

### ISSUE THREAD

**Issue by yan-zhongbao** [Tyrrrz/YoutubeDownloader#92]
I want to download this URL:
https://www.youtube.com/watch?v=SOrb5n5fy8w&list=UUZJJTxA36ZPNTJ1WFIByaeA
there are 244 videos on this list when I download, all status is pending and then to 'X Failed'
if I click the restart button to download one by one, it works well. click more than 100 items and start one by one its a hard work. I think maybe you can fix this problem. 
I am in China, used this program with a VPN,  maybe it's the issue from.
Thank you for this downloader.

**Comment by Tyrrrz** [comment]
Hey.
If you right click on the download list, you can restart all failed downloads.
![image](https://user-images.githubusercontent.com/1935960/77825275-db3f5e00-7110-11ea-9f05-edfec960ba2f.png)

**Comment by yan-zhongbao** [comment]
I know this function, but it didn't work for the list I post. when I clicked to restart all, then all task changed status to 'pending... ' then to 'X Failed'. 
I try edit code to fix this problem, I add a event TaskEnded when 'IsCanceled ,IsSuccessful,IsFailed' changed to value true. but then in some case, the restart button didn't work. I don't know much about WPF, so I don't know how to fix it. 
Now the program can download the list for me, only some times its crash. I think it is not good to  pull  it until I fix all the bug

**Comment by Tyrrrz** [comment]
I think the problem is the fact that some videos can't be downloaded currently.
See #89. I'll fix it eventually.
