### ISSUE TITLE
Automatically paste URL

### ISSUE THREAD

**Issue by lgphy** [Tyrrrz/YoutubeDownloader#96]
great thanks your work. 
if  it's possible after copy the youtube Url, then the Downloader can automatically paste the Url, or automatically pop-up a tips " whether you want to download this video or audio ? " click "OK" directly start the download,

**Comment by Tyrrrz** [comment]
I don't see the problem with copying and pasting yourself. I wouldn't want an application to intercept my clipbaord buffer.
