### ISSUE TITLE
Urls from private Playlists throws Errors

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeDownloader#97]
Hey, i found this Problem:
If you want to download a Video over the URL and the Video is an Elmement of a private Playlist, its throw this error:
![image](https://user-images.githubusercontent.com/39240736/79149149-ff649580-7dc6-11ea-8928-0473fb965d64.png)

[Video URL](https://www.youtube.com/watch?v=CLXSQpMgink&list=LLAjXJVR1WPNfcp9nvDLLWZQ&index=131&t=0s)

It is not a serious problem, because if you copy only the Video ID it works all fine.
Anyways i dont care about this issue, but it would be nice if you can fix it. Thank you for this nice Programm! :D

**Comment by Tyrrrz** [comment]
It's just that this URL is a playlist URL so it tries to load it as playlist, but since it's private - it fails.

**Comment by derech1e** [comment]
> Es ist nur so, dass diese URL eine Wiedergabelisten-URL ist, also versucht sie, sie als Wiedergabeliste zu laden, aber da sie privat ist, schlägt sie fehl.

Ok, yeah I just wanted to create an issue for that to help other Users :)

**Comment by Tyrrrz** [comment]
Unfortunately, there's literally nothing in the response that would help us differentiate between a playlist which is private and a playlist that doesn't exist. Closing this as "can't be implemented".
