### ISSUE TITLE
Non-BPM character

### ISSUE THREAD

**Issue by nthomasCUBE** [Tyrrrz/YoutubeDownloader#98]
hi,
great tool, maybe you find a workaround for cases where the video.title
contains strange characters, e.g. try-catch or so
as video can be still downloaded

br

download_youtube_video.py", line 43, in download_youtube_video
    print('Download Started: %s' % video.title)
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 79-79: Non-BMP character not supported in Tk

**Comment by Tyrrrz** [comment]
Wrong repository. This is not the project you're looking for.

**Comment by nthomasCUBE** [comment]
sry, thanks, should be 'YouTubeDownload', will add it there
