### ISSUE TITLE
Don't download updates automatically

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Tyrrrz/YoutubeDownloader#99]
This is more of an enhancement:

Some people may not want the program to automatically download updates when it detects an update.

For example, I am using mobile hotspot for my laptop, and I don't want it to download the updates.

**Comment by Tyrrrz** [comment]
Hi.
It's reasonable. However, for this application, the updates usually deliver fixes that update the underlying library when YouTube breaks something. If I let users disable it, I'm afraid they will create issues claiming that nothing works, but that's because they're on older (broken) version.

**Comment by Pythonic-Rainbow** [comment]
In that case maybe just label those issues as duplicated and close them?  
I don't know how often YouTube breaks things. If they do this quite frequently then I agree auto-downloading updates is mandatory.  

Another solution is that when the software detects an update, warns users that staying in an old version may result in malfunctions, and please try updating to the latest version in you encouter any problems.

**Comment by Pythonic-Rainbow** [comment]
Thank you!
